import type { PresentationScene } from './types';

export const PRESENTATION_SCENES: PresentationScene[] = [
  {
    id: 1,
    title: 'Oracle Essbase OCI Modernization',
    subtitle: 'Tractor Manufacturing — Planning Infrastructure Transformation',
    description: 'This portal covers the complete architectural design, cloud migration strategy, and performance transformation from a legacy on-premise Essbase 11 deployment to a modern OCI 21c Hybrid Storage engine serving global manufacturing planning teams.',
    voiceText: 'Welcome to the Oracle Essbase OCI Modernization Portal for Tractor Manufacturing. In this presentation, we walk through the complete transformation of our planning infrastructure — from a legacy on-premise deployment to a modern, high-performance cloud-native architecture on Oracle Cloud Infrastructure. You will see the multi-dimensional cube structure, the target OCI virtual cloud network design, the six-phase migration roadmap, and the dramatic performance results that justify this investment.',
    durationMs: 10000,
    visualType: 'intro',
  },
  {
    id: 2,
    title: 'Tractor Manufacturing Essbase Core',
    subtitle: 'High-Performance Analytics on Oracle Cloud Infrastructure',
    description: 'This presentation outlines the modernization of our Tractor Manufacturing analytical engine. Shifting our legacy on-premise Essbase deployment to OCI delivers massive performance, scalability, and flexibility benefits for our distributed global planning teams.',
    voiceText: 'Our Oracle Essbase modernization initiative centers on the tractor manufacturing analytical engine and its cloud migration strategy. Today, we review the cube structure powering financial planning across our compact, utility, and row-crop product lines, the target cloud infrastructure, the phased timeline, and the stakeholder communication protocols that keep all teams aligned.',
    durationMs: 9500,
    visualType: 'intro',
  },
  {
    id: 3,
    title: 'Multi-Dimensional Cube Outline',
    subtitle: 'Tuning Tractor Manufacturing Dimensions for Hybrid Storage',
    description: 'Our Tractor Manufacturing Cube structures metrics cleanly across seven specialized dimensions. Heavy product and manufacturing hierarchies sit in Sparse dimensions, while dense financial formulas occupy Dense dimensions — enabling fast parallel calculations without long pre-aggregation windows.',
    voiceText: 'We have structured our planning engine across seven core dimensions, including Product, Plant, and Market. Measures and Scenario are classified as dense dimensions — they live inside every data block. Product and Plant are sparse — they define the address space of blocks that actually contain data. By utilizing modern Hybrid BSO and ASO storage, we combine fast financial formulas with massive dealer-level detail, eliminating the overnight batch calculation windows our planners previously endured.',
    durationMs: 11000,
    visualType: 'cube',
  },
  {
    id: 4,
    title: 'Target OCI Cloud Architecture',
    subtitle: 'Double-Subnet VCN, High Availability, and ADW Integration',
    description: 'The target OCI architecture separates web-tier, application-tier, and database-tier traffic across strict VCN subnets. Essbase servers run on powerful Compute VM shapes, leveraging OCI File Storage Service for high-availability clustering and Autonomous Data Warehouse for fast transactional storage.',
    voiceText: 'Our cloud architecture utilizes a double-subnet private virtual cloud network. Smart View users access the Essbase server securely through an active OCI Load Balancer and IPSec VPN connection. The private application subnet hosts two clustered Essbase 21c compute nodes, with shared cube files and application logs mounted from OCI File Storage Service — guaranteeing seamless failover. Oracle Autonomous Data Warehouse in the private database subnet handles all ETL landing tables and the Essbase metadata repository.',
    durationMs: 12500,
    visualType: 'architecture',
  },
  {
    id: 5,
    title: 'The Gated Migration Roadmap',
    subtitle: '6-Phase Deployment Plan with Testing Milestones',
    description: 'To minimize production risk, the migration follows a gated 6-phase approach: Assessment, Cloud Provisioning, Cube Modernization, ETL Integration, Performance Validation, and Cutover. Each phase requires sign-off before the next begins, guaranteeing a zero-data-loss and highly secure transition.',
    voiceText: 'To guarantee success, the migration roadmap spans six clear phases. Phase one begins with a full inventory of on-premise 11.1.2 cubes, rule files, and MaxL scripts. Phases two and three provision the OCI foundation and re-platform the cube to 21c Hybrid mode. Phase four integrates the manufacturing ERP data pipeline. Phase five is the critical testing gate — thirty days of parallel operation with automated result comparison. Phase six is go-live: DNS cutover and decommission of the on-premise cluster.',
    durationMs: 11500,
    visualType: 'roadmap',
  },
  {
    id: 6,
    title: 'OCI Scalability & Performance Gains',
    subtitle: 'Moving from 8-Hour Batch Cycles to Real-Time What-If Simulations',
    description: 'On-premise Essbase calculations took up to 8 hours daily. With OCI dynamic hybrid aggregation, calculations happen instantly on request. Coupled with automated vertical scaling, technical leads can expand processing power dynamically during peak manufacturing budget forecasting cycles.',
    voiceText: 'Deploying on OCI delivers exceptional scalability and performance gains. The full IronField cube aggregation — all models, all plants, all time periods — dropped from eight hours and forty minutes on-premise to four point two seconds on OCI 21c Hybrid storage. That is a seven-thousand two-hundred times improvement. Manufacturing leads can now simulate raw material cost fluctuations in real time, and the DBA team shifted from overnight hardware maintenance to application tuning and user support.',
    durationMs: 11000,
    visualType: 'gains',
  },
  {
    id: 7,
    title: 'Project Summary & Go-Live Readiness',
    subtitle: 'Key Outcomes, Business Value, and Next Steps',
    description: 'The modernization delivers a 7,200× aggregation speedup, 60% reduction in administrative overhead, and enables real-time what-if simulations across all tractor product lines. The six-phase gated roadmap ensures zero-data-loss cutover with full stakeholder alignment.',
    voiceText: 'In summary, migrating our Tractor Manufacturing planning engine to Oracle Cloud Infrastructure delivers transformational results. Aggregation time drops from eight and a half hours to under five seconds — a seven-thousand-two-hundred times improvement. Administrative overhead drops by sixty percent, freeing the DBA team for application work rather than hardware maintenance. Planning teams gain real-time what-if simulation capability across all tractor series. The six-phase gated roadmap, with built-in testing checkpoints and thirty days of parallel validation, ensures a zero-data-loss cutover. Infrastructure is provisioned, teams are aligned, and we are ready for go-live.',
    durationMs: 12000,
    visualType: 'summary',
  },
];
