import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'Oracle Explain Plan and Execution Plans: How the CBO Chooses, What to Read, and Where Plans Go Wrong',
  slug: 'oracle-explain-plan-execution-plans-cbo',
  excerpt:
    'The Oracle Cost-Based Optimizer evaluates every SQL statement before execution, selecting a plan based on object statistics, cardinality estimates, and I/O cost models — but EXPLAIN PLAN shows only estimates while real execution plans reveal what actually happened. Understanding the gap between estimated and actual row counts is the central diagnostic skill for resolving plan regressions, index selection failures, and suboptimal join order decisions. This post covers how to read execution plans, when each join method and index access path is chosen, and how plan stability mechanisms like SQL Plan Baselines and SQL Patches protect production workloads.',
  category: 'oracle-database' as const,
  published: true,
  isPremium: false,
  publishedAt: new Date('2026-06-05'),
  youtubeUrl: null,
  content: `# Oracle Explain Plan and Execution Plans: How the CBO Chooses, What to Read, and Where Plans Go Wrong

## Introduction

Every SQL statement submitted to Oracle passes through the Cost-Based Optimizer before a single row is fetched. The CBO's sole job is to transform the declarative intent of a SQL statement — "give me employees hired after 2020 who work in department 60" — into the lowest-cost procedural execution strategy available given the current schema structure, object statistics, and session parameters. That strategy is an execution plan: a tree of operations that specifies which indexes to use, which join method to apply, and in what order to access each table. The plan is generated fresh on every hard parse, and it is the CBO's best estimate of efficiency given what it knows at parse time.

The distinction between EXPLAIN PLAN and a real execution plan is fundamental and frequently misunderstood. EXPLAIN PLAN populates Oracle's plan table with the plan the optimizer would choose if it were to execute the statement right now — but it does not execute the statement. The plan it produces is entirely estimated: estimated row counts, estimated cost, estimated memory usage. A real execution plan, captured from V$SQL_PLAN_STATISTICS_ALL or via DBMS_XPLAN.DISPLAY_CURSOR with the ALLSTATS format, records what actually happened during execution: how many rows each plan step actually returned, how much memory was actually consumed, and how long each operation actually took.

Developers and DBAs are routinely surprised to discover that the plan Oracle chose at runtime differs from the plan they saw in EXPLAIN PLAN, or that the plan looks reasonable but performance is catastrophic. Both surprises have the same underlying cause: the plan shown by EXPLAIN PLAN is generated for the session's current environment and uses estimated values at every step. If the session has different optimizer parameters than the production connection pool, the plan will differ. If statistics are stale, the estimated row counts will be wrong. If the statement uses bind variables, EXPLAIN PLAN has no visibility into the bind values and must use default selectivity assumptions — which may bear no resemblance to the actual data distribution the bind values select at runtime.

The root cause of most plan performance problems is cardinality estimation error: the CBO estimated that a particular plan step would return N rows, but it actually returned 100N or N/100 rows. Cardinality errors compound through the join tree. An overestimate of the driving row set can force a hash join where nested loops would be far more efficient. An underestimate can produce nested loops that iterate millions of times against a table that should have been hash-joined. Understanding execution plans means, above all else, learning to find and interpret these estimation gaps — and then tracing them back to missing statistics, stale histograms, or bind variable peeking artifacts.

## The Cost-Based Optimizer: What "Cost" Actually Means

Oracle's cost model assigns a numeric cost to each plan operation and sums these costs to compare candidate plans. The unit of cost is a single-block I/O — a random read of one Oracle block from disk. Multiblock I/O (used for full table scans and index fast full scans) is cheaper per block because the operating system can service multiple blocks in a single physical I/O; the CBO uses the DB_FILE_MULTIBLOCK_READ_COUNT parameter to estimate how many blocks are delivered per multiblock I/O call. CPU cost is added on top of I/O cost using a CPU-to-I/O conversion factor derived from the system statistics gathered by DBMS_STATS.GATHER_SYSTEM_STATS. For distributed queries — SQL that spans a database link — network cost is also factored in.

To assign cost to an operation, the CBO needs to estimate how many rows that operation will process. This estimate is called cardinality. For a single-table access, cardinality is estimated as the table's row count multiplied by the selectivity of all predicates applied to that table. Selectivity for an equality predicate on a column without a histogram is estimated as 1 / NDV (number of distinct values). For a range predicate, selectivity is estimated using the column's min and max values. The accuracy of both estimates depends entirely on the quality of the column statistics: if NDV is stale, selectivity will be wrong; if min/max values have not been refreshed after a bulk insert, range selectivity will be wrong. Histograms capture data distribution non-uniformity — a column like ORDER_STATUS where 95% of rows are 'CLOSED' and 5% are 'OPEN' has a very different actual selectivity for each value than the 1/NDV default estimate would suggest.

Cardinality errors compound through join trees in a way that is critical to understand. If the CBO estimates 10 rows from the first join input but 1,000 rows actually emerge, every downstream operation — the join method, the join order, the memory allocation for hash joins — was sized for 10 rows and will perform poorly for 1,000. In a three-table join, estimation errors in the first two tables multiply: a 10× error on table A and a 5× error on table B produce a 50× error in the estimated cardinality feeding into the join with table C, which in turn corrupts the cost estimate for the entire remaining plan tree. This compounding is why cardinality estimation errors are so disproportionately damaging and why fixing the root estimation error — by refreshing statistics, adding a histogram, or creating a column group statistic — often fixes a bad plan without any other intervention.

Bind variable peeking adds another dimension of complexity. On the first hard parse of a SQL statement that contains bind variables, Oracle peeks at the current bind values and uses them to estimate cardinality — exactly as if they were literal values. The resulting plan is then cached in the shared pool. On subsequent executions, even if the bind values change dramatically, Oracle reuses the cached plan unless a new hard parse is triggered. A plan optimized for bind value = 1 (which selects a single row) will be reused when the same query runs with bind value = 'ACTIVE' (which selects 40% of the table). Adaptive Cursor Sharing (ACS), introduced in Oracle 11g, partially addresses this: the optimizer marks bind-sensitive cursors and monitors actual row counts over multiple executions; if a different bind value distribution warrants a different plan, Oracle allows a second child cursor to be created with a plan optimized for that bind value range. ACS is not foolproof and adds shared pool pressure through cursor proliferation, but it significantly reduces the plan sensitivity problem for OLTP queries with bind variable skew.

## EXPLAIN PLAN: The Estimated Plan

EXPLAIN PLAN is the oldest and simplest way to inspect what plan Oracle would choose for a SQL statement. It executes the parse and plan generation phases but stops before executing the statement, writing the resulting plan tree to the PLAN_TABLE (a global temporary table created automatically in most modern Oracle installations) or to a user-specified alternative. The statement does not run, no rows are fetched, and no locks are held. This makes EXPLAIN PLAN safe to run against any statement, including expensive full-table-scan queries on production systems, as long as you only want the estimated plan.

The DBMS_XPLAN.DISPLAY function formats the plan table contents into the familiar plan output. Calling it as SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'ALL')) formats the most recently explained plan in the current session with all available columns. The plan is displayed as a tree printed left-to-right: each row is a plan step, and indentation reflects the parent-child relationship. The deepest (most-indented) step in each branch executes first, feeding rows upward to its parent. Reading a plan tree correctly means tracing execution from the bottom-most leaf nodes upward, following the data flow.

The columns that matter most in an estimated plan are: Operation and Options (what the step does — TABLE ACCESS FULL, INDEX RANGE SCAN, HASH JOIN, etc.); Object Name (which table or index is being accessed); Rows (the CBO's cardinality estimate for this step); Bytes (estimated data volume); Cost (the step's contribution to total plan cost); and the Predicate Information section at the bottom of the formatted output, which shows Access Predicates and Filter Predicates separately. This access/filter distinction is diagnostically important. Access predicates are used by the storage engine to locate rows — they drive index range scans, partition pruning, and cluster key lookups. Filter predicates are applied after rows have already been retrieved: the storage engine fetched a row, then Oracle tested the filter predicate and discarded the row if the predicate evaluated to false. A filter predicate on a TABLE ACCESS BY INDEX ROWID step means Oracle is visiting an index, fetching rows from the table, and then discarding many of them — a strong signal that either a different index should be used or a composite index should be created that includes the filter column.

The limitations of EXPLAIN PLAN are significant. Bind variables are unknown at explain time; Oracle uses a default selectivity of 1% for equality predicates on bind-variable columns unless statistics have been gathered with histograms that can inform a better estimate. The plan is generated using the session's current optimizer parameters, NLS settings, and schema visibility — which may differ from the production application's connection settings. Most importantly, the EXPLAIN PLAN output shows no actual row counts, no actual elapsed times, and no actual memory usage. A plan that looks perfectly reasonable in EXPLAIN PLAN — a nested loops join using an index range scan — can be catastrophically slow in production if the index range scan is returning far more rows than the CBO estimated, turning the nested loops into a multi-million-iteration loop.

## Real Execution Plans: V$SQL_PLAN and DBMS_XPLAN.DISPLAY_CURSOR

The authoritative source for execution plan diagnostics is the actual plan captured from V$SQL_PLAN and augmented with runtime statistics from V$SQL_PLAN_STATISTICS_ALL. Unlike EXPLAIN PLAN, these views capture the plan used for a specific execution of a specific SQL statement and, with the right instrumentation, show exactly what happened at each step.

To retrieve the actual plan for a SQL statement currently in the shared pool, query V$SQL to find the SQL_ID and CHILD_NUMBER, then call DBMS_XPLAN.DISPLAY_CURSOR. The format parameter controls the detail level: 'ALLSTATS LAST' shows actual row counts (A-Rows), actual memory used, and actual elapsed time per operation for the most recent execution. The '+PEEKED_BINDS' addition shows the bind variable values that were used at parse time — essential for diagnosing bind variable peeking artifacts. The 'ALL' format includes all predicate information and plan notes. The ALLSTATS LAST output adds two columns that EXPLAIN PLAN never has: E-Rows (the CBO's estimated row count for each step) and A-Rows (the actual rows returned during the last execution).

The E-Rows vs A-Rows comparison is the single most important diagnostic in execution plan analysis. A step where E-Rows = 1 and A-Rows = 847,293 is not a tuning observation — it is a definitive identification of where the plan went wrong. The CBO built its entire plan assuming that step would return one row; instead it returned nearly a million. Every plan decision downstream of that step — join method, join order, memory allocation, sort algorithm — was sized for one row. This is the cardinality estimation error that explains the bad plan, and fixing the statistics that caused that single estimation error will often fix the plan entirely, without any hints, outlines, or plan freezing.

The plan operations themselves carry meaning that must be understood to diagnose plans correctly. TABLE ACCESS FULL reads every block of the table using multiblock I/O — appropriate for large result sets but catastrophic for selective queries on large tables. TABLE ACCESS BY INDEX ROWID fetches individual table rows using ROWIDs from an index — appropriate when the number of rows is small relative to the table size. INDEX RANGE SCAN reads a contiguous range of index leaf blocks — the workhorse of OLTP query plans, appropriate when the predicate selects a small fraction of index entries. INDEX UNIQUE SCAN uses a single index leaf block lookup for an equality predicate on a unique or primary key — the fastest possible row retrieval. HASH JOIN builds a hash table in memory from the smaller of two join inputs, then probes it with the larger input — optimal for large unsorted joins where neither side has a useful index. NESTED LOOPS executes the inner table lookup once per row from the outer (driving) table — optimal when the driving row set is small and the inner table has a selective index. MERGE JOIN requires both inputs to be sorted on the join key — rarely chosen in OLTP, but can be optimal for range-based joins where both inputs are already sorted.

## Reading Join Methods and Access Paths

The three Oracle join methods each have a specific performance profile and set of conditions under which they are optimal. Understanding these conditions is what allows a DBA to look at a plan and immediately identify whether the chosen join method makes sense given the data volumes involved.

Nested Loops are the join of choice for OLTP queries where the driving row set is small — typically fewer than a few hundred rows — and the inner table has a selective index on the join column. The algorithm is simple: for each row in the outer (driving) table, Oracle performs an index lookup on the inner table and fetches the matching rows. With a highly selective index and a small driving set, the total I/O is low. The catastrophic failure mode for Nested Loops is a large driving set: if the outer table produces 100,000 rows, Oracle performs 100,000 individual index lookups on the inner table, each requiring multiple block reads. This is why a cardinality overestimate on the driving table — the CBO thinks the driving table returns 5 rows but it actually returns 100,000 — is so dangerous: the CBO chooses Nested Loops because it looks cheap for 5 rows, but runtime performance is orders of magnitude worse.

Hash Joins are optimal for joining large sets where neither side has a useful index on the join column. Oracle builds a hash table in memory from the smaller input (the build side), then scans the larger input (the probe side) and probes the hash table for each row. Memory is allocated from the PGA sort area; if the build side is too large to fit in memory, Oracle spills to a temporary tablespace (a "one-pass" or "multi-pass" hash join, identifiable in the plan by the HASH JOIN BUFFERED operation and in runtime statistics by the Temp Space column). Hash Joins are insensitive to order and do not require indexes, making them the natural choice for large analytical joins. The failure mode is memory pressure: if PGA_AGGREGATE_LIMIT is too restrictive and many hash joins are spilling to disk simultaneously, I/O from temporary tablespace can dominate overall query time.

Merge Joins require both inputs to be already sorted on the join key, or to be sorted as part of the join operation (a SORT JOIN step appears in the plan). They scan both sorted inputs in parallel, merging matching rows as they advance through each input — a single pass over both sets with no hash table overhead. Merge Joins are rarely the optimal choice in pure OLTP, but they naturally arise when both join inputs are already ordered by their respective index accesses, and the optimizer can avoid the sort step entirely. They are occasionally optimal for range-based joins where both tables' relevant columns are indexed in key order.

Index access paths require careful interpretation. INDEX UNIQUE SCAN is always a single-block operation that fetches exactly one index entry — it is used for equality predicates on unique or primary key columns and is essentially free in I/O terms. INDEX RANGE SCAN reads a contiguous range of index leaf blocks between the high-key and low-key values of the predicate; its cost scales linearly with the number of index entries in the range, and it is appropriate when the predicate is selective relative to the total table size. INDEX FULL SCAN reads all index blocks in key order using single-block I/O; it is chosen when the query needs output in key order (avoiding a SORT ORDER BY step) and the index contains all columns referenced by the query (a covering index scenario). INDEX FAST FULL SCAN reads all index blocks in storage order using multiblock I/O — faster than INDEX FULL SCAN for counting or aggregating all rows when the index is narrower than the table, but it does not preserve key order. INDEX SKIP SCAN applies to composite indexes where the query predicate does not include the leading column: Oracle enumerates the distinct values of the leading column and performs a sub-range scan for each, effectively skipping through the index. Skip scans are efficient only when the leading column has few distinct values; with high-NDV leading columns, the overhead of many sub-scans exceeds the cost of a full table scan.

Full Table Scan is not always a problem. For queries that return a large fraction of a table's rows, or for very small tables that fit in the buffer cache, a full table scan with multiblock I/O is often faster than index access. The CBO calculates the crossover point: if the expected row count exceeds roughly the clustering_factor of the most selective index divided by the total block count of the table, a full table scan will likely be cheaper. A full table scan on a 50-million-row table with a predicate that selects 0.001% of rows, however, is almost certainly a symptom of a missing index or stale statistics.

## Plan Stability: Baselines, Outlines, and SQL Patches

Oracle provides several mechanisms to stabilize execution plans — to prevent a good plan from being replaced by a worse plan after a statistics refresh, a database upgrade, or an optimizer parameter change. These mechanisms are not substitutes for good statistics and correct schema design, but they are essential operational tools for managing plan regressions in production environments.

SQL Plan Management (SPM), introduced in Oracle 11g, is the most comprehensive plan stability framework. SPM maintains a SQL plan baseline for each SQL statement: a set of one or more accepted plans stored in the SYSAUX tablespace and exposed through DBA_SQL_PLAN_BASELINES. When a new plan is generated for a SQL statement that has an existing baseline, Oracle uses the new plan only if it has been explicitly verified as performing at least as well as the existing baseline plan. Until verified, the new plan is added to the baseline in an unaccepted state, and Oracle continues using the accepted plan. Verification and acceptance can be performed manually using DBMS_SPM.EVOLVE_SQL_PLAN_BASELINE or automated through the SPM Evolve Advisor. The practical result is that after a major statistics refresh or an upgrade to a new Oracle version, SQL statements with baselines will not regress to worse plans until a DBA explicitly reviews and accepts any new plans. The tradeoff is operational overhead: baselines must be managed, and if the application SQL changes, the baseline must be refreshed.

SQL Profiles are a related but distinct mechanism, created by the SQL Tuning Advisor. A SQL Profile is not a fixed plan — it is a set of auxiliary statistics (corrected cardinality estimates for specific column combinations) stored in the data dictionary and applied automatically whenever the profiled SQL is parsed. The result is that the CBO makes better cardinality estimates without being constrained to a specific plan structure. This is generally preferable to a fixed baseline when the optimizer should still be free to adapt to changing data volumes and structures, as long as the root cardinality problem is corrected. SQL Profiles do not prevent the CBO from choosing a new plan structure if future statistics support one that is genuinely better.

SQL Plan Directives, introduced in Oracle 12c, are automatically created when the optimizer repeatedly encounters a cardinality misestimate for a specific set of columns in a specific query block. The directive instructs the optimizer to use dynamic statistics (a recursive SQL query executed at parse time to sample the actual data distribution) whenever that column combination is encountered, producing more accurate cardinality estimates without a full statistics gather. Directives are stored in SYSAUX and can be queried from DBA_SQL_PLAN_DIRECTIVES. They represent Oracle's self-correcting response to systemic statistics failures.

SQL Patches — created via DBMS_SQLDIAG.CREATE_SQL_PATCH — are the emergency intervention tool. A SQL Patch associates a set of optimizer hints with a specific SQL statement, identified by the exact SQL text. When the SQL is parsed, Oracle applies the hints as if they had been written into the SQL text. The patch is applied regardless of schema changes, statistics refreshes, or optimizer parameter changes. This is the tool to reach for when a plan regression occurs in production at 2:00 AM, the application cannot be changed, and the DBA needs to force a specific index or join method immediately without restarting the database or modifying application code.

## Common Plan Regression Causes

Statistics staleness is the most common cause of plan regressions in production Oracle databases. When a table undergoes a bulk load, a partition exchange, or a major delete-and-reinsert cycle, the row count, block count, and column value distributions can change dramatically. If statistics are not refreshed immediately afterward — or if the table falls between automatic statistics gather windows — the CBO will continue using the old cardinality estimates. A table that grew from 100,000 rows to 10,000,000 rows overnight will still have num_rows = 100,000 in DBA_TAB_STATISTICS until statistics are gathered; every plan for queries against that table will be sized for the old row count, with nested loops and index access paths that are catastrophically suboptimal for the new data volume.

Bind variable peeking at non-representative values is the second most common regression cause. When a session first executes a SQL statement with bind variables after a shared pool flush or a statistics invalidation, the plan generated at that moment uses the current bind values. If those values happen to be atypical — a status code that selects very few rows, an employee ID that belongs to a high-volume department — the cached plan will be optimized for that atypical distribution and reused for all subsequent executions regardless of their bind values. The symptom is inconsistent performance: the same SQL is fast most of the time but slow occasionally, with no apparent change to the database. The diagnosis requires comparing the bind values used at parse time (PEEKED_BINDS in the plan output) with the bind values used during the slow execution.

Optimizer parameter changes are a systematic regression cause during environment migrations and database upgrades. The OPTIMIZER_FEATURES_ENABLE parameter controls which optimizer features are available and their relative costs; changing this parameter — implicitly, by upgrading the database — can cause the CBO to choose different plans for every SQL statement in the application. The OPTIMIZER_MODE parameter (CHOOSE, ALL_ROWS, FIRST_ROWS_N) changes the optimization objective from minimizing total resource consumption to minimizing time to first row. The DB_FILE_MULTIBLOCK_READ_COUNT parameter affects the relative cost of full table scans versus index access, directly influencing the CBO's access path decisions. When plans diverge between test and production environments, comparing the optimizer parameters in effect during each parse session is the first diagnostic step.

Histogram staleness causes plan regressions specifically for queries on columns with skewed data distributions. A column like ORDER_STATUS might have 95% of its rows with value 'CLOSED', 4% with value 'PROCESSING', and 1% with value 'OPEN'. Without a histogram, the CBO estimates that any equality predicate on this column selects 1/NDV of rows — say 33% if there are three distinct values. With a histogram, the CBO knows that STATUS = 'CLOSED' selects 95% of rows (probably leading to a full table scan plan) and STATUS = 'OPEN' selects 1% (probably leading to an index access plan). If the histogram was gathered six months ago but the data distribution has since shifted — perhaps due to a business change where 40% of orders are now in an 'AWAITING_PAYMENT' status that barely existed before — the histogram-based estimates will be wrong and the plans chosen accordingly.

Object growth between the time a plan was cached and the time it is executed is a particularly insidious regression cause because it does not require any event — no statistics gather, no schema change, no parameter modification. A query plan cached when a log table had 50,000 rows may still be in use when that table grows to 500,000,000 rows. Because the plan is in cache and statistics have not changed, Oracle has no reason to hard-parse and generate a new plan. The existing plan continues to use index range scans and nested loops sized for 50,000 rows. The fix is to gather fresh statistics on the grown object, which invalidates the cached plan and forces a new hard parse.

## Adaptive Plans (12c+)

Oracle 12c introduced Adaptive Query Optimization as a framework for the optimizer to self-correct during execution. The most visible component is adaptive plans: for join operations where the CBO has uncertainty about which join method will be more efficient, the optimizer generates a composite plan that includes both alternatives and inserts Statistics Collectors at key decision points. A Statistics Collector is a transparent row-counting mechanism that monitors the actual row count passing through a join point. If the actual rows observed match the estimated row count, the default plan is used. If the actual rows diverge significantly from the estimate — a configurable threshold — the plan switches to the alternative at that decision point, without interrupting the execution.

The practical result is that a query planned as a Nested Loop (because the CBO estimated 50 rows from the driving table) can switch to a Hash Join mid-execution if the Statistics Collector observes 50,000 rows passing through. This switch happens within the first execution, not after a separate re-parse cycle. V$SQL shows the SQL's IS_RESOLVED_ADAPTIVE_PLAN column to indicate whether the adaptive plan mechanism was triggered. DBMS_XPLAN output with the 'ADAPTIVE' format option shows the plan tree including both the default and alternative subplans, with the chosen path highlighted.

Adaptive plans significantly improve OLTP performance for queries with bind variable sensitivity — particularly queries that fall in the boundary zone between Nested Loops and Hash Join efficiency. However, for batch processing jobs where execution plan consistency is a requirement — where the same query must have identical performance characteristics across thousands of concurrent executions — the adaptive plan mechanism can introduce variance that is operationally undesirable. A batch job that runs consistently in 30 minutes may occasionally trigger the adaptive switch and run in 15 minutes or 45 minutes depending on which subplan is activated. For these workloads, adaptive plans can be disabled at the session or system level with the OPTIMIZER_ADAPTIVE_PLANS parameter. The OPTIMIZER_ADAPTIVE_STATISTICS parameter separately controls adaptive statistics (dynamic statistics triggered by plan directives), providing finer-grained control over which adaptive mechanisms are active.

## Summary

The Oracle Cost-Based Optimizer makes execution plan decisions based on a cost model that combines I/O cost, CPU cost, and network cost, calibrated against system statistics and driven by object statistics that describe each table's row count, block count, and column value distributions. Every plan decision flows from cardinality estimates — the CBO's prediction of how many rows each plan step will return. Those estimates are only as accurate as the statistics they are based on, and when statistics are stale, skewed, or missing, the resulting cardinality errors cascade through the join tree and corrupt every downstream plan decision.

EXPLAIN PLAN provides a fast, low-cost view of what plan Oracle would generate for a SQL statement under current conditions, but it is fundamentally an estimate. The values in its Rows and Cost columns are the CBO's predictions, not measurements. DBMS_XPLAN.DISPLAY_CURSOR with the ALLSTATS LAST format is the authoritative diagnostic tool: it shows the E-Rows and A-Rows columns side by side for each plan step, making cardinality estimation errors immediately visible. A step where E-Rows = 1 and A-Rows = 1,000,000 is a complete diagnosis: the CBO estimated one row, one million were returned, and every plan decision downstream of that step was wrong.

Join method selection — Nested Loops for small driving sets with selective inner indexes, Hash Join for large unsorted sets, Merge Join for pre-sorted range joins — and index access path selection — UNIQUE SCAN for exact key lookups, RANGE SCAN for selective range predicates, FULL SCAN for ordered coverage queries, FAST FULL SCAN for unordered aggregate coverage, SKIP SCAN for non-leading composite predicates — are deterministic given the cardinality estimates feeding into each decision. Fix the cardinality estimate, and the join method and access path choices usually correct themselves without any hints.

Plan stability mechanisms — SQL Plan Baselines to prevent regression after statistics refreshes and upgrades, SQL Profiles to correct cardinality estimation errors without locking in a specific plan structure, SQL Patches to inject hints into production SQL without modifying application code — are the operational safety net when cardinality cannot be fully corrected through statistics alone. Adaptive plans (12c+) provide an automated self-correction layer for queries where the optimal plan depends on runtime data distribution. Together, these tools form the complete execution plan management toolkit: statistics accuracy prevents problems before they occur, real plan diagnostics identify problems after they occur, and plan stability mechanisms control the plan while root causes are addressed.

The central discipline is this: when a SQL statement is slow, do not reach for hints first. Get the real execution plan with ALLSTATS LAST. Find the step where E-Rows and A-Rows diverge by the largest factor. Trace that divergence back to the statistics failure that caused it. Fix the statistics. The plan will follow.
`,
};

async function main() {
  console.log('Inserting Oracle Explain Plan and Execution Plans post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: { ...post },
  });
  console.log('Inserted: "' + post.title + '"');
}

main().catch(console.error);
