import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'The 5-Year Time Bomb: Resolving Expired WebLogic Demo Certificates and OHS Wallets in EBS',
  slug: 'ebs-weblogic-ohs-demo-certificate-expiry',
  excerpt:
    'Every five years, Oracle E-Business Suite middleware administrators hit the same crisis: WebLogic DemoIdentity and OHS default certificates expire simultaneously. The WebLogic side has a button. The OHS side — a cwallet.sso auto-login wallet with no standard tooling — does not. Here is the full recovery path.',
  category: 'ebs-suite' as const,
  published: true,
  isPremium: false,
  publishedAt: new Date('2026-06-08'),
  youtubeUrl: null,
  content: `Every five years, a quiet crisis hits middleware administrators running Oracle WebLogic Server alongside Oracle E-Business Suite 12.2. You arrive at work to find application deployments failing, admin consoles throwing SSL handshake exceptions, or internal routing breaking down completely.

The culprit is predictable in hindsight: the standard WebLogic DemoIdentity certificate has expired.

While regenerating the default WebLogic keystore through the Enterprise Manager (EM) console is relatively straightforward, a much trickier wrinkle stops most admins cold: the corresponding Oracle HTTP Server (OHS) default certificate — \`ohs1_default\` — has expired at the exact same time.

If you look inside the OHS configuration, you won't find a standard Java KeyStore (\`.jks\`) or a PKCS#12 (\`.p12\`) file. Instead, you are confronted with an Oracle Wallet containing only a \`cwallet.sso\` file.

---

## The Anatomy of the Expiration Intersection

When you install Oracle WebLogic Server 12c (12.2.1.4.0) alongside an integrated Oracle HTTP Server instance — as happens in every EBS 12.2 provisioning — the system automatically provisions temporary self-signed certificates for testing and rapid deployment.

**DemoIdentity.jks** controls SSL for the WebLogic Administration Server and all Managed Server listen ports (oacore_server1, oafm_server1, forms-c4ws_server1, etc.). It is hardcoded to expire exactly five years from the moment the domain was created.

**ohs1_default** lives inside the OHS instance's SSL wallet. Because it was generated at the same time during initial domain provisioning, its five-year expiry aligns perfectly with the WebLogic demo keys.

The confusion arises because their fingerprints and serial numbers do not match — they are entirely separate entities, generated by different tools. You can click a few buttons in Enterprise Manager or run a CertGen command to refresh WebLogic's internal keystore. Enterprise Manager **cannot** automatically regenerate the OHS default wallet certificate. That requires the command line.

---

## Understanding the OHS Auto-Login Wallet

When troubleshooting the OHS side of the failure, you locate the \`SSLWallet\` directive in the OHS \`ssl.conf\`:

\`\`\`apache
# Excerpt from ssl.conf
SSLWallet "\${ORACLE_INSTANCE}/config/fmwconfig/components/OHS/instances/ohs_1/keystores/default"
\`\`\`

Inside that directory, there is a single file: \`cwallet.sso\`.

No \`.p12\`. No \`.jks\`. No private key file. Just one binary blob.

Oracle HTTP Server uses Oracle Wallets to manage SSL. The \`cwallet.sso\` file is an *obfuscated auto-login wallet*. It contains the private key and certificate completely wrapped in an encrypted binary format so that OHS background processes can spin up without prompting an administrator to enter an SSL passphrase at every server boot.

Because it is obfuscated and there is no standalone PKCS#12 export alongside it, standard tools like Java \`keytool\` and \`openssl\` cannot help you. You must use Oracle's dedicated tool: **\`orapki\`**.

---

## Diagnosing the Expiry

Before running any fix, confirm what is actually expired and by how much.

**Check the WebLogic DemoIdentity certificate:**

\`\`\`bash
# From the domain security directory
keytool -list -v -keystore $DOMAIN_HOME/security/DemoIdentity.jks \
        -storepass DemoIdentityKeyStorePassPhrase \
        -alias demoidentity 2>/dev/null | grep -E "Valid|Alias|Serial"
\`\`\`

**Check the OHS wallet certificate:**

\`\`\`bash
# Requires ORACLE_HOME set to the WLS/OHS Oracle home
orapki wallet display \
  -wallet $DOMAIN_HOME/config/fmwconfig/components/OHS/instances/ohs_1/keystores/default
\`\`\`

The \`orapki wallet display\` output shows each certificate's subject DN and validity dates. A certificate whose \`Valid until\` date is in the past is the cause of the OHS SSL handshake failures.

**Confirm from a live endpoint (if OHS is still partially running):**

\`\`\`bash
openssl s_client -connect yourhost.domain.com:4443 -showcerts </dev/null 2>/dev/null \
  | openssl x509 -noout -dates
\`\`\`

---

## Phase 1 — Refreshing the WebLogic Demo Identity

Fix the core middleware container before touching the web tier.

### Step 1: Set domain environment and stop servers

\`\`\`bash
source $DOMAIN_HOME/bin/setDomainEnv.sh
$DOMAIN_HOME/bin/stopWebLogic.sh
# Stop managed servers via wlst or nodemanager if applicable
\`\`\`

### Step 2: Back up existing keystores

\`\`\`bash
cd $DOMAIN_HOME/security
cp DemoIdentity.jks DemoIdentity.jks.bak_$(date +%Y%m%d)
cp DemoTrust.jks    DemoTrust.jks.bak_$(date +%Y%m%d)
\`\`\`

### Step 3: Regenerate the identity certificate

Run the WebLogic Certificate Generator utility to create a fresh 5-year key pair:

\`\`\`bash
java utils.CertGen -key_sz 2048 -cert_value DemoIdentity
\`\`\`

This generates two new files: \`DemoIdentity.pem\` (the certificate) and \`DemoIdentityKey.pem\` (the private key).

### Step 4: Import into the JKS keystore

\`\`\`bash
java utils.ImportPrivateKey \
  -keystore DemoIdentity.jks \
  -storepass DemoIdentityKeyStorePassPhrase \
  -keypass DemoIdentityPassPhrase \
  -alias demoidentity \
  -certfile DemoIdentity.pem \
  -keyfile DemoIdentityKey.pem
\`\`\`

### Step 5: Verify the new certificate

\`\`\`bash
keytool -list -v -keystore DemoIdentity.jks \
        -storepass DemoIdentityKeyStorePassPhrase \
        -alias demoidentity | grep -E "Valid|Alias"
\`\`\`

The \`Valid from\` date should be today and \`Valid until\` should be five years from now.

---

## Phase 2 — Rebuilding the OHS Auto-Login Wallet

This is the part that Enterprise Manager cannot do for you. All steps run as the Oracle software owner via the OS command line.

\`\`\`bash
# 1. Navigate to the OHS keystore directory
cd $DOMAIN_HOME/config/fmwconfig/components/OHS/instances/ohs_1/keystores/default

# 2. Back up the old auto-login wallet
mv cwallet.sso cwallet.sso.bak_$(date +%Y%m%d)

# 3. Create a fresh, empty Oracle wallet with auto-login enabled
orapki wallet create -wallet . -pwd YourSecureWalletPassword123 -auto_login

# 4. Generate a new self-signed certificate directly into the wallet
#    -validity 1825 = 5 years (365 * 5)
orapki wallet add \
  -wallet . \
  -pwd YourSecureWalletPassword123 \
  -dn "CN=yourhost.domain.com,O=Demo,C=US" \
  -keysize 2048 \
  -validity 1825 \
  -self_signed

# 5. Verify the wallet contents
orapki wallet display -wallet .
\`\`\`

The \`-validity 1825\` flag signs the certificate for exactly 1,825 days, aligning the OHS expiry with the freshly regenerated WebLogic layer.

After this block, the directory will contain both \`cwallet.sso\` (the new auto-login wallet) and \`ewallet.p12\` (an encrypted PKCS#12 export). OHS reads only \`cwallet.sso\` at startup.

---

## Restart and Validate

Restart the Node Manager first, then the Admin Server, then OHS:

\`\`\`bash
# Restart Node Manager
$DOMAIN_HOME/bin/startNodeManager.sh &

# Restart Admin Server
$DOMAIN_HOME/bin/startWebLogic.sh &

# Restart OHS via opmnctl
$ORACLE_INSTANCE/bin/opmnctl startall
\`\`\`

Confirm OHS is serving SSL on the correct port:

\`\`\`bash
openssl s_client -connect yourhost.domain.com:443 -showcerts </dev/null 2>/dev/null \
  | openssl x509 -noout -subject -dates
\`\`\`

---

## Why Demo Certificates Are a Structural Risk

While this fix restores operations, relying on demo assets has a known vulnerability: the default WebLogic demo keystores use **publicly documented passwords** (\`DemoIdentityKeyStorePassPhrase\`, \`DemoIdentityPassPhrase\`, \`DemoTrustKeyStorePassPhrase\`). These passwords are embedded in WebLogic's public documentation and source binaries.

Any attacker with network access to your WebLogic listen ports and knowledge of these default passwords can potentially impersonate the server or decrypt intercepted traffic.

Treat this regeneration as a bridge fix. The second phase is migrating both the WebLogic JKS keystores and the OHS Oracle Wallet to certificates signed by your enterprise Certificate Authority. That eliminates the five-year time bomb permanently and removes the default-password exposure.

The companion runbook for this post covers the complete step-by-step procedure with expiry monitoring scripts.`,
};

async function main() {
  console.log('Inserting EBS WebLogic/OHS demo certificate expiry blog post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: {
      title: post.title,
      excerpt: post.excerpt,
      content: post.content,
      category: post.category,
      published: post.published,
      isPremium: post.isPremium,
      publishedAt: post.publishedAt,
      youtubeUrl: post.youtubeUrl,
    },
  });
  console.log('Inserted:', JSON.stringify(post.title));
}

main().catch(console.error);
