import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';

const slug = 'ebs-code-tree-s-cp-twotask-context-file';

const content = `
Two questions come up repeatedly when DBAs take over an Oracle EBS environment: where does everything live, and what controls how the application tier connects to the database? The answers to both are rooted in the Applications code tree and the Context File that drives its configuration.

This post covers the EBS file system structure across 11i, R12.1.3, and R12.2.x, then goes deep on \`s_cp_twotask\` — the parameter in \`\$CONTEXT_FILE\` that controls how the Concurrent Processing tier connects to the database, why it is separate from the general application TWO_TASK, and how to inspect and change it correctly on both the application tier and the database tier.

---

## The EBS Code Tree

The "code tree" refers to the complete file system layout for an Oracle EBS installation — the directory hierarchy that holds application PL/SQL libraries, Forms, Reports, Java, HTML, configuration files, and the context file that ties everything together. Its structure evolved significantly between 11i and R12.2.

### EBS 11i Code Tree

In 11i, the entire application file system lives under a single \`APPL_TOP\` directory. Each Oracle product has its own subdirectory named after the product short name and version number:

\`\`\`
\$APPL_TOP/                          ← root of all application files
  admin/
    \${CONTEXT_NAME}.xml             ← CONTEXT_FILE (e.g., EBSPRD_appnode01.xml)
    adconfig.txt
    out/                             ← AutoConfig output logs
    log/                             ← AutoConfig run logs
  fnd/11.5.0/                        ← \$FND_TOP (Foundation)
    bin/
    forms/US/
    sql/
    patch/115/sql/
  ar/11.5.0/                         ← \$AR_TOP (Receivables)
  gl/11.5.0/                         ← \$GL_TOP (General Ledger)
  ap/11.5.0/                         ← \$AP_TOP (Payables)
  po/11.5.0/                         ← \$PO_TOP (Purchasing)
  inv/11.5.0/                        ← \$INV_TOP (Inventory)
  au/11.5.0/                         ← \$AU_TOP (shared utilities, CUSTOM.pll)

\$OA_HTML/                           ← Oracle HTML directory (self-service pages)
\$JAVA_TOP/                          ← Java class files
\$IAS_ORACLE_HOME/                   ← Oracle HTTP Server / Apache JServ (iAS)
  Apache/
    Jserv/
      logs/                          ← FormsGroup*.stdout lives here
\`\`\`

The Context File in 11i is at:
\`\`\`
\$APPL_TOP/admin/\${CONTEXT_NAME}.xml
\`\`\`

where \`CONTEXT_NAME\` follows the pattern \`\${TWO_TASK}_\${HOSTNAME}\` — for example, \`EBSPRD_appnode01\`.

The environment is sourced from:
\`\`\`bash
source \$APPL_TOP/APPSORA.env
# or, when using AutoConfig-managed envs:
source /u01/applmgr/EBSPRD/appsutil/env/EBSPRD_appnode01.env
\`\`\`

### EBS R12.1.3 Code Tree

R12.1 introduced a cleaner separation between the application file system (\`apps_st\`) and common shared components (\`comn\`). An instance-level directory (\`inst\`) holds configuration and log files separately from the application code, making patching cleaner and supporting a more standardized layout.

\`\`\`
/u01/applmgr/EBSPRD/
  apps/
    apps_st/
      appl/                          ← \$APPL_TOP
        admin/
          \${CONTEXT_NAME}.xml       ← CONTEXT_FILE
        fnd/12.0.0/                  ← \$FND_TOP
        ar/12.0.0/
        gl/12.0.0/
        au/12.0.0/                   ← \$AU_TOP
    comn/
      java/                          ← \$JAVA_TOP
      html/                          ← \$OA_HTML
      util/                          ← \$COMMON_TOP/util
  inst/
    apps/
      \${CONTEXT_NAME}/
        appl/
          admin/                     ← instance-level admin logs
        logs/
          appl/
            conc/                    ← Concurrent Manager log/out files
            apache/                  ← OHS/Apache logs
        ora/
          10.1.2/                    ← 10.1.2 ORACLE_HOME (Forms/Reports runtime)
          10.1.3/                    ← 10.1.3 ORACLE_HOME (OC4J/Java runtime)
\`\`\`

The environment is sourced from:
\`\`\`bash
source /u01/applmgr/EBSPRD/apps/apps_st/appl/EBSprd_appnode01.env
\`\`\`

A key R12.1 addition: the \`inst\` tree separates run-time artifacts (logs, configuration, temp files) from the application code tree. Patching touches \`apps_st\`; \`inst\` is regenerated by AutoConfig.

### EBS R12.2.x Code Tree — Dual File System

R12.2 is architecturally different from 11i and R12.1. The Online Patching (\`adop\`) framework requires two complete copies of the application file system — \`fs1\` and \`fs2\` — so that patches can be applied to the idle copy while users continue working against the active copy. After cutover, the roles swap.

\`\`\`
/u01/applmgr/EBSPRD/
  fs1/                               ← File system 1 (may be run or patch edition)
    EBSapps/
      appl/                          ← \$APPL_TOP when fs1 is run edition
        admin/
          \${CONTEXT_NAME}.xml       ← Edition-specific CONTEXT_FILE
        fnd/12.0.0/
        ar/12.0.0/
        au/12.0.0/
      comn/
        java/                        ← \$JAVA_TOP
        html/                        ← \$OA_HTML
  fs2/                               ← File system 2 (the other edition)
    EBSapps/
      appl/                          ← \$APPL_TOP when fs2 is run edition
        admin/
          \${CONTEXT_NAME}.xml       ← Separate edition context file
      comn/
  fs_ne/                             ← Non-editioned file system (shared)
    EBSapps/
      appl/
        admin/                       ← Shared admin artifacts
      comn/
  inst/                              ← Instance files (shared across editions)
    apps/
      \${CONTEXT_NAME}/
        logs/
          appl/
            conc/                    ← Concurrent Manager logs
            apache/                  ← OHS logs
  EBSapps.env                        ← Edition selector script
\`\`\`

The edition selector is the key operational change:
\`\`\`bash
source /u01/applmgr/EBSPRD/EBSapps.env run    # sources the run edition
source /u01/applmgr/EBSPRD/EBSapps.env patch  # sources the patch edition
\`\`\`

In R12.2, each edition has its own \`CONTEXT_FILE\`. When you source \`run\`, \`\$CONTEXT_FILE\` points to the run edition's context XML. When you source \`patch\`, it points to the patch edition's. This is important for \`s_cp_twotask\` — if you need to inspect or change the parameter, you must source the correct edition and edit the correct context file.

The non-editioned file system (\`fs_ne\`) holds components that are shared between editions and are not replaced during patching — primarily certain configuration and log infrastructure. It is not a patching target.

---

## The Applications Context File (\$CONTEXT_FILE)

The Context File is the single source of truth for all Oracle EBS configuration parameters. It is an XML file containing hundreds of named parameters, each represented as an XML element with the naming convention \`s_<parameter_name>\`. AutoConfig reads this file and generates every downstream configuration file in the EBS installation: \`tnsnames.ora\`, \`listener.ora\`, \`httpd.conf\`, \`appsweb.cfg\`, \`dbc\` files, concurrent manager startup scripts, and more.

The file is located at:

| Version | Location |
|---------|---------|
| 11i | \`\$APPL_TOP/admin/\${TWO_TASK}_\${HOSTNAME}.xml\` |
| R12.1.3 | \`\$APPL_TOP/admin/\${TWO_TASK}_\${HOSTNAME}.xml\` |
| R12.2.x | \`\${APPL_TOP}/admin/\${CONTEXT_NAME}.xml\` (one per edition) |

The environment variable \`\$CONTEXT_FILE\` is set when the EBS environment is sourced and always points to the active edition's context XML.

\`\`\`bash
echo \$CONTEXT_FILE
# /u01/applmgr/EBSPRD/apps/apps_st/appl/admin/EBSPRD_appnode01.xml
\`\`\`

---

## What Is s_cp_twotask?

\`s_cp_twotask\` is the Applications Context File parameter that defines the Oracle Net service name used exclusively by **Concurrent Processing (CP)** — the EBS Concurrent Manager framework — when it connects to the database.

In the context file it appears as:

\`\`\`xml
<s_cp_twotask oa_var="s_cp_twotask">EBSPRD</s_cp_twotask>
\`\`\`

The value (\`EBSPRD\` in this example) is a TNS service name that must resolve via \`tnsnames.ora\` on the application tier.

### Why s_cp_twotask is separate from s_twotask

EBS maintains two distinct database connection parameters at the context file level:

| Parameter | Controls | Used by |
|-----------|---------|---------|
| \`s_twotask\` | General application TWO_TASK | Forms sessions, self-service OA Framework, Oracle HTTP Server DADs |
| \`s_cp_twotask\` | Concurrent Processing TWO_TASK | Internal Concurrent Manager (ICM), Standard Managers, all CP worker processes |

The separation exists because concurrent processing has different connection requirements from interactive application sessions:

- **Dedicated server mode**: CP jobs typically require dedicated server processes rather than shared server, because batch operations hold database cursors for long durations. A separate service can enforce dedicated mode for CP connections.
- **RAC node affinity**: In RAC environments, you may want CP jobs pinned to specific nodes (dedicated to batch workloads) while OLTP Forms sessions use a different service that distributes across all RAC nodes.
- **Resource management**: A separate CP service enables Oracle Database Resource Manager to apply different plans to CP connections vs. interactive connections, preventing runaway batch jobs from starving the OLTP workload.
- **Active Data Guard offload (R12.2)**: Some read-intensive CP reports can be routed to an Active Data Guard standby by pointing \`s_cp_twotask\` at a service registered on the standby.

### How AutoConfig propagates s_cp_twotask

When AutoConfig runs on the application tier, it reads \`s_cp_twotask\` from the context file and writes the value into the Concurrent Manager environment startup scripts — specifically into the scripts that set \`CP_TWO_TASK\` before the ICM launches. The ICM and every concurrent process it spawns then use this environment variable for their database connections.

\`\`\`bash
# Generated by AutoConfig — do not edit manually
export CP_TWO_TASK=EBSPRD
\`\`\`

This generated script is sourced when the Concurrent Manager service starts. Changing \`s_cp_twotask\` in the context file has no effect until AutoConfig is re-run and the Concurrent Manager is restarted.

---

## Viewing s_cp_twotask

### On the application tier (all versions)

\`\`\`bash
grep -i "cp_twotask" \$CONTEXT_FILE
\`\`\`

Output:
\`\`\`xml
<s_cp_twotask oa_var="s_cp_twotask">EBSPRD</s_cp_twotask>
\`\`\`

To see the currently active value in the running environment (what the ICM is actually using):
\`\`\`bash
echo \$CP_TWO_TASK
\`\`\`

If \`CP_TWO_TASK\` is empty or differs from \`s_cp_twotask\` in the context file, AutoConfig has not been run since the last context file change, or the environment was not sourced from the generated scripts.

### Comparing s_twotask and s_cp_twotask

\`\`\`bash
echo "TWO_TASK (general)  : \$(grep -i '<s_twotask ' \$CONTEXT_FILE | sed 's/.*>\\(.*\\)<.*/\\1/')"
echo "CP_TWO_TASK (batch) : \$(grep -i 's_cp_twotask' \$CONTEXT_FILE | sed 's/.*>\\(.*\\)<.*/\\1/')"
echo ""
echo "Active TWO_TASK    : \$TWO_TASK"
echo "Active CP_TWO_TASK : \$CP_TWO_TASK"
\`\`\`

If both parameters hold the same value, CP and interactive sessions share a single service. This is the default in most single-instance environments. The values diverge intentionally in RAC environments with workload separation or when CP is offloaded to a standby.

### In OAM (Oracle Applications Manager)

For a GUI view: navigate to **Site Map > AutoConfig > Edit Parameters** and search for \`cp_twotask\`. OAM provides a form-based interface that writes to the context file on save — useful when you want to avoid hand-editing XML.

---

## Using s_cp_twotask on the Application Tier

### Verify the current CP connection

After the Concurrent Manager is running, confirm what service the ICM is using:

\`\`\`sql
-- Run in SQL*Plus as APPS
SELECT s.sid,
       s.serial#,
       s.username,
       s.program,
       s.service_name,
       s.status,
       s.last_call_et AS idle_sec
FROM   v\$session s
WHERE  s.program LIKE '%FNDLIBR%'
   OR  s.program LIKE '%FNDSM%'
   OR  s.program LIKE '%ICM%'
ORDER BY s.program;
\`\`\`

The \`SERVICE_NAME\` column shows the Oracle service each CP process is connected through. This should match the TNS service name that \`s_cp_twotask\` resolves to.

### Changing s_cp_twotask

**Step 1 — Edit the context file**

Never hand-edit the context file while the environment is live. Use OAM or a controlled edit:

\`\`\`bash
# Back up before editing
cp \$CONTEXT_FILE \${CONTEXT_FILE}.\$(date +%Y%m%d_%H%M%S).bak

# Edit — change the value between the XML tags
vi \$CONTEXT_FILE
# Find: <s_cp_twotask oa_var="s_cp_twotask">OLD_SERVICE</s_cp_twotask>
# Set:  <s_cp_twotask oa_var="s_cp_twotask">NEW_SERVICE</s_cp_twotask>
\`\`\`

In R12.2, the context file is edition-specific. Edit the run edition context file (source \`run\` before editing):

\`\`\`bash
source /u01/applmgr/EBSPRD/EBSapps.env run
cp \$CONTEXT_FILE \${CONTEXT_FILE}.\$(date +%Y%m%d_%H%M%S).bak
vi \$CONTEXT_FILE
\`\`\`

**Step 2 — Verify the new TNS service resolves**

Before running AutoConfig, confirm the new service name resolves correctly:

\`\`\`bash
tnsping NEW_SERVICE
\`\`\`

If \`tnsping\` fails, the change will cause CP connections to fail after AutoConfig. Add or correct the entry in \`tnsnames.ora\` first.

**Step 3 — Run AutoConfig on the application tier**

\`\`\`bash
cd \$AD_TOP/bin
./adautocfg.sh
\`\`\`

AutoConfig will regenerate the CP startup scripts with the new \`CP_TWO_TASK\` value.

**Step 4 — Restart the Concurrent Manager**

The new \`CP_TWO_TASK\` does not take effect until the ICM is restarted:

\`\`\`bash
# Stop
\$FND_TOP/bin/adcmctl.sh stop apps/<apps_password>

# Wait for all managers to shut down
\$FND_TOP/bin/adcmctl.sh status apps/<apps_password>

# Start
\$FND_TOP/bin/adcmctl.sh start apps/<apps_password>
\`\`\`

**Step 5 — Verify the new connection**

Re-run the \`v\$session\` query above and confirm \`SERVICE_NAME\` shows the new service name for all ICM and FNDLIBR processes.

---

## Using s_cp_twotask on the Database Tier

The database tier does not have a \`CONTEXT_FILE\` of its own for application-level parameters — the \`s_cp_twotask\` value is an app tier configuration item. However, the database must be prepared to accept connections on the service that \`s_cp_twotask\` resolves to.

### Verify the target service exists in the database

\`\`\`sql
SELECT name,
       network_name,
       creation_date,
       enabled
FROM   v\$active_services
ORDER BY name;
\`\`\`

The service named in \`s_cp_twotask\` must appear in this view with \`enabled = YES\`. If it is absent, CP processes will receive ORA-12514 or ORA-12541 when attempting to connect.

### Create the CP service (if needed)

For a single-instance database:

\`\`\`sql
-- Create the service
EXEC DBMS_SERVICE.CREATE_SERVICE(
  service_name   => 'EBSPRD_CP',
  network_name   => 'EBSPRD_CP'
);

-- Start it
EXEC DBMS_SERVICE.START_SERVICE('EBSPRD_CP');
\`\`\`

For a RAC database, use \`srvctl\` to create the service and assign it to specific preferred instances:

\`\`\`bash
# Create service preferred on rac1, available on rac2
srvctl add service \\
  -db EBSPRD \\
  -service EBSPRD_CP \\
  -preferred EBSPRD1 \\
  -available EBSPRD2 \\
  -role PRIMARY

# Start the service
srvctl start service -db EBSPRD -service EBSPRD_CP

# Verify
srvctl status service -db EBSPRD -service EBSPRD_CP
\`\`\`

### Add the service to tnsnames.ora on the app tier

The new service must resolve on the application tier nodes. Add an entry to \`\$TNS_ADMIN/tnsnames.ora\` before running AutoConfig, or let AutoConfig generate it from the context file if the TNS template includes the CP service.

\`\`\`
EBSPRD_CP =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = dbhost.example.com)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = EBSPRD_CP)
    )
  )
\`\`\`

The \`SERVER = DEDICATED\` clause enforces dedicated server connections for CP, which is recommended for long-running batch jobs.

### RAC-specific: pin CP to dedicated nodes

In a RAC environment with workload separation, the typical pattern is:

| Service | Preferred nodes | Used for |
|---------|----------------|---------|
| \`EBSPRD\` | All RAC nodes | Interactive sessions (Forms, self-service) |
| \`EBSPRD_CP\` | RAC node 2 only | Concurrent Processing |

Setting \`s_cp_twotask=EBSPRD_CP\` and pointing that service to a dedicated RAC instance prevents CP batch load from competing with OLTP sessions on the primary nodes.

### Verify CP connections are using the correct service after restart

\`\`\`sql
SELECT s.service_name,
       COUNT(*) AS session_count,
       SUM(CASE WHEN s.status = 'ACTIVE' THEN 1 ELSE 0 END) AS active
FROM   v\$session s
WHERE  s.username = 'APPS'
  AND  (s.program LIKE '%FNDLIBR%' OR s.program LIKE '%FNDSM%')
GROUP BY s.service_name
ORDER BY session_count DESC;
\`\`\`

All CP sessions should be grouped under the service name set in \`s_cp_twotask\`.

---

## Version Differences Summary

| Aspect | EBS 11i | R12.1.3 | R12.2.x |
|--------|---------|---------|---------|
| APPL_TOP layout | Single flat tree under \`APPL_TOP\` | Split \`apps_st/appl\` + \`comn\` + \`inst\` | Dual \`fs1\`/\`fs2\` + \`fs_ne\` + \`inst\` |
| CONTEXT_FILE location | \`\$APPL_TOP/admin/\${SID}_\${HOST}.xml\` | \`\$APPL_TOP/admin/\${SID}_\${HOST}.xml\` | Edition-specific: \`\$APPL_TOP/admin/\${CONTEXT_NAME}.xml\` |
| Environment source | \`appsutil/env/\${SID}_\${HOST}.env\` | \`EBSprd_\${HOST}.env\` | \`EBSapps.env run\` or \`EBSapps.env patch\` |
| Patching tool | adpatch | adpatch | adop (Online Patching) |
| s_cp_twotask in context file | Same XML format | Same XML format | Same XML format; edit run edition after sourcing \`run\` |
| AutoConfig command | \`adautocfg.sh\` | \`adautocfg.sh\` | \`adautocfg.sh\` (run against run edition) |
| CM restart after change | Required | Required | Required; use standard \`adcmctl.sh\` |

---

## Summary

The EBS code tree evolved from a single flat \`APPL_TOP\` in 11i to a separated instance/app layout in R12.1, to a fully dual-edition file system in R12.2. Across all three versions, the Context File at \`\$CONTEXT_FILE\` is the authoritative source of configuration parameters, generated into downstream files by AutoConfig.

\`s_cp_twotask\` is the context file parameter that separates the Concurrent Processing database connection from the general application TWO_TASK. It allows CP to use a dedicated Oracle Net service — one configured for dedicated server mode, pinned to specific RAC nodes, or pointed at an Active Data Guard standby for read-only workloads. Changing it requires editing the context file (with a backup), verifying the new TNS service resolves and exists in the database, running AutoConfig on the application tier, and restarting the Concurrent Manager. The change has no database-side AutoConfig component — the DBA must ensure the service is registered and available on the database before the app tier is reconfigured to use it.
`.trim();

async function main() {
  await db.insert(posts).values({
    title: 'EBS Code Tree and s_cp_twotask: File System Layout in 11i, R12.1.3, and R12.2.x and How the Concurrent Processing TWO_TASK Works',
    slug,
    excerpt: 'The EBS code tree evolved from a single APPL_TOP in 11i through a separated instance layout in R12.1.3 to a dual run/patch edition file system in R12.2.x. This post maps the directory structure across all three versions, explains the Applications Context File ($CONTEXT_FILE) and how it drives AutoConfig, and goes deep on s_cp_twotask — the parameter that gives Concurrent Processing its own database service name separate from the general application TWO_TASK, how to inspect and change it on both tiers, and why the separation matters in RAC and Data Guard environments.',
    content,
    category: 'ebs-suite',
    isPremium: false,
    published: true,
    publishedAt: new Date(),
  });
  console.log('Inserted:', slug);
}

main().catch(console.error);
