import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';

const slug = 'ebs-custom-jdbc-tns-descriptors-autoconfig-survival';

const content = `
As an Apps DBA, few things are more frustrating than executing an AutoConfig cycle to apply a routine change — only to find that your custom network optimisations have vanished. You added \`(ENABLE=BROKEN)\` to handle dead connection detection across a stateful firewall, confirmed it working in production, and now it is gone. The form sessions are hanging again on idle disconnect instead of timing out cleanly.

Directly editing \`\$CONTEXT_FILE\` or \`tnsnames.ora\` is a recipe for exactly this problem. AutoConfig regenerates both from templates, and any in-place edit to the generated output is silently overwritten on the next run. Because Oracle EBS handles configuration generation through fundamentally different architectures depending on the release generation, the method to make these changes permanent varies significantly by version.

This post is the definitive playbook for permanently injecting custom connection string parameters across EBS 11i, 12.1.3, and 12.2.x — ensuring your changes survive every AutoConfig cycle.

---

## Why \`(ENABLE=BROKEN)\` and When You Need It

Before getting into the version-specific mechanics, it is worth understanding the pattern that most commonly triggers this requirement.

\`(ENABLE=BROKEN)\` in an Oracle Net connect descriptor activates TCP keepalive probing at the Oracle Net layer. When enabled, Oracle Net sends periodic dead-connection-detection probes over the SQL*Net connection. If the remote end does not respond, the connection is cleanly terminated on the Oracle side.

This parameter is critical in environments where:

- A stateful firewall or load balancer sits between the application tier and the database tier and enforces idle TCP session timeouts
- EBS Forms sessions or long-running concurrent requests hold database connections open for periods that exceed the firewall's idle timeout window
- The firewall silently drops the TCP session without sending a RST, leaving the Oracle server holding an open cursor against a dead client — resulting in ORA-03113 or ORA-01001 on the application side

The correct placement is immediately after the opening \`(DESCRIPTION=\` tag:

\`\`\`
(DESCRIPTION=
  (ENABLE=BROKEN)
  (ADDRESS_LIST=
    (ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521))
  )
  (CONNECT_DATA=
    (SERVICE_NAME=EBSPROD)
  )
)
\`\`\`

The problem is that both \`tnsnames.ora\` and the JDBC connect string embedded in the EBS application tier are generated by AutoConfig from templates and context file values. Editing the generated files directly is effective until the next AutoConfig run — which could be triggered by a patch, a hostname change, or even a routine maintenance cycle.

---

## EBS 11i: Legacy CGI Framework

In the 11i era, AutoConfig parses templates from \`\$FND_TOP/admin/template\` and generates active configuration files. The generated files are overwritten on every run. The mechanism for protection is the \`custom\` subdirectory, which AutoConfig reads and merges after processing the base templates.

### Application tier: appsweb.cfg

\`\`\`bash
cd \$FND_TOP/admin/template
mkdir -p custom
cp appsweb.cfg custom/appsweb.cfg
\`\`\`

Open \`custom/appsweb.cfg\` and locate the \`connectString\` parameter. Inject your \`(ENABLE=BROKEN)\` parameter inside the connect descriptor value:

\`\`\`
connectString=(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521)))(CONNECT_DATA=(SID=EBSPROD)))
\`\`\`

### Database tier: tnsnames.ora

To protect the database-tier \`tnsnames.ora\`, copy the relevant template from \`\$ORACLE_HOME/appsutil/template/\`:

\`\`\`bash
cd \$ORACLE_HOME/appsutil/template
mkdir -p custom
cp adxdbctx.tmp custom/adxdbctx.tmp
\`\`\`

Edit \`custom/adxdbctx.tmp\`. Locate the target database connect descriptor block and insert \`(ENABLE=BROKEN)\` immediately after \`(DESCRIPTION=\`:

\`\`\`
(DESCRIPTION=
  (ENABLE=BROKEN)
  (ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521))
  (CONNECT_DATA=(SID=EBSPROD))
)
\`\`\`

Run AutoConfig on the application tier followed by the database tier:

\`\`\`bash
# Application tier
\$ADMIN_SCRIPTS_HOME/adautoconfig.sh

# Database tier
\$ORACLE_HOME/appsutil/scripts/\$CONTEXT_NAME/adautoconfig.sh
\`\`\`

---

## EBS 12.1.3: The ATG Era

With Release 12.1.3, the architecture shifted toward XML context file processing. The \`\$CONTEXT_FILE\` became the authoritative source for JDBC connection strings, while the \`custom\` directory template mechanism was retained for standard TNS files.

The critical distinction: the JDBC string embedded in the context file is what EBS middle-tier components (forms, OC4J, concurrent managers) use to connect to the database. It is separate from the OS-level \`tnsnames.ora\`, and it lives inside the XML context file under the parameter tag \`s_apps_jdbc_connect_descriptor\`.

### JDBC connect descriptor in \$CONTEXT_FILE

Open your application tier \`\$CONTEXT_FILE\` (an XML file, typically at \`\$APPL_TOP/admin/\$TWO_TASK_\$HOSTNAME.xml\`) and search for \`s_apps_jdbc_connect_descriptor\`:

\`\`\`xml
<s_apps_jdbc_connect_descriptor oa_var="s_apps_jdbc_connect_descriptor">
(DESCRIPTION=
  (ENABLE=BROKEN)
  (ADDRESS_LIST=
    (ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521))
  )
  (CONNECT_DATA=(SERVICE_NAME=EBSPROD))
)
</s_apps_jdbc_connect_descriptor>
\`\`\`

Edit the value in place, adding \`(ENABLE=BROKEN)\` as the first element after \`(DESCRIPTION=\`. Save the file. **This change survives AutoConfig in 12.1.3** because the context file itself is the source of record — AutoConfig reads the context file and propagates its values into the generated output, rather than regenerating the context file from scratch.

### TNS templates: aftnsnm.tmp

For the OS-level \`tnsnames.ora\` generated on the application tier:

\`\`\`bash
cd \$FND_TOP/admin/template
mkdir -p custom
cp aftnsnm.tmp custom/aftnsnm.tmp
\`\`\`

Edit \`custom/aftnsnm.tmp\`. Locate the \`(DESCRIPTION=\` block for your target connect descriptor and insert \`(ENABLE=BROKEN)\` immediately below it:

\`\`\`
(DESCRIPTION=
  (ENABLE=BROKEN)
  ...
\`\`\`

Run AutoConfig to propagate both changes:

\`\`\`bash
\$ADMIN_SCRIPTS_HOME/adautoconfig.sh
\`\`\`

---

## EBS 12.2.x: The Dual Filesystem and WebLogic Era

Release 12.2 introduced a paradigm shift: the Online Patching dual filesystem (\`fs1\`/\`fs2\`), Oracle WebLogic Server replacing OC4J, and a stricter AutoConfig synchronisation model that actively reconciles the context file values across both filesystem editions. In this environment:

- Manually editing the XML context file by hand is fragile — AutoConfig synchronisation between the run and patch editions can overwrite hand-edited values
- The \`custom\` template directory mechanism still works for TNS file generation
- The authoritative tool for modifying context file parameters without breaking edition synchronisation is \`txkSetContextParam.pl\`

### Step 1 — Update the JDBC descriptor via txkSetContextParam.pl

Source your active RUN-edition environment first, then use the official Oracle utility:

\`\`\`bash
source /u01/oracle/EBS/EBSapps.env run

perl \$FND_TOP/bin/txkSetContextParam.pl \\
  -contextfile=\$CONTEXT_FILE \\
  -paramname=s_apps_jdbc_connect_descriptor \\
  -paramvalue="(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=EBSPROD)))"
\`\`\`

**Before running this command**, capture the existing value from the context file so you can construct the new value correctly:

\`\`\`bash
grep -A3 's_apps_jdbc_connect_descriptor' \$CONTEXT_FILE | head -6
\`\`\`

Take the existing descriptor verbatim, add \`(ENABLE=BROKEN)\` immediately after the opening \`(DESCRIPTION=\`, and pass that complete string as \`-paramvalue\`. Do not reconstruct the descriptor from memory — clusters with multiple \`ADDRESS\` entries, failover parameters, and load-balancing flags are easy to lose in transcription.

### Step 2 — Isolate the TNS template

\`\`\`bash
source /u01/oracle/EBS/EBSapps.env run

cd \$FND_TOP/admin/template
mkdir -p custom
cp aftnsnm.tmp custom/aftnsnm.tmp
\`\`\`

Edit \`custom/aftnsnm.tmp\` and inject \`(ENABLE=BROKEN)\` into the target descriptor block:

\`\`\`
(DESCRIPTION=
  (ENABLE=BROKEN)
  (ADDRESS_LIST=
    (ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521))
  )
  (CONNECT_DATA=(SERVICE_NAME=EBSPROD))
)
\`\`\`

### Step 3 — Run AutoConfig on the RUN edition

\`\`\`bash
\$ADMIN_SCRIPTS_HOME/adautoconfig.sh
\`\`\`

### Step 4 — Validate the generated files

\`\`\`bash
# Confirm ENABLE=BROKEN is present in the live tnsnames.ora
grep -i 'ENABLE=BROKEN' \$TNS_ADMIN/tnsnames.ora

# Confirm it is present in the context file JDBC parameter
grep -A5 's_apps_jdbc_connect_descriptor' \$CONTEXT_FILE | grep -i 'ENABLE=BROKEN'

# In 12.2 — also validate the PATCH edition context file
source /u01/oracle/EBS/EBSapps.env patch
grep -i 'ENABLE=BROKEN' \$TNS_ADMIN/tnsnames.ora
grep -A5 's_apps_jdbc_connect_descriptor' \$CONTEXT_FILE | grep -i 'ENABLE=BROKEN'
\`\`\`

If the PATCH edition does not yet contain the change, run AutoConfig on the patch edition as well — or re-run \`txkSetContextParam.pl\` targeting the PATCH edition context file, then run AutoConfig on that edition.

---

## Edition Synchronisation in 12.2 (the Detail That Catches DBAs Out)

In 12.2, the context file exists in both the run edition and the patch edition. When \`adop phase=prepare\` runs fs_clone, it copies the run edition's context file to the patch edition. If you update the run context file after fs_clone has already run, the patch edition will not have your change — and after cutover, the old value re-appears.

The correct sequence for making a TNS/JDBC change during an active adop cycle:

\`\`\`
1. Make the change on the RUN edition (txkSetContextParam.pl + AutoConfig)
2. Verify the generated files on the RUN edition
3. Run adop phase=fs_clone  ← propagates the updated context file to PATCH edition
4. Run AutoConfig on the PATCH edition
5. Proceed with adop phase=apply
\`\`\`

If you make the change after \`adop phase=apply\` has started, run \`txkSetContextParam.pl\` targeting the PATCH edition context file directly:

\`\`\`bash
source /u01/oracle/EBS/EBSapps.env patch

perl \$FND_TOP/bin/txkSetContextParam.pl \\
  -contextfile=\$CONTEXT_FILE \\
  -paramname=s_apps_jdbc_connect_descriptor \\
  -paramvalue="(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ebsdb01.corp.example.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=EBSPROD)))"

\$ADMIN_SCRIPTS_HOME/adautoconfig.sh
\`\`\`

---

## Version Comparison

| Mechanism | 11i | 12.1.3 | 12.2.x |
|---|---|---|---|
| JDBC descriptor location | appsweb.cfg template | \`s_apps_jdbc_connect_descriptor\` in \`\$CONTEXT_FILE\` | \`s_apps_jdbc_connect_descriptor\` in \`\$CONTEXT_FILE\` (both editions) |
| How to protect JDBC change | \`custom/appsweb.cfg\` | Edit \`\$CONTEXT_FILE\` directly | \`txkSetContextParam.pl\` — do not hand-edit |
| TNS template | \`\$ORACLE_HOME/appsutil/template/custom/adxdbctx.tmp\` | \`\$FND_TOP/admin/template/custom/aftnsnm.tmp\` | \`\$FND_TOP/admin/template/custom/aftnsnm.tmp\` (both editions) |
| AutoConfig command | \`adautoconfig.sh\` (app + DB tier) | \`adautoconfig.sh\` (app tier) | \`adautoconfig.sh\` (run edition, then patch edition) |
| Dual filesystem concern | No | No | Yes — must apply to both editions |

---

## Summary

AutoConfig regenerates TNS and JDBC configuration files from templates and context file values on every run. Any direct edit to the generated output — \`tnsnames.ora\`, \`appsweb.cfg\`, or the JDBC connection string file — will be silently overwritten. The fix in all three EBS generations is to modify the source, not the output: custom template directories for TNS files, and either the context file directly (11i, 12.1.3) or \`txkSetContextParam.pl\` (12.2) for JDBC descriptors. In 12.2, the dual-filesystem architecture adds one additional step — the change must be applied to both the run and patch edition context files, and AutoConfig must be run on each. A post-AutoConfig validation check that greps for \`ENABLE=BROKEN\` (or your specific custom parameter) in both the live \`tnsnames.ora\` and the \`\$CONTEXT_FILE\` closes the loop and confirms the change survived the cycle.
`.trim();

async function main() {
  await db.insert(posts).values({
    title: 'Preserving Custom JDBC and TNS Descriptors Across Oracle EBS Generations (11i, 12.1.3, 12.2)',
    slug,
    excerpt: 'AutoConfig silently overwrites tnsnames.ora and JDBC connect strings on every run. Definitive guide to making custom parameters like (ENABLE=BROKEN) permanent across EBS 11i (custom template directory), 12.1.3 (context file s_apps_jdbc_connect_descriptor), and 12.2 (txkSetContextParam.pl plus dual-edition synchronisation). Includes version comparison table and post-AutoConfig validation commands.',
    content,
    category: 'ebs-suite',
    isPremium: false,
    published: true,
    publishedAt: new Date(),
  });
  console.log('Inserted:', slug);
}

main().catch(console.error);
