import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'Oracle Siebel CRM: Topology, Installation, Maintenance, and Monitoring',
  slug: 'oracle-siebel-topology-install-maintain-monitoring',
  excerpt:
    'A technical deep-dive into Oracle Siebel CRM three-tier topology, installation sequence, day-to-day maintenance operations using Server Manager, and a complete bash health check script covering Gateway, AOM processes, component status, log scanning, and disk usage.',
  category: 'oracle-siebel' as const,
  isPremium: false,
  published: true,
  publishedAt: new Date('2026-06-18'),
  content: `Oracle Siebel CRM is a three-tier enterprise platform that has been in continuous production use for over two decades. Unlike SaaS CRM products, Siebel is fully self-hosted — every component, from the database to the web tier, runs on infrastructure you own and operate. This means the DBA and systems administrator must understand the full topology in detail to keep the platform running reliably. This post covers that topology, the installation sequence, daily and periodic maintenance operations, and a complete health check script you can run on a cron schedule.

---

## Siebel Architecture: The Three-Tier Topology

Siebel CRM uses a classic three-tier model. Each tier has a specific role and failure mode that every administrator must understand.

### Tier 1 — Database

The database tier runs Oracle Database — 19c for modern Innovation Pack releases, 11gR2 for legacy deployments. Siebel stores all CRM data in tables prefixed with \`S_\`:

| Table | Contents |
|---|---|
| \`S_CONTACT\` | Customer and employee contact records |
| \`S_ACCOUNT\` | Account (company) records |
| \`S_OPTY\` | Sales opportunity records |
| \`S_SRV_REQ\` | Service request / case records |
| \`S_EVT_ACT\` | Activity records (calls, tasks, emails) |
| \`S_ACCNT\` | Account alias table (used in some older schema versions) |

The database schema is owned by the \`SIEBEL\` Oracle user. Every record has a \`ROW_ID\` column of type \`VARCHAR2(15)\` — Siebel's own unique key, generated by an internal sequence, not an Oracle sequence. **Never access S_ tables directly with DML**. All data operations must go through the Siebel object layer (the AOM or EAI adapters). Direct SQL inserts will bypass business logic, skip workflow triggers, and can produce ROW_ID collisions.

Row-level locking is enforced at the Oracle level. Siebel does not use application-level locking — it relies on Oracle's row-level locks (\`SELECT ... FOR UPDATE\`). This means that long-running Siebel sessions holding locks on high-contention records (like shared account records in a large call center) will surface as blocking sessions in Oracle.

### Tier 2 — Application Object Manager

The application tier runs on one or more **Siebel Servers**. Each Siebel Server is a host running several background processes, organized into **Component Groups**. The most important component group is the one that contains **Application Object Manager (AOM)** components.

An AOM component is a named multi-threaded C++ process that manages user sessions for a specific functional area:

| AOM Component | Purpose |
|---|---|
| \`SCCObjMgr_enu\` | Siebel Call Center (Service + Sales) |
| \`SSEObjMgr_enu\` | Siebel Sales Enterprise |
| \`SFSObjMgr_enu\` | Siebel Field Service |
| \`SMCObjMgr_enu\` | Siebel Marketing |

Each AOM maintains a connection pool to the Oracle database via named subsystems:

- **DataMgr**: handles all SQL generation and Oracle connection management
- **InfraObjMgr**: manages the object model (business components, business objects, applets)
- **SRProc**: Siebel Request Processor — handles asynchronous task execution

The key sizing parameter per AOM component is \`MaxTasks\` — the maximum number of concurrent user sessions that AOM can serve. When active sessions approach \`MaxTasks\`, new login attempts queue or fail. Monitoring task counts against the \`MaxTasks\` threshold is the single most important operational metric for AOM health.

### Tier 3 — Web / Presentation

The web tier is built on the **Siebel Web Server Extension (SWSE)** — a plugin installed on Apache HTTP Server or Microsoft IIS. SWSE does not generate HTML itself; it acts as a protocol bridge between HTTPS (from the browser) and SISNAPI — Siebel's proprietary binary protocol — over TCP to the AOM.

From Innovation Pack 2013 onward, Siebel uses **Siebel Open UI** for rendering. Open UI delivers HTML5 and JavaScript to the browser, replacing the older Hi-Interactive rendering that required ActiveX or Java plugins. This change made Siebel browser-compatible without plugins, but SWSE and SISNAPI remain in the middle of every request.

In multi-server deployments, a load balancer (hardware or software) sits in front of two or more Apache/IIS instances, each running SWSE. Because SISNAPI sessions are stateful — each user's session context lives on a specific AOM thread — **session affinity (sticky sessions)** must be configured on the load balancer. Requests from the same user must always reach the same SWSE instance, which routes to the same AOM thread.

### Gateway Name Server

The **Gateway Name Server** is a separate process from the Siebel Server. It runs on its own host (often the same host as one Siebel Server in smaller deployments). Its role is a central registry: every Siebel Server in the enterprise registers its components with the Gateway at startup. The Gateway maintains the authoritative list of which servers are running which components and their current state.

The Gateway listens on port **2320** by default. If the Gateway is unreachable, no Siebel Server can start its components — the Gateway is a single point of failure by default. High-availability configurations run two Gateway processes in an active/passive arrangement, but this requires specific configuration and is not automatic.

### Enterprise Hierarchy

Siebel's configuration hierarchy maps directly to operational scope:

\`\`\`
Siebel Enterprise (SiebelEnterprise)
 └── Siebel Server: siebsrvr01
 │    └── Component Group: CallCenter
 │    │    └── Component: SCCObjMgr_enu  (AOM)
 │    │    └── Component: EAIObjMgr_enu  (EAI)
 │    └── Component Group: CommMgmt
 │         └── Component: CommSessionMgr
 │         └── Component: CommOutboundMgr
 └── Siebel Server: siebsrvr02
      └── Component Group: CallCenter
           └── Component: SCCObjMgr_enu  (AOM)
\`\`\`

One Enterprise → multiple Siebel Servers → multiple Component Groups → multiple Components. All servers within an Enterprise share the same Oracle database and the same Siebel Repository File (SRF).

---

## Installation Overview

Siebel installation follows a strict sequence. Installing components out of order results in failed registrations and configuration errors that are difficult to diagnose.

### Prerequisites

Before starting any Siebel installation:

- Oracle Database 11gR2+ or 19c, running and accessible
- OS user \`siebel\` created with correct shell environment
- \`/siebel\` filesystem with at least **100 GB** free (SES install footprint + logs + SRF)
- Environment variables set in \`siebel\` user profile:

\`\`\`bash
export JAVA_HOME=/usr/java/jdk1.8.0_341
export ORACLE_HOME=/u01/app/oracle/product/19c/dbhome_1
export ORACLE_SID=SIEBELDB
export PATH=\${JAVA_HOME}/bin:\${ORACLE_HOME}/bin:\${PATH}
export LD_LIBRARY_PATH=\${ORACLE_HOME}/lib:\${LD_LIBRARY_PATH}
\`\`\`

- NLS_CHARACTERSET must be AL32UTF8 in the Oracle database
- \`cursor_sharing = EXACT\` in Oracle init parameters (Siebel is incompatible with SIMILAR or FORCE)

### Installation Sequence

The installation order is mandatory:

| Step | Component | Notes |
|---|---|---|
| 1 | Gateway Name Server | Must be running before any Siebel Server install |
| 2 | Siebel Enterprise Server (SES) | Registers with Gateway; installs siebsrvr |
| 3 | Siebel Web Server Extension (SWSE) | Installed on each web server host |
| 4 | Database Configuration Utilities (dbsrvr) | Runs DDL scripts to create S_ tables |
| 5 | Innovation Pack / SIA patches | Applied after base install, before go-live |

### Key Directories

\`\`\`
/siebel/ses/gtwysrvr/        Gateway Name Server root
/siebel/ses/siebsrvr/        Siebel Server root (SIEBEL_ROOT)
/siebel/ses/siebsrvr/log/    Server and component log files
/siebel/ses/siebsrvr/bin/    Siebel Server binaries (siebmtsh, srvrmgr)
/siebel/ses/siebsrvr/cfgtoollogs/   Configuration logs
/siebel/swse/                Web Server Extension root
/siebel/dbsrvr/              Database configuration utilities
\`\`\`

### Key Configuration Files

- \`siebel.cfg\` — Main Siebel Server configuration. Located in \`siebsrvr/bin/\`. Controls DataMgr connection strings, AOM parameters, file system path, and component defaults.
- \`eapps.cfg\` — SWSE configuration. Located in the SWSE install directory. Controls which Siebel applications are exposed on which URLs, virtual host settings, and the connect strings to Siebel Servers (SISNAPI addresses).

---

## Maintenance Operations

### Server Manager (srvrmgr)

The primary CLI for Siebel Server administration is **srvrmgr** (Server Manager). Connect as SADMIN:

\`\`\`bash
\${SIEBEL_ROOT}/bin/srvrmgr \\
  /g siebgw01 \\
  /e SiebelEnterprise \\
  /s siebsrvr01 \\
  /u SADMIN \\
  /p \${SADMIN_PASSWORD}
\`\`\`

Once connected, the srvrmgr prompt accepts commands:

\`\`\`
srvrmgr> list comp
srvrmgr> list comp for server siebsrvr01
srvrmgr> start comp SiebelCallCenter_1
srvrmgr> stop comp SiebelCallCenter_1
srvrmgr> list tasks for comp SCCObjMgr_enu
srvrmgr> change param MaxTasks=75 for comp SCCObjMgr_enu
srvrmgr> quit
\`\`\`

The \`list comp\` output shows \`CP_DISP_RUN_STATE\` for each component. Healthy components show **Running**. **Shutdown**, **Offline**, or **Failed** states require investigation.

### Log Management

Siebel logs to the \`SIEBEL_ROOT/log/\` directory. Logs are not automatically rotated — they grow indefinitely until you manage them:

- \`siebsrvr.log\` — the main Siebel Server log (startup, shutdown, component registration events)
- \`ComponentName_taskid.log\` — per-task logs for each AOM session. A busy AOM generates thousands of these files per day.
- \`gtwysrvr.log\` — Gateway Name Server log

Recommended log management:

\`\`\`bash
# Weekly archive — compress logs older than 7 days
find \${SIEBEL_ROOT}/log -name "*.log" -mtime +7 -exec gzip {} \;

# Monthly purge — delete compressed logs older than 90 days
find \${SIEBEL_ROOT}/log -name "*.log.gz" -mtime +90 -delete
\`\`\`

### Database Maintenance

Siebel S_ tables require regular database maintenance. Unlike typical OLTP schemas, Siebel has a wide schema with many tables that receive uneven write loads:

**Monthly:**
\`\`\`sql
-- Update stats on key S_ tables (run as SIEBEL or DBA)
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'SIEBEL', tabname => 'S_CONTACT', cascade => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'SIEBEL', tabname => 'S_OPTY', cascade => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'SIEBEL', tabname => 'S_ACCOUNT', cascade => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'SIEBEL', tabname => 'S_SRV_REQ', cascade => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'SIEBEL', tabname => 'S_EVT_ACT', cascade => TRUE);
\`\`\`

**Quarterly — index rebuild:**
\`\`\`sql
-- Identify fragmented indexes on key tables
SELECT index_name, blevel, leaf_blocks, num_rows
FROM   dba_indexes
WHERE  owner = 'SIEBEL'
AND    table_name IN ('S_CONTACT','S_OPTY','S_ACCNT','S_EVT_ACT')
ORDER  BY blevel DESC;

-- Rebuild indexes with blevel > 3
ALTER INDEX SIEBEL.S_CONTACT_P1 REBUILD ONLINE;
ALTER INDEX SIEBEL.S_OPTY_P1 REBUILD ONLINE;
\`\`\`

### Patching

Siebel patches are delivered as **SIA (Siebel Innovation Architecture) patches** or **Quick Fix Engineering (QFE)** patches:

1. Download patch from Oracle Support (My Oracle Support)
2. Stop all Siebel Server components via srvrmgr
3. Stop the Siebel Server service
4. Apply patch using the Siebel installer in patch mode
5. If schema changes are included, run dbsrvr upgrade scripts as SADMIN
6. Restart Siebel Server and Gateway
7. Validate component status via \`list comp\`

---

## Monitoring Key Metrics

| Metric | How to Check | Alert Threshold |
|---|---|---|
| AOM task count | \`list tasks for comp SCCObjMgr_enu\` | >80% of MaxTasks |
| Component run state | \`list comp\` → CP_DISP_RUN_STATE | Any non-Running state |
| ORA- errors in logs | \`grep ORA- siebsrvr.log\` | Any ORA- error |
| SBL- error codes | \`grep "SBL-" \${SIEBEL_ROOT}/log/*.log\` | SBL-EAI, SBL-SVC critical codes |
| FATAL log entries | \`grep FATAL siebsrvr.log\` | Any occurrence |
| DB connection pool | DataMgr stats in srvrmgr | Pool utilization >75% |
| SWSE health endpoint | HTTP GET to /eai_enu/start.swe | Non-200 response |
| Gateway availability | TCP connect to port 2320 | Connection refused |
| Disk usage on /siebel | \`df -h /siebel\` | >80% used |

---

## Health Check Script

The following bash script checks the key Siebel health indicators and sends an email alert if any check fails. Run it on the Siebel Server host.

\`\`\`bash
#!/bin/bash
# ============================================================
# Siebel CRM Health Check Script
# Run every 15 minutes via cron
# ============================================================

SIEBEL_ROOT=/siebel/ses/siebsrvr
GATEWAY_HOST=siebgw01
GATEWAY_PORT=2320
ENTERPRISE=SiebelEnterprise
SIEBEL_SERVER=siebsrvr01
SADMIN_PASS=changeme
ALERT_EMAIL=dba@example.com
SIEBEL_FS=/siebel
DISK_THRESHOLD=80
ERRORS=0
ALERT_MSG=""
LOG=/tmp/siebel_health_\$(date +%Y%m%d_%H%M%S).log

log() {
  echo "\$(date '+%Y-%m-%d %H:%M:%S') \$1" | tee -a "\$LOG"
}

add_alert() {
  ERRORS=\$((ERRORS + 1))
  ALERT_MSG="\${ALERT_MSG}\\nALERT: \$1"
  log "ALERT: \$1"
}

# --- Check 1: Gateway Name Server port ---
check_gateway() {
  log "Checking Gateway Name Server \${GATEWAY_HOST}:\${GATEWAY_PORT}..."
  if nc -z -w5 "\${GATEWAY_HOST}" "\${GATEWAY_PORT}" 2>/dev/null; then
    log "  Gateway port \${GATEWAY_PORT}: OK"
  else
    add_alert "Gateway Name Server \${GATEWAY_HOST}:\${GATEWAY_PORT} is unreachable"
  fi
}

# --- Check 2: Siebel Server process ---
check_siebel_process() {
  log "Checking Siebel Server process (siebmtsh)..."
  if pgrep -x siebmtsh > /dev/null 2>&1; then
    PROC_COUNT=\$(pgrep -x siebmtsh | wc -l)
    log "  siebmtsh processes running: \${PROC_COUNT}"
  else
    add_alert "siebmtsh process not found — Siebel Server may be down"
  fi
}

# --- Check 3: Component status via srvrmgr ---
check_component_status() {
  log "Checking component status via srvrmgr..."
  COMP_OUTPUT=\$(\${SIEBEL_ROOT}/bin/srvrmgr \
    /g "\${GATEWAY_HOST}" \
    /e "\${ENTERPRISE}" \
    /s "\${SIEBEL_SERVER}" \
    /u SADMIN \
    /p "\${SADMIN_PASS}" << 'SRVRMGR_EOF'
list comp
quit
SRVRMGR_EOF
  )
  if echo "\${COMP_OUTPUT}" | grep -qE "(Offline|Shutdown|Failed)"; then
    FAILED_COMPS=\$(echo "\${COMP_OUTPUT}" | grep -E "(Offline|Shutdown|Failed)" | awk '{print \$1}')
    add_alert "Components not in Running state: \${FAILED_COMPS}"
  else
    log "  All components appear Running"
  fi
  echo "\${COMP_OUTPUT}" >> "\${LOG}"
}

# --- Check 4: Log error scan (last 60 minutes) ---
check_log_errors() {
  log "Scanning logs for errors in last 60 minutes..."
  RECENT_ERRORS=0

  # Find log files modified in last 60 minutes
  while IFS= read -r -d '' logfile; do
    ERROR_COUNT=\$(grep -cE "(ORA-[0-9]+|SBL-[A-Z]+-[0-9]+|FATAL)" "\${logfile}" 2>/dev/null || echo 0)
    if [ "\${ERROR_COUNT}" -gt 0 ]; then
      RECENT_ERRORS=\$((RECENT_ERRORS + ERROR_COUNT))
      log "  Found \${ERROR_COUNT} errors in \${logfile}"
    fi
  done < <(find "\${SIEBEL_ROOT}/log" -name "*.log" -newer /tmp/siebel_health_marker -print0 2>/dev/null)

  # Update marker file for next run
  touch /tmp/siebel_health_marker

  if [ "\${RECENT_ERRORS}" -gt 0 ]; then
    add_alert "Found \${RECENT_ERRORS} ORA-/SBL-/FATAL error(s) in recent logs — check \${SIEBEL_ROOT}/log"
  else
    log "  No critical errors found in recent logs"
  fi
}

# --- Check 5: Disk usage ---
check_disk_space() {
  log "Checking disk usage on \${SIEBEL_FS}..."
  USAGE=\$(df "\${SIEBEL_FS}" | awk 'NR==2 {gsub(/%/,"",$5); print \$5}')
  log "  \${SIEBEL_FS} disk usage: \${USAGE}%"
  if [ "\${USAGE}" -gt "\${DISK_THRESHOLD}" ]; then
    add_alert "Disk usage on \${SIEBEL_FS} is \${USAGE}% (threshold: \${DISK_THRESHOLD}%)"
  fi
}

# --- Send alert email ---
send_alert() {
  echo -e "Siebel Health Check Alert\\nHost: \$(hostname)\\nTime: \$(date)\\n\${ALERT_MSG}\\n\\nSee log: \${LOG}" \
    | mail -s "Siebel Alert: \${ERRORS} issue(s) on \$(hostname)" "\${ALERT_EMAIL}"
  log "Alert email sent to \${ALERT_EMAIL}"
}

# ---- Main execution ----
log "=== Siebel Health Check Start ==="
check_gateway
check_siebel_process
check_component_status
check_log_errors
check_disk_space

if [ "\${ERRORS}" -gt 0 ]; then
  log "Total issues found: \${ERRORS}"
  send_alert
else
  log "All checks passed — no issues detected"
fi

log "=== Siebel Health Check End ==="
\`\`\`

### Crontab Schedule

Add the following to the \`siebel\` user's crontab (\`crontab -e\`):

\`\`\`
# Siebel health check every 15 minutes
*/15 * * * * /opt/scripts/siebel_health.sh >> /var/log/siebel_health.log 2>&1
\`\`\`

---

## Summary and Operational Guidance

Understanding Siebel topology is prerequisite to operating it reliably. A few operational principles that experienced Siebel DBAs follow consistently:

**Keep component groups lean.** Only enable the component groups you actively use. Every running component consumes Oracle DB connections and server memory. A Siebel Server with 15 enabled components uses significantly more Oracle connection slots than one with 5. Review enabled components annually and disable anything that has zero active sessions.

**Monitor task counts continuously.** The most common Siebel user experience problem — refused or queued logins — is caused by AOM task counts hitting the \`MaxTasks\` ceiling. Monitor this metric every 15 minutes. If you regularly see task counts above 70% of \`MaxTasks\` during business hours, either increase \`MaxTasks\` or add a second AOM process via \`MaxMTServers\`.

**Treat the Gateway as a single point of failure.** The Gateway Name Server is required for Siebel Server startup and component registration. If the Gateway process or host fails, your Siebel application servers cannot start their components. Even if the Gateway restarts quickly, currently running AOM components must re-register — this causes brief outages. In production environments, plan for Gateway HA from the start, not as an afterthought.

**Keep database statistics current.** Siebel's SQL generation is sensitive to optimizer statistics. The AOM generates complex multi-table queries at runtime based on what the user is doing. Stale statistics on high-volume tables like \`S_CONTACT\` and \`S_EVT_ACT\` lead to full table scans and dramatic performance degradation. Run stats jobs monthly on key S_ tables — or set up automated statistics collection targeting the Siebel schema.

**Establish a log review cadence.** The Siebel server log directory will accumulate thousands of files in a matter of days on a busy system. Build a weekly review process: look for ORA-04031 (shared pool exhaustion), ORA-00257 (archiver stuck), and SBL-EAI- error codes in the most recent siebsrvr.log and AOM task logs. Catching these early prevents them from becoming production incidents.
`,
};

async function main() {
  console.log('Inserting Siebel topology blog post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: {
      title: post.title,
      excerpt: post.excerpt,
      content: post.content,
      category: post.category,
      published: post.published,
      isPremium: post.isPremium,
      publishedAt: post.publishedAt,
      updatedAt: new Date(),
    },
  });
  console.log('Inserted:', post.slug);
}

main().catch(console.error);
