import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';

const slug = 'ebs-tns-ifile-context-file-internal-concurrent-manager';

const content = `
Oracle EBS generates most of its configuration files automatically through AutoConfig — tnsnames.ora included. That convenience comes with a constraint: every time AutoConfig runs, it overwrites the generated tnsnames.ora with a fresh copy derived from the context file. Any manual additions made directly to the generated file are silently lost.

The TNS ifile mechanism exists to solve this. A single IFILE directive in the AutoConfig-generated tnsnames.ora points to a second file that AutoConfig does not touch. DBAs maintain that second file independently, and Oracle Net reads both files together on every connection attempt.

This post covers how the TNS ifile works, where its path is stored in the \`\$CONTEXT_FILE\`, how the Internal Concurrent Manager depends on it at startup, how the TNS admin directory structure differs across EBS 11i, R12.1.3, and R12.2.x, and how to maintain the ifile correctly on both the application tier and the database tier.

---

## The EBS Code Tree and TNS Admin Directories

The location of TNS configuration files — tnsnames.ora, sqlnet.ora, and the ifile — is directly tied to the EBS code tree structure, which changed significantly between releases.

### EBS 11i

In 11i, the application tier uses the iAS Oracle Home for its web server and Forms runtime. The TNS admin for the application middle tier is under the iAS home:

\`\`\`
\$IAS_ORACLE_HOME/                         ← iAS / Apache Oracle Home
  network/
    admin/
      tnsnames.ora                         ← generated by AutoConfig
      sqlnet.ora                           ← generated by AutoConfig
      ifile.ora                            ← DBA-maintained; NOT regenerated

\$APPL_TOP/admin/\${CONTEXT_NAME}/
  out/
    tnsnames.ora                           ← AutoConfig output (source)
\`\`\`

The database tier has its own TNS admin under the database Oracle Home:

\`\`\`
\$ORACLE_HOME/                             ← Database Oracle Home
  network/
    admin/
      tnsnames.ora                         ← generated by DB-tier AutoConfig
      sqlnet.ora
      ifile.ora                            ← DBA-maintained on DB tier
\`\`\`

In 11i, \`TNS_ADMIN\` is set to the iAS home's \`network/admin\` directory for the application tier and to the database Oracle Home's \`network/admin\` for the database tier.

### EBS R12.1.3

R12.1 introduced two Oracle Homes on the application tier — 10.1.2 (for Forms and Reports) and 10.1.3 (for OC4J and OA Framework) — each with its own network/admin directory. The instance-level directory (\`\$INST_TOP\`) holds the generated network files:

\`\`\`
\$INST_TOP/                                ← Instance home
  ora/
    10.1.2/                               ← Forms/Reports Oracle Home (application tier)
      network/
        admin/
          tnsnames.ora                    ← generated by AutoConfig
          sqlnet.ora
          ifile.ora                       ← DBA-maintained
    10.1.3/                               ← OC4J Oracle Home (application tier)
      network/
        admin/
          tnsnames.ora                    ← generated by AutoConfig (separate copy)
          sqlnet.ora
          ifile.ora                       ← DBA-maintained
\`\`\`

The database tier in R12.1 still uses the standard:

\`\`\`
\$ORACLE_HOME/network/admin/tnsnames.ora   ← generated by DB-tier AutoConfig
\$ORACLE_HOME/network/admin/ifile.ora      ← DBA-maintained on DB tier
\`\`\`

### EBS R12.2.x

R12.2 uses a single application Oracle Home but the instance directory is shared across editions. The TNS admin directories live under the shared instance tree rather than the edition-specific file systems:

\`\`\`
/u01/applmgr/EBSPRD/
  inst/
    apps/
      \${CONTEXT_NAME}/
        ora/
          10.1.2/
            network/
              admin/
                tnsnames.ora             ← generated by AutoConfig
                sqlnet.ora
                ifile.ora                ← DBA-maintained; survives adop cycles
\`\`\`

Because the \`inst\` directory is not part of the editioned file system (\`fs1\`/\`fs2\`), the ifile survives \`adop\` patching cycles without being overwritten. This makes the ifile even more important in R12.2: it is the one place where custom TNS entries reliably persist across both AutoConfig runs and online patching.

---

## What Is the TNS ifile?

The \`IFILE\` directive is a standard Oracle Net parameter supported in \`tnsnames.ora\`, \`sqlnet.ora\`, and \`listener.ora\`. When Oracle Net reads a configuration file and encounters an IFILE directive, it reads the referenced file as if its contents were embedded inline at that point.

In a generated \`tnsnames.ora\`, the IFILE entry looks like:

\`\`\`
IFILE = /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/ifile.ora
\`\`\`

Oracle Net then reads \`ifile.ora\` and merges its entries with those in \`tnsnames.ora\`. From the perspective of any process resolving a service name — sqlplus, JDBC thin, the ICM — entries in \`ifile.ora\` are indistinguishable from entries declared directly in \`tnsnames.ora\`.

### What goes in the ifile

The ifile holds TNS service name entries that need to survive AutoConfig. Common entries:

- **Read-only standby service** — a service registered on an Active Data Guard standby for offloading reporting queries
- **RAC-specific load balancing services** — services that target specific RAC nodes or use specific connection policies
- **Custom SCAN listener entries** — SCAN address entries with non-standard ports or retry settings
- **Third-party application service aliases** — connections to external databases (ERP integrations, ETL pipelines)
- **CP-specific service overrides** — if \`s_cp_twotask\` points to a service defined in the ifile rather than the main tnsnames.ora

### What the ifile is not

The ifile is not:
- A replacement for tnsnames.ora — it supplements it
- A place to override entries in tnsnames.ora — if the same alias exists in both files, the behavior is implementation-defined and should be avoided
- Automatically validated by AutoConfig — errors in the ifile are silent until a connection attempt fails

---

## The s_ifile Parameter in \$CONTEXT_FILE

AutoConfig writes the IFILE directive into the generated tnsnames.ora based on the \`s_ifile\` parameter in the context file. The entry in \`\$CONTEXT_FILE\` looks like:

\`\`\`xml
<s_ifile oa_var="s_ifile">/u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/ifile.ora</s_ifile>
\`\`\`

To view the current value:

\`\`\`bash
grep -i "s_ifile" \$CONTEXT_FILE
\`\`\`

When AutoConfig runs, it writes this path into the generated tnsnames.ora as:

\`\`\`
IFILE = <value of s_ifile>
\`\`\`

### Key behavior: AutoConfig creates a placeholder ifile if the path is absent

On first-time installations or after certain patch cycles, AutoConfig may generate an empty ifile at the path specified in \`s_ifile\`. This placeholder file is valid — it is read by Oracle Net, but it contains no entries, so it has no effect on TNS resolution. DBAs add entries to this file manually.

### What happens when s_ifile is blank or wrong

If \`s_ifile\` is empty in the context file, AutoConfig generates a tnsnames.ora with no IFILE directive. Any custom TNS entries that existed in the ifile are no longer reachable unless \`TNS_ADMIN\` is also set to pick up the file through another mechanism.

If \`s_ifile\` points to a path that does not exist at runtime, Oracle Net silently ignores the IFILE directive. No error is raised at the application tier — the failure surfaces only when a process attempts to resolve a service name that was defined only in the missing ifile.

---

## The Internal Concurrent Manager and TNS ifile

The Internal Concurrent Manager (ICM) is the master process that starts, monitors, and shuts down all other concurrent managers. It connects to the database at startup using the service name in the \`CP_TWO_TASK\` environment variable.

### The ICM startup TNS dependency chain

\`\`\`
ICM startup
     │
     ▼
Reads CP_TWO_TASK environment variable (set by AutoConfig from s_cp_twotask)
     │
     ▼
Calls Oracle Net to resolve CP_TWO_TASK service name
     │
     ▼
Oracle Net reads \$TNS_ADMIN/tnsnames.ora
     │
     ├── Service found in tnsnames.ora → connect succeeds
     │
     └── Service NOT found in tnsnames.ora
              │
              ▼
         Oracle Net reads IFILE entry from tnsnames.ora
              │
              ├── ifile.ora exists and contains the service → connect succeeds
              │
              └── ifile missing, empty, or service not defined → ORA-12154
\`\`\`

### When CP_TWO_TASK is defined in the ifile

This is the most common source of ICM startup failures after an AutoConfig run or a code tree migration. If a DBA placed the Concurrent Processing service definition in ifile.ora rather than in tnsnames.ora — which is a valid configuration — and then AutoConfig changes the \`s_ifile\` path or the path becomes inaccessible, the ICM fails to start with:

\`\`\`
ORA-12154: TNS:could not resolve the connect identifier specified
\`\`\`

The error message does not indicate whether the failure was in tnsnames.ora or in the ifile. The resolution is:

\`\`\`bash
# Check whether the IFILE directive is present in the generated tnsnames.ora
grep -i "ifile" \$TNS_ADMIN/tnsnames.ora

# Check whether the ifile exists and is readable
cat \$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')

# Verify the CP_TWO_TASK service is in either file
tnsping \$CP_TWO_TASK
\`\`\`

### ICM and the ifile across EBS versions

| Version | TNS_ADMIN (app tier) | ifile typical path | ICM startup risk if ifile missing |
|---------|---------------------|-------------------|------------------------------------|
| 11i | \`\$IAS_ORACLE_HOME/network/admin\` | Same dir, \`ifile.ora\` | ORA-12154 on ICM startup if CP service in ifile |
| R12.1.3 | \`\$INST_TOP/ora/10.1.2/network/admin\` | Same dir, \`ifile.ora\` | ORA-12154 on ICM startup |
| R12.2.x | \`\$INST_TOP/apps/\${CONTEXT_NAME}/ora/10.1.2/network/admin\` | Same dir, \`ifile.ora\` | ORA-12154 on ICM startup; persists across adop cycles |

---

## Using the TNS ifile on the Application Tier

### Locate the active ifile path

\`\`\`bash
# From context file
grep -i "s_ifile" \$CONTEXT_FILE

# From the generated tnsnames.ora (confirms AutoConfig wrote the directive)
grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora

# Confirm the file exists and is readable
IFILE_PATH=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
ls -lh "\${IFILE_PATH}"
\`\`\`

### Add a custom TNS entry to the ifile

\`\`\`bash
# Never edit tnsnames.ora directly — edit the ifile
vi "\${IFILE_PATH}"

# Add the entry using standard TNS syntax:
# EBSPRD_CP =
#   (DESCRIPTION =
#     (ADDRESS = (PROTOCOL = TCP)(HOST = dbhost.example.com)(PORT = 1521))
#     (CONNECT_DATA =
#       (SERVER = DEDICATED)
#       (SERVICE_NAME = EBSPRD_CP)
#     )
#   )
\`\`\`

### Verify the new entry resolves

\`\`\`bash
tnsping EBSPRD_CP
\`\`\`

If \`tnsping\` resolves successfully, Oracle Net is reading the ifile correctly.

### Verify after an AutoConfig run

AutoConfig regenerates tnsnames.ora but does not touch ifile.ora. After any AutoConfig run, confirm:

\`\`\`bash
# 1. IFILE directive is still in the generated tnsnames.ora
grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora

# 2. The ifile path in tnsnames.ora matches s_ifile in the context file
TNSNAMES_IFILE=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
CTX_IFILE=\$(grep -i "s_ifile" \$CONTEXT_FILE | sed 's/.*>\\(.*\\)<.*/\\1/' | tr -d '[:space:]')
echo "tnsnames.ora IFILE : \${TNSNAMES_IFILE}"
echo "Context file s_ifile: \${CTX_IFILE}"

# 3. Custom entries still resolve
tnsping EBSPRD_CP
\`\`\`

### R12.2 — ifile after an adop cycle

In R12.2, the \`inst\` directory is not editioned, so the ifile is not affected by \`adop phase=cutover\`. Verify this after each online patching cycle:

\`\`\`bash
source /u01/applmgr/EBSPRD/EBSapps.env run

grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora
tnsping \$CP_TWO_TASK
\`\`\`

If the IFILE directive disappears from tnsnames.ora after a cutover, the adop cycle regenerated tnsnames.ora using a context file where \`s_ifile\` was blank. This requires correcting the context file and re-running AutoConfig.

---

## Using the TNS ifile on the Database Tier

The database tier has its own \`tnsnames.ora\` — separate from the application tier's. This file is also regenerated by the DB-tier AutoConfig run and also supports an IFILE directive.

### Locate the DB-tier TNS admin

\`\`\`bash
# Standard location
echo \$ORACLE_HOME/network/admin

# Verify which tnsnames.ora is in use
echo \$TNS_ADMIN
ls -lh \$TNS_ADMIN/tnsnames.ora
\`\`\`

### DB-tier ifile use cases

The most common entries added to the DB-tier ifile:

- **Cross-database dblinks** — remote database connection strings for database links that the EBS database creates
- **Listener alias entries** — alternate service names for listener registration testing
- **Standby connection aliases** — connection strings for the physical standby database, used in switchover or DR testing procedures
- **Monitoring tool service names** — entries used by monitoring agents (OEM, third-party) that should survive DBA-managed AutoConfig runs

### Add an entry to the DB-tier ifile

\`\`\`bash
# Locate the DB-tier ifile
DB_IFILE=\$(grep -i "^IFILE" \$ORACLE_HOME/network/admin/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')

# If no IFILE directive exists yet, create one
if [ -z "\${DB_IFILE}" ]; then
  DB_IFILE=\$ORACLE_HOME/network/admin/ifile.ora
  echo "IFILE = \${DB_IFILE}" >> \$ORACLE_HOME/network/admin/tnsnames.ora
fi

# Edit the ifile
vi "\${DB_IFILE}"
\`\`\`

### Verify DB-tier resolution

\`\`\`bash
\$ORACLE_HOME/bin/tnsping <new_service_name>
\`\`\`

### DB-tier AutoConfig considerations

The DB-tier AutoConfig reads its own context file (stored at the database node's \`appsutil\` path). If \`s_ifile\` is set in the DB-tier context file, AutoConfig generates a DB-tier tnsnames.ora with the IFILE directive. If it is not set, the directive is absent and any ifile entries added manually will not be read.

\`\`\`bash
# On the database node
source /u01/oracle/EBSPRD/appsutil/env/EBSPRD_\$(hostname -s).env
grep -i "s_ifile" \$CONTEXT_FILE
\`\`\`

---

## Troubleshooting: ICM Fails to Start After AutoConfig

**Symptom:** ICM fails with ORA-12154 immediately after an AutoConfig run. Forms sessions and self-service sessions work normally (because their TWO_TASK service is in tnsnames.ora), but the ICM cannot connect.

**Diagnosis:**

\`\`\`bash
# 1. What service is the ICM trying to connect to?
echo "CP_TWO_TASK: \$CP_TWO_TASK"

# 2. Does that service resolve?
tnsping \$CP_TWO_TASK
# If this returns ORA-12154, the service is not in tnsnames.ora or ifile

# 3. Is IFILE in the generated tnsnames.ora?
grep -i "IFILE" \$TNS_ADMIN/tnsnames.ora

# 4. Does the ifile exist?
IFILE_PATH=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
[ -f "\${IFILE_PATH}" ] && echo "ifile exists" || echo "ifile MISSING"

# 5. Is the CP_TWO_TASK service in the ifile?
grep -i "\$CP_TWO_TASK" "\${IFILE_PATH}"
\`\`\`

**Resolution options:**

Option A — Add the CP_TWO_TASK service to the main tnsnames.ora (outside AutoConfig scope is not possible, but the context file approach is):

Add the service to the context file's TNS template section and re-run AutoConfig so it appears in the generated tnsnames.ora.

Option B — Restore the ifile at the path referenced in tnsnames.ora:

\`\`\`bash
# If the ifile was at a different path before AutoConfig changed it
# Check the old ifile path from context file backup
grep -i "s_ifile" \${CONTEXT_FILE}.\$(ls -t \${CONTEXT_FILE}.*.bak 2>/dev/null | head -1 | awk -F'.' '{print \$NF}')

# Create or restore the ifile at the new path with the required entries
cat >> "\${IFILE_PATH}" << 'IFILEENTRY'
EBSPRD_CP =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = dbhost.example.com)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = EBSPRD_CP)
    )
  )
IFILEENTRY
\`\`\`

Option C — Update \`s_ifile\` in the context file to point to the existing ifile, then re-run AutoConfig:

\`\`\`bash
# Edit CONTEXT_FILE to set s_ifile to the correct path
vi \$CONTEXT_FILE

# Re-run AutoConfig
cd \$AD_TOP/bin
./adautocfg.sh

# Restart ICM
\$FND_TOP/bin/adcmctl.sh stop apps/<apps_password>
\$FND_TOP/bin/adcmctl.sh start apps/<apps_password>
\`\`\`

---

## Summary

The TNS ifile is the mechanism that allows custom Oracle Net service name entries to survive AutoConfig regeneration of tnsnames.ora. Its path is stored in the \`s_ifile\` parameter in the Applications Context File (\`\$CONTEXT_FILE\`), and AutoConfig writes an \`IFILE =\` directive into the generated tnsnames.ora that points to it.

The Internal Concurrent Manager depends on this chain at every startup: it reads the \`CP_TWO_TASK\` environment variable, asks Oracle Net to resolve the service name, and Oracle Net follows the IFILE directive if the service is not found in tnsnames.ora directly. If the ifile is missing, inaccessible, or does not contain the CP_TWO_TASK service definition, the ICM fails with ORA-12154 while the rest of the EBS application tier — which uses the general TWO_TASK service in tnsnames.ora — continues working normally. This selective failure pattern is the most reliable diagnostic indicator that the problem is in the ifile rather than in tnsnames.ora or the network.

Across all three EBS release families, the ifile path changes with the code tree layout but the behavior is identical. In R12.2.x, the ifile benefits from its position in the non-editioned \`inst\` directory, which means adop patching cycles do not affect it — but AutoConfig changes to \`s_ifile\` can still break the chain if the context file is updated without recreating the ifile at the new path.
`.trim();

async function main() {
  await db.insert(posts).values({
    title: 'EBS TNS ifile and the Internal Concurrent Manager: Context File Parameter, Code Tree Paths, and ICM Startup Dependency Across 11i, R12.1.3, and R12.2.x',
    slug,
    excerpt: 'The TNS ifile lets custom Oracle Net entries survive AutoConfig regeneration of tnsnames.ora. Its path is stored in s_ifile in $CONTEXT_FILE. The Internal Concurrent Manager depends on the complete tnsnames.ora → IFILE → ifile.ora chain at every startup — if the CP_TWO_TASK service lives in the ifile and the ifile is missing or inaccessible, the ICM fails with ORA-12154 while Forms and self-service sessions continue normally. This post covers the ifile mechanism, the s_ifile context parameter, TNS admin directory paths across 11i, R12.1.3, and R12.2.x, and how to correctly maintain the ifile on both the application tier and the database tier.',
    content,
    category: 'ebs-suite',
    isPremium: false,
    published: true,
    publishedAt: new Date(),
  });
  console.log('Inserted:', slug);
}

main().catch(console.error);
