import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'Oracle Temporary Tablespace: Sort Operations, PGA, and Temp Space Management',
  slug: 'oracle-temp-tablespace-sort-pga-management',
  excerpt:
    'A thorough examination of Oracle temporary tablespace architecture — covering how sort and hash operations spill from PGA to disk, how to size PGA_AGGREGATE_TARGET to eliminate most temp I/O, and how to prevent ORA-01652 "unable to extend temp segment" through proper tablespace sizing, monitoring with V$TEMPSEG_USAGE, and understanding the OPTIMAL vs ONE PASS vs MULTI PASS execution model.',
  category: 'oracle-database' as const,
  published: true,
  isPremium: false,
  publishedAt: new Date('2026-06-05'),
  youtubeUrl: null,
  content: `## Introduction

Oracle's temporary tablespace is one of the most frequently misunderstood storage components in the database. Unlike permanent tablespaces, which hold tables, indexes, and other database objects that survive instance crashes and shutdowns, the temporary tablespace holds only transient working data — data that exists for the duration of a session's work area operations and is silently discarded when the session's operation completes or the instance restarts. There is no recovery for temp tablespace content: no redo is generated for writes to temp, no undo is required, and no archiving occurs. The temp tablespace is, by design, ephemeral. Understanding this fundamental characteristic is the prerequisite for everything else in this article.

The temporary tablespace is used whenever a SQL operation cannot complete entirely in memory. The operations that consume temp space are: sort operations (ORDER BY, GROUP BY, DISTINCT, certain index scans) whose intermediate data exceeds the PGA work area allocated to that sort; hash joins whose build-side hash table exceeds the available PGA work area; bitmap merge operations in star query plans; global temporary table (GTT) data for the duration of a transaction or session; and index creation with SORT operations on large tables. Every one of these operations begins by attempting to execute entirely in memory — temp space is only the fallback when memory is insufficient. This is why the relationship between PGA sizing and temp tablespace usage is so direct: a well-sized PGA eliminates most temp tablespace I/O entirely, while an undersized PGA forces every moderately complex query to spill to disk, producing unnecessary I/O and degraded query performance.

The relationship between PGA and the temp tablespace is the central tuning lever for managing sort and hash operation performance. PGA (Process Global Area) is the private memory area allocated to each Oracle server process. Within the PGA, the SQL work area is the portion allocated to sort and hash operations. Oracle's Automatic Memory Management for PGA (controlled by \`PGA_AGGREGATE_TARGET\`) attempts to give each active work area a share of the available PGA budget, executing as many operations in memory as possible. When the work area cannot fit in the available PGA — because too many concurrent operations are competing for the same pool, or because a single operation is processing a data set that genuinely exceeds available memory — Oracle spills the excess to the temporary tablespace. The temp tablespace is Oracle's mechanism for completing work that would otherwise be impossible, but it comes with an I/O cost that makes it a fallback, not a design target.

ORA-01652 "unable to extend temp segment" is the most common temp tablespace error and has a clear and limited set of causes. The temp tablespace is genuinely too small for the current workload, a runaway query is consuming all available temp space while concurrent sessions need their share, or the temp datafiles have autoextend disabled or have hit their configured maximum size. Unlike ORA-01555 (snapshot too old), which is a correctness error with complex root causes, ORA-01652 is a capacity error — the database ran out of room to complete an operation. The diagnosis is always the same: query \`V\$TEMPSEG_USAGE\` to find who is consuming temp space and how much, check the high-water mark in \`V\$SORT_SEGMENT\`, and then determine whether the fix is adding a temp datafile, increasing PGA to reduce spill, or terminating a runaway session.

---

## How Temp Tablespace Works: Sort and Hash Operations

Oracle allocates sort runs and hash partitions in the temporary tablespace when in-memory work area is exhausted. Understanding the mechanics of this spill is essential for diagnosing and resolving temp-related performance problems. The external sort algorithm Oracle uses is a multi-pass merge sort: Oracle sorts as much data as fits in the PGA work area, writes the sorted run to the temp tablespace, reads the next chunk of unsorted data into the work area, sorts it, writes another sorted run, and continues until all input data has been processed into sorted runs on disk. The final step is an external merge: Oracle reads from all the sorted runs in parallel, merging them into the final sorted output. If the number of sorted runs fits within a single merge pass, Oracle calls this a ONE PASS sort. If the number of runs is so large that a single merge pass would require more concurrent open files than Oracle's sort merge fanout allows, Oracle must perform multiple merge passes — this is a MULTI PASS sort, the most expensive possible execution mode.

For a hash join, the mechanism is analogous but involves partitioning rather than sorting. Oracle reads the build-side (smaller) input and builds a hash table in the PGA work area. If the hash table fits entirely in the work area, the probe-side (larger) input is streamed through and matched against the in-memory hash table — a ONE PASS or OPTIMAL hash join. If the hash table does not fit in the PGA work area, Oracle partitions the build input: each partition goes to its own hash bucket, and when a bucket exceeds the work area, it is written to temp. The probe input is then also partitioned using the same hash function, and each probe partition is matched against the corresponding build partition on disk. This is a two-pass hash join. If the partitions themselves are still too large for the work area, Oracle must perform additional partitioning passes — a MULTI PASS hash join. Each additional pass multiplies the I/O cost and the temp space requirement.

The temp tablespace uses a special segment type called sort segments, which are fundamentally different from permanent data segments. Unlike permanent segments, which are individually created when an object is created and dropped when the object is dropped, sort segments are pre-allocated at instance startup as a pool and are reused across operations. Oracle does not create a new sort segment for each sort operation — instead, it allocates extents from the existing sort segment pool when an operation needs temp space and returns those extents to the pool when the operation completes. This pre-allocation design avoids the overhead of segment creation and deletion for each query and provides a pool of immediately available extents. The pool is managed at the tablespace level: each temporary tablespace has one sort segment, and the \`V\$SORT_SEGMENT\` view shows the current state of that pool, including total blocks, used blocks, free blocks, and — critically — the high-water mark (\`MAX_USED_BLOCKS\`) since instance startup.

The \`V\$SORT_SEGMENT\` and \`V\$TEMPSEG_USAGE\` views together provide a complete picture of temp space usage. \`V\$SORT_SEGMENT\` gives the aggregate pool state — total capacity, current usage, and peak usage since startup. \`V\$TEMPSEG_USAGE\` gives the per-session breakdown — which session (identified by \`SESSION_ADDR\`) holds how many temp blocks, for which operation type (SORT, HASH, LOB_DATA, etc.), and in which tablespace. The \`DBA_TEMP_FREE_SPACE\` view provides the DBA-level summary: total tablespace size, allocated space, and free space in a single row per tablespace, without requiring knowledge of the internal \`V\$\` view structure.

---

## PGA and Automatic Memory Management

The \`PGA_AGGREGATE_TARGET\` parameter sets the total PGA target for all server processes combined. Oracle's automatic PGA memory management — enabled when \`WORKAREA_SIZE_POLICY = AUTO\`, which is the default — distributes the available PGA budget among active work areas according to an internal allocation algorithm that tries to maximize the number of operations running optimally in memory. When many sessions are active simultaneously, each individual work area gets a smaller share of the PGA budget; when fewer sessions are active, individual operations can claim larger work areas and execute more of their work in memory.

The \`PGA_AGGREGATE_LIMIT\` parameter, introduced in Oracle 12c, establishes a hard ceiling on total PGA allocation across all server processes. If total PGA allocation reaches \`PGA_AGGREGATE_LIMIT\`, Oracle takes corrective action: it terminates the session consuming the most PGA if that session is performing a work area operation, or issues ORA-04036 to the session if it is not. \`PGA_AGGREGATE_LIMIT\` defaults to the greater of 2 GB or twice \`PGA_AGGREGATE_TARGET\`, and it should be set explicitly in production to a value that protects the OS from memory exhaustion due to runaway PGA consumption. A single poorly-written query executing a MULTI PASS sort on a very large data set can consume tens of gigabytes of PGA and temp space if nothing bounds it.

\`WORKAREA_SIZE_POLICY = AUTO\` enables automatic PGA management and is the only recommended mode for modern Oracle databases. The legacy alternative — \`WORKAREA_SIZE_POLICY = MANUAL\` with explicit \`SORT_AREA_SIZE\` and \`HASH_AREA_SIZE\` parameters — sets process-level limits and is inflexible: \`SORT_AREA_SIZE\` applies uniformly to every session regardless of how many are active or how complex their operations are. Under manual management, a DBA must choose between setting the work area large enough for the worst-case query (wasting memory when simpler operations run) or setting it small enough to be safe for concurrent execution (forcing temp spill for complex operations). Automatic management solves this trade-off dynamically.

Sizing \`PGA_AGGREGATE_TARGET\`: Oracle's general guidance is that OLTP workloads should allocate at least 20% of the system's total physical memory to PGA, while analytical or reporting databases that perform many large sorts and hash joins should allocate 50–70% of available memory to PGA. In practice, the most reliable sizing method is empirical: monitor \`V\$PGASTAT\` during representative workload periods and look at the \`cache hit percentage\` statistic. The cache hit percentage represents the fraction of work area operations that executed optimally (entirely in memory) or with at most a single temp spill pass. Oracle's recommended target is above 90% for OLTP workloads and above 80% for analytical workloads. If the cache hit percentage is consistently below target, \`PGA_AGGREGATE_TARGET\` should be increased in increments of 25–50% until the metric improves. The \`V\$PGASTAT\` view also shows \`total PGA inuse\`, \`total PGA allocated\`, and \`maximum PGA allocated\` — the maximum provides the peak demand figure that \`PGA_AGGREGATE_LIMIT\` should exceed with headroom.

---

## Temp Tablespace Groups

A temp tablespace group is a named collection of temporary tablespaces that can be assigned to users or set as the database default temporary tablespace. When a user is assigned to a temp tablespace group, Oracle distributes temp allocations across the member tablespaces in round-robin fashion — each new sort segment allocation goes to the next tablespace in the group. This provides two benefits: aggregate capacity that exceeds what a single tablespace can offer, and I/O parallelism when the member tablespaces reside on different storage devices or storage paths.

Temp tablespace groups are particularly valuable in parallel query environments. A parallel query with degree-of-parallelism 32 spawns 32 parallel server processes, each of which may independently need temp space. If all 32 slaves allocate from the same temp tablespace backed by a single set of datafiles on the same storage, those 32 I/O streams compete for the same physical I/O bandwidth. By distributing the temp tablespace across a group with multiple member tablespaces on separate storage, the I/O load is spread across multiple physical paths and the aggregate throughput scales accordingly.

In Oracle RAC environments, each instance typically uses its own local temp tablespace — the allocation model for temp space in RAC mirrors the per-instance model used for undo tablespaces. Temp tablespace groups can span RAC instances, but I/O efficiency is better served by local allocation. When a PDB in a CDB is assigned to a temp tablespace group, the group must be defined within the PDB's context; PDB-level temp tablespace groups do not share membership with CDB\$ROOT's groups.

The database default temporary tablespace — set via \`ALTER DATABASE DEFAULT TEMPORARY TABLESPACE\` — is assigned to any user whose \`CREATE USER\` statement did not include a \`TEMPORARY TABLESPACE\` clause, and to any user whose assigned temp tablespace is subsequently dropped. Getting this default right is critical: if no default is explicitly set, Oracle may assign users to the SYSTEM tablespace as their temp tablespace. An Oracle installation should always have an explicitly named default temporary tablespace, and that tablespace should never be SYSTEM. Assigning DML-heavy or analytic users to a temp tablespace group rather than a single tablespace is the most straightforward capacity scaling mechanism available.

---

## Global Temporary Tables

Global temporary tables (GTTs) store session-private or transaction-private data in the temp tablespace. They are created with standard DDL (\`CREATE GLOBAL TEMPORARY TABLE\`) and appear in the data dictionary permanently — the table definition persists, but the data does not. There are two retention modes: \`ON COMMIT DELETE ROWS\` causes all rows to be deleted at the end of each transaction, while \`ON COMMIT PRESERVE ROWS\` retains rows for the lifetime of the session and truncates the table when the session ends. GTT data is always session-private: session A's rows are invisible to session B even if both sessions insert into the same GTT simultaneously.

Because GTT data lives in the temp tablespace, it consumes temp space and must be accounted for in temp tablespace sizing. A GTT-heavy application that accumulates millions of rows per session in ON COMMIT PRESERVE ROWS tables can exhaust the temp tablespace just as effectively as a large sort operation. The \`V\$TEMPSEG_USAGE\` view distinguishes GTT allocations from sort and hash allocations via the \`SEGTYPE\` column — \`DATA\` indicates a GTT data segment rather than \`SORT\` or \`HASH\`. Monitoring GTT-sourced temp consumption alongside sort and hash usage is necessary for accurate temp tablespace sizing.

GTT statistics management was problematic prior to Oracle 12c. Because GTT data is transient, the CBO's statistics for a GTT reflected whatever data was present when statistics were last gathered — which might be zero rows (if gathered immediately after session end) or an arbitrary session's data. If row counts vary dramatically between sessions (session A uses the GTT for 10 rows, session B uses it for 10 million rows), a single set of shared statistics produces wildly inappropriate query plans for at least one of them. Oracle 12c introduced session-private statistics for GTTs, enabled via \`DBMS_STATS.SET_TABLE_PREFS(schema, table_name, 'GLOBAL_TEMP_TABLE_STATS', 'SESSION')\`. With session-private statistics, each session gathers and uses its own statistics for the GTT, producing optimal plans based on that session's actual data volume.

Direct-path reads from GTTs — particularly in analytic contexts — bypass the buffer cache entirely. Because GTT data is never shared between sessions, there is no cache benefit from storing GTT blocks in the shared buffer cache, and Oracle's direct-path read mechanism reads GTT data directly into the PGA, reducing buffer cache pressure. This makes GTT I/O performance dependent on the speed of the temp tablespace storage: fast NVMe or SAN storage benefits GTT workloads directly. For very large GTTs where buffer cache overhead would otherwise be significant, the direct-path read behaviour is a feature rather than a limitation.

---

## Sorting Without Spilling: Tuning Strategies

The primary tool for eliminating temp spill is increasing \`PGA_AGGREGATE_TARGET\`. If the cache hit percentage in \`V\$PGASTAT\` is consistently below target and temp I/O is measurably impacting query performance, more PGA is the most direct fix. The limiting factor is available physical memory — if the system's memory is already fully committed to SGA, OS, and other processes, increasing PGA requires either adding memory to the server or reducing the SGA. In Oracle 12c Multitenant and later, Memory Manager can help with automatic PGA/SGA balancing when \`MEMORY_TARGET\` is in use, but its granularity may not be sufficient for precise tuning in high-concurrency environments.

Beyond PGA sizing, index-based strategies can eliminate sorts at the SQL level entirely. An ORDER BY clause whose column list exactly matches an available index's key columns — in the same order and direction — allows Oracle to satisfy the sort via an index range scan or full scan, reading data in already-sorted order without any sort operation. Covering indexes that include all columns referenced in a GROUP BY clause allow the optimizer to use a sort-group-by algorithm that reads groups directly from the index without materializing an intermediate sort set. These approaches require index changes — but they eliminate the sort operation rather than merely reducing its cost, making them preferable to PGA tuning when the query pattern is stable and the index overhead is acceptable.

Rewriting correlated subqueries as analytic functions often reduces the intermediate data set that must be sorted. A correlated subquery that computes a window function equivalent (running totals, rankings, row comparisons) typically forces the optimizer to execute the subquery multiple times, often with sort operations on each invocation. Rewriting with \`ROW_NUMBER()\`, \`RANK()\`, \`LAG()\`, \`LEAD()\`, or \`SUM() OVER ()\` allows Oracle to sort the data set once and compute the window function in a single pass. Analytic functions are among the most powerful tools in the DBA's SQL optimization toolkit specifically because they replace repeated subquery executions with single-pass operations.

For parallel query workloads, the interaction between PGA and temp space is multiplicative. A query executing at degree-of-parallelism 64 effectively requires 64× the per-slave PGA for in-memory execution: each of the 64 parallel server processes has its own work area, and each work area must fit its share of the data in memory to avoid spilling. On a system where \`PGA_AGGREGATE_TARGET\` is 8 GB, 64 parallel slaves each get approximately 128 MB of work area — adequate for modest operations but insufficient for sorting hundreds of millions of rows. Monitoring per-SQL work area usage via \`V\$SQL_WORKAREA\` is essential in parallel environments: the \`LAST_EXECUTION\` column shows whether the most recent execution of each work area was OPTIMAL (entirely in memory), ONE PASS (single temp spill), or MULTI PASS (multiple temp passes). \`MULTI PASS\` operations represent a critical finding — they indicate the work area was severely undersized relative to the data volume and the associated temp I/O is multiplied by the degree of parallelism.

---

## Temp Tablespace Sizing and ORA-01652

Sizing the temp tablespace does not have the same formula-driven precision as undo tablespace sizing because temp usage depends on two variables that can only be measured empirically: concurrent query concurrency (how many sessions are simultaneously performing large sorts or hash joins) and peak data volume per operation (how much data the largest individual operations process). The practical approach is to instrument the production system during peak load.

The key data source is the high-water mark in \`V\$SORT_SEGMENT\`: the \`MAX_USED_BLOCKS\` column records the maximum number of temp blocks allocated simultaneously since the instance started. This is the definitive peak usage figure — not an estimate, but an actual measurement of peak demand. Converting to gigabytes: \`MAX_USED_BLOCKS * db_block_size / 1073741824\`. The standard recommendation is to size the temp tablespace to at least 150% of this high-water mark — the 50% buffer accommodates future workload growth, new queries that may require more temp space than currently observed, and parallel query expansion. The \`DBA_TEMP_FREE_SPACE\` view provides the current free and used temp space in a single query and is the fastest way to check real-time temp space status.

ORA-01652 "unable to extend temp segment" occurs in three distinct scenarios. First, the temp tablespace is genuinely undersized for the workload — the high-water mark is approaching or exceeds the tablespace's capacity. In this case, adding a temp datafile (or extending an existing one) immediately resolves the error and buys time for permanent resizing. Second, a runaway query is consuming all available temp space while concurrent sessions need their share — a single poorly-optimized sort or cross join that generates hundreds of gigabytes of temp usage will starve concurrent sessions. Check \`V\$TEMPSEG_USAGE\` sorted by blocks descending to identify the offending session and its \`SQL_ID\`; killing the session (after confirming with the user) releases the temp space immediately. Third, temp datafiles are not configured for autoextend, or they have hit their \`MAXSIZE\` limit — the tablespace cannot physically expand even though additional space exists on the underlying storage.

The space reclaim mechanism for temp tablespace is passive: Oracle returns temp extents to the sort segment pool when a session's sort or hash operation completes, not when the session disconnects. Sort segments are maintained at the tablespace level — the sort segment for a temp tablespace persists as long as any session is using it, and its total pre-allocated size does not shrink automatically. Shrinking the temp tablespace to reclaim space requires waiting until all sort segments are inactive (current users = 0 in \`V\$SORT_SEGMENT\`), then executing \`ALTER TABLESPACE temp SHRINK SPACE KEEP <n>G\` to reduce the allocated size while retaining a minimum reserve.

---

## Temp in CDB/PDB Architecture

In Oracle's multitenant Container Database (CDB) architecture, each PDB maintains its own independent temporary tablespace (or tablespace group). Unlike undo management, which had a "shared undo" mode in Oracle 12c that all PDBs shared the CDB's undo tablespace, temp tablespace has always been PDB-private: there is no concept of a shared temp tablespace that spans PDBs. Each PDB allocates its own sort segments in its own temp tablespace, and temp space consumption in one PDB cannot directly cause ORA-01652 in another PDB.

The CDB\$ROOT itself has its own temp tablespace, used by sessions connected to the root container. Administrative operations performed at the CDB level — such as cross-container queries using \`CONTAINERS()\` or large CDB-level administrative sorts — use the CDB\$ROOT's temp tablespace. Most production workload occurs in PDBs, so the CDB\$ROOT's temp tablespace is typically small. However, if CDB-level maintenance operations are expected to perform large sorts (for example, \`DBMS_STATS\` cross-PDB runs or large CDB-level data exports), the CDB\$ROOT's temp tablespace should be sized appropriately.

Provisioning temp tablespace per PDB requires knowledge of the PDB's intended workload. A PDB hosting an OLTP application with simple queries and small result sets needs only a modest temp tablespace — perhaps 4–8 GB. A PDB hosting a data warehouse or reporting application with complex multi-table joins, GROUP BY operations on billions of rows, and parallel query execution may need hundreds of gigabytes of temp space. The correct approach is to provision PDBs with a reasonable default and monitor \`V\$SORT_SEGMENT\` (queried while connected to the PDB's container) during representative load tests or during the first production load cycle, using the \`MAX_USED_BLOCKS\` high-water mark to establish the correct sizing.

The \`CDB_TEMP_FREE_SPACE\` view, queryable from \`CDB\$ROOT\` by a privileged user, provides a cross-PDB view of temp space usage — one row per PDB per temp tablespace, showing total size, allocated space, and free space. This is the correct monitoring point for a DBA managing a multi-PDB CDB: a single query against \`CDB_TEMP_FREE_SPACE\` shows every PDB's temp space status, and any PDB approaching capacity can be identified and addressed before ORA-01652 occurs in production.

---

## Summary

Oracle's temporary tablespace is the disk-based fallback for SQL operations that cannot complete entirely within the PGA work area. The sort segment architecture — pre-allocated at instance startup and reused across operations as a pool — makes temp allocation efficient, but the I/O cost of temp spill is always significantly higher than the equivalent in-memory execution. The path from data to result for a sort operation is: data read from the object → PGA work area → (if insufficient PGA) sorted runs written to temp → sorted runs merged from temp → result returned. Every additional step in this chain is I/O that could be avoided with more PGA.

The OPTIMAL → ONE PASS → MULTI PASS execution model in \`V\$SQL_WORKAREA\` provides a precise, per-SQL measurement of how well the PGA is sized relative to the workload. OPTIMAL executions require no temp I/O. ONE PASS executions require a single write and read cycle to temp — expensive but manageable. MULTI PASS executions require multiple write/read cycles and represent a serious performance problem: not only is the I/O multiplied, but the temp space consumed is also multiplied. Any SQL in \`V\$SQL_WORKAREA\` with \`LAST_EXECUTION = 'MULTI PASS'\` requires immediate investigation — either PGA is dramatically undersized relative to the operation's data volume, or the SQL is consuming resources disproportionate to its business purpose.

PGA_AGGREGATE_TARGET is the most powerful lever for reducing temp tablespace I/O. Sizing it correctly requires empirical measurement: monitor the cache hit percentage in \`V\$PGASTAT\` during representative workload periods and increase the parameter until the percentage exceeds the target threshold (90% OLTP, 80% analytical). The PGA_AGGREGATE_LIMIT hard cap, available from Oracle 12c, is the essential companion parameter that prevents runaway PGA growth from exhausting OS memory when a complex operation or a poorly optimized query escalates to MULTI PASS execution.

Temp tablespace groups provide capacity and I/O parallelism for environments where a single temp tablespace would become an I/O bottleneck, particularly in high-degree parallel query workloads. Global temporary tables store session-private data in temp space and require their own capacity allocation in the temp tablespace sizing analysis — particularly when ON COMMIT PRESERVE ROWS semantics cause GTT data to accumulate across many transactions within a session. The correct mental model is that the temp tablespace is an extension of the PGA onto disk: when PGA is adequate, the temp tablespace is barely touched; when PGA is insufficient, the temp tablespace must absorb the overflow and its I/O capacity becomes the performance ceiling. The most effective temp tablespace "tuning" is PGA tuning — if PGA is sized correctly for the workload, temp I/O becomes the exception rather than the routine cost of query execution.`,
};

async function main() {
  console.log('Inserting Oracle Temp Tablespace concept post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: { ...post },
  });
  console.log('Inserted: "' + post.title + '"');
}

main().catch(console.error);
