import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';

const slug = 'rman-backup-strategy-oracle-rac-database';

const content = `
RMAN backups on a single-instance Oracle database involve a single set of archive logs, a single set of datafiles, and a single host where channels run. On a RAC database, every one of those assumptions changes: archive logs are generated by multiple instances simultaneously, channels can be allocated on any node in the cluster, ASM disk group accessibility depends on which node a channel runs on, and a poorly designed backup script can silently produce an incomplete archive log sequence that will fail at recovery time.

This post covers the architectural differences that make RAC backup distinct, the channel allocation strategies that determine where backup work runs, archive log management across multiple instances, the RMAN configuration parameters that matter most in a cluster, ASM-specific considerations, and the complete backup scripts for full, incremental, and archive log backup strategies.

---

## How RAC Changes the RMAN Landscape

In a single-instance database, RMAN's task is straightforward: connect to the one instance, allocate channels on the one host, and back up all the files.

In a RAC database, the same logical database runs across multiple instances simultaneously. Each instance has its own SGA, its own background processes, and generates its own stream of redo and archive logs. All instances write to the same set of datafiles in the shared ASM disk group, but each instance's archive logs are distinct — they carry a thread number corresponding to the instance that generated them.

This creates several backup requirements that do not exist in a single-instance environment:

**All archive log threads must be backed up.** A 4-node RAC generates thread 1, thread 2, thread 3, and thread 4 archive logs. A restore and recovery operation requires all threads to be present up to the desired recovery point. If RMAN only backed up threads 1 and 3, recovery would stall waiting for thread 2 and thread 4 logs that are not in the backup set.

**Channels run on specific nodes, and which node matters.** An RMAN channel is a server process that runs on the database host. In a RAC cluster with nodes A, B, C, and D, channels allocated without explicit node binding can run on any of the four nodes. This affects which mount points and which network paths are accessible to the channel.

**ASM archive log location differs by instance configuration.** If the database uses a Fast Recovery Area in ASM (the common case), archive logs from all threads are written to the shared ASM disk group and are accessible from any node. If archive logs are written to a local filesystem path, each node's logs are only accessible from that specific node, and the channel that backs them up must run on the same node.

**RMAN catalog is strongly recommended for RAC.** Without a recovery catalog, RMAN backup metadata is stored in the target database control file. In a RAC environment where multiple instances share the control file, this works but the catalog provides cross-database visibility, stored scripts, and a history that survives control file recreation — all of which become more important in a multi-instance environment.

---

## Archive Log Threading in RAC

Each RAC instance is assigned a thread number. Thread 1 is typically instance 1, thread 2 is instance 2, and so on. The thread number is embedded in the archive log filename and in the \`V$ARCHIVED_LOG\` view.

\`\`\`sql
-- View archive logs by thread on a 4-node RAC
SELECT thread#,
       sequence#,
       name,
       archived,
       status,
       TO_CHAR(completion_time, 'YYYY-MM-DD HH24:MI:SS') AS completed
FROM   v\$archived_log
WHERE  standby_dest = 'NO'
ORDER  BY thread#, sequence#;
\`\`\`

The critical field is \`THREAD#\`. A complete backup of archived logs must cover every thread from the last SCN present in the backup to the SCN at which recovery ends. Missing a single sequence in any thread produces an ORA-00308 or ORA-00280 during recovery.

\`\`\`sql
-- Identify any gap in archive log sequences per thread
SELECT thread#,
       MIN(sequence#) AS first_seq,
       MAX(sequence#) AS last_seq,
       COUNT(*)       AS log_count,
       MAX(sequence#) - MIN(sequence#) + 1 AS expected_count,
       CASE WHEN COUNT(*) = MAX(sequence#) - MIN(sequence#) + 1
            THEN 'COMPLETE' ELSE 'GAP' END AS status
FROM   v\$archived_log
WHERE  standby_dest = 'NO'
AND    status       = 'A'
GROUP  BY thread#
ORDER  BY thread#;
\`\`\`

---

## Channel Allocation Strategies

### Automatic Allocation

When no explicit channels are defined in a RUN block, RMAN uses the configured default channel settings. In a RAC environment, automatic channel allocation without configuration produces channels that run on whichever node the target instance connection reaches. This is unpredictable and can cause issues if archive logs are on local filesystems.

For ASM-based archives, automatic allocation works correctly as long as all nodes can access the ASM disk groups — which is the normal configuration for a properly built RAC cluster.

### Explicit Node-Specific Allocation

For controlled, predictable backup execution, channels can be bound to specific RAC instances using the \`CONNECT\` clause or by connecting to specific instances. The common approach is to allocate channels through the RAC database service and let Oracle route them, or to explicitly target specific instances using the instance name:

\`\`\`text
RUN {
  -- Channels allocated across two nodes for parallelism
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK
    CONNECT 'sys/password@RACDB1';

  ALLOCATE CHANNEL c2 DEVICE TYPE DISK
    CONNECT 'sys/password@RACDB2';

  ALLOCATE CHANNEL c3 DEVICE TYPE DISK
    CONNECT 'sys/password@RACDB3';

  ALLOCATE CHANNEL c4 DEVICE TYPE DISK
    CONNECT 'sys/password@RACDB4';

  BACKUP DATABASE PLUS ARCHIVELOG;
}
\`\`\`

Where \`RACDB1\` through \`RACDB4\` are TNS aliases that connect to individual instance SIDs (not the database service). This distributes backup I/O across all nodes and all HBAs simultaneously.

### Single-Node Backup for Simplicity

For many environments, the simplest and most maintainable approach is to run all backup channels from a single designated node — typically the node where the cron job or OEM job runs. This eliminates the complexity of cross-node channel management while still producing a complete, valid backup.

\`\`\`text
RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c3 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c4 DEVICE TYPE DISK MAXPIECESIZE 32G;

  BACKUP AS COMPRESSED BACKUPSET
    INCREMENTAL LEVEL 0
    DATABASE
    FORMAT '/backup/RACDB/db_%d_%T_%U.bkp'
    TAG 'WEEKLY_FULL';

  BACKUP ARCHIVELOG ALL
    FORMAT '/backup/RACDB/arch_%d_%T_%s_%p.bkp'
    TAG 'ARCH_FULL'
    DELETE INPUT;

  BACKUP CURRENT CONTROLFILE
    FORMAT '/backup/RACDB/ctl_%d_%T_%U.bkp';

  BACKUP SPFILE
    FORMAT '/backup/RACDB/spf_%d_%T_%U.bkp';
}
\`\`\`

This runs entirely on the node where RMAN executes. The \`BACKUP ARCHIVELOG ALL\` clause queries \`V\$ARCHIVED_LOG\` which is a cluster-wide view on any RAC node — it sees all threads. The channels then fetch the logs from their ASM locations regardless of which thread generated them.

---

## RMAN Configuration for RAC

RMAN persistent configuration is stored per database. On a RAC database, configuration is shared across all instances through the control file.

### Key Parameters to Configure

\`\`\`text
-- Connect to any RAC instance and configure globally
CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 14 DAYS;
CONFIGURE BACKUP OPTIMIZATION ON;
CONFIGURE DEFAULT DEVICE TYPE TO DISK;
CONFIGURE CONTROLFILE AUTOBACKUP ON;
CONFIGURE CONTROLFILE AUTOBACKUP FORMAT FOR DEVICE TYPE DISK
  TO '/backup/RACDB/cf_%F';
CONFIGURE COMPRESSION ALGORITHM 'BASIC';
CONFIGURE ARCHIVELOG DELETION POLICY TO BACKED UP 2 TIMES TO DISK;
\`\`\`

**\`CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 14 DAYS\`** — RMAN will keep enough backups to recover to any point in time within the past 14 days. Backups older than the window become obsolete and can be deleted with \`DELETE OBSOLETE\`.

**\`CONFIGURE BACKUP OPTIMIZATION ON\`** — RMAN skips backing up files that are already backed up to the same device and have not changed since the last backup. In a RAC environment this is particularly useful for archive log backups: if a log was already backed up by a previous job, it will not be backed up again.

**\`CONFIGURE CONTROLFILE AUTOBACKUP ON\`** — Automatically creates a control file and SPFILE backup after every RMAN backup or structural change. Essential for any database but especially important in RAC where the control file is the single source of cluster membership and redo thread registration.

**\`CONFIGURE ARCHIVELOG DELETION POLICY TO BACKED UP 2 TIMES TO DISK\`** — Archive logs will not be deleted by RMAN (or eligible for deletion by ASM) until they have been backed up at least twice. This provides a safety margin: if one backup job fails, the logs remain available for the next job. Adjust the count to match your backup frequency and disk space constraints.

### Parallelism Configuration

\`\`\`text
-- Set default parallelism to match node count
CONFIGURE DEVICE TYPE DISK PARALLELISM 4 BACKUP TYPE TO BACKUPSET;
\`\`\`

This configures 4 default channels when no explicit channel allocation is present. Adjust to the number of nodes times the number of channels per node you want running concurrently.

---

## ASM Considerations for RMAN Backup

### Backing Up to ASM

RMAN can write backup pieces directly to ASM disk groups. This is useful when a centralized ASM disk group is used as a Fast Recovery Area:

\`\`\`text
CONFIGURE DEFAULT DEVICE TYPE TO DISK;
CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '+RECO/%d_%T_%U.bkp';
\`\`\`

The Fast Recovery Area in ASM is accessible from all nodes simultaneously, so backup pieces written by channels on node 1 can be read by channels on node 3 during a restore — there is no node affinity for ASM backup pieces.

### Fast Recovery Area in ASM

When \`DB_RECOVERY_FILE_DEST\` points to an ASM disk group, Oracle manages backup retention automatically through the FRA space management:

\`\`\`sql
-- Check FRA space usage
SELECT name,
       space_limit / 1024 / 1024 / 1024    AS limit_gb,
       space_used / 1024 / 1024 / 1024     AS used_gb,
       space_reclaimable / 1024 / 1024 / 1024 AS reclaimable_gb,
       number_of_files
FROM   v\$recovery_file_dest;
\`\`\`

When the FRA reaches 85% capacity, Oracle issues a warning in the alert log. At 100%, archive log generation will stall — all threads halt because no instance can write new archive logs. On a 4-node RAC, a full FRA ASM disk group stalls all four instances simultaneously.

Monitor FRA usage as part of a standard RAC health check:

\`\`\`sql
-- FRA usage per file type
SELECT file_type,
       percent_space_used,
       percent_space_reclaimable,
       number_of_files
FROM   v\$recovery_area_usage
ORDER  BY percent_space_used DESC;
\`\`\`

### Archive Logs on Local Filesystems

If archive logs are written to local OS paths (not ASM), each node's archive logs reside only on that node's filesystem. In this configuration:

- The channel that backs up thread N must run on node N
- RMAN's automatic channel allocation will fail silently or incompletely
- Explicit per-node channel allocation with node-specific \`CONNECT\` strings is mandatory

This configuration is increasingly rare in modern RAC deployments because ASM is the standard storage layer, but it exists in legacy environments built before Automatic Storage Management was mature.

Verify the archive log destination type:

\`\`\`sql
SELECT dest_id,
       target,
       archiver,
       status,
       destination
FROM   v\$archive_dest
WHERE  status = 'VALID'
AND    target = 'PRIMARY';
\`\`\`

If \`DESTINATION\` begins with \`+\`, the logs go to ASM. If it begins with \`/\`, they go to a local filesystem on each node.

---

## Complete Backup Scripts

### Weekly Full (Level 0) + Daily Incremental Strategy

The most common RAC backup strategy uses a Level 0 on Sunday and Level 1 differentials Monday through Saturday, with archive log backups running every 2–4 hours independently.

**Weekly Level 0 — rman_level0.rman**

\`\`\`text
RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK MAXPIECESIZE 64G;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK MAXPIECESIZE 64G;
  ALLOCATE CHANNEL c3 DEVICE TYPE DISK MAXPIECESIZE 64G;
  ALLOCATE CHANNEL c4 DEVICE TYPE DISK MAXPIECESIZE 64G;

  BACKUP AS COMPRESSED BACKUPSET
    INCREMENTAL LEVEL 0
    DATABASE
    FORMAT '/backup/RACDB/%d_L0_%T_%U.bkp'
    TAG 'WEEKLY_LEVEL0';

  BACKUP AS COMPRESSED BACKUPSET
    ARCHIVELOG ALL
    NOT BACKED UP 1 TIMES
    FORMAT '/backup/RACDB/%d_arch_%T_%s_%p.bkp'
    TAG 'ARCH_WITH_L0'
    DELETE INPUT;

  BACKUP CURRENT CONTROLFILE
    FORMAT '/backup/RACDB/%d_ctl_%T_%U.bkp'
    TAG 'CTL_WITH_L0';

  BACKUP SPFILE
    FORMAT '/backup/RACDB/%d_spf_%T_%U.bkp'
    TAG 'SPF_WITH_L0';

  DELETE NOPROMPT OBSOLETE;
}
\`\`\`

**Daily Level 1 Differential — rman_level1.rman**

\`\`\`text
RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c3 DEVICE TYPE DISK MAXPIECESIZE 32G;
  ALLOCATE CHANNEL c4 DEVICE TYPE DISK MAXPIECESIZE 32G;

  BACKUP AS COMPRESSED BACKUPSET
    INCREMENTAL LEVEL 1
    DATABASE
    FORMAT '/backup/RACDB/%d_L1_%T_%U.bkp'
    TAG 'DAILY_LEVEL1';

  BACKUP AS COMPRESSED BACKUPSET
    ARCHIVELOG ALL
    NOT BACKED UP 1 TIMES
    FORMAT '/backup/RACDB/%d_arch_%T_%s_%p.bkp'
    TAG 'ARCH_WITH_L1'
    DELETE INPUT;

  BACKUP CURRENT CONTROLFILE
    FORMAT '/backup/RACDB/%d_ctl_%T_%U.bkp'
    TAG 'CTL_WITH_L1';

  DELETE NOPROMPT OBSOLETE;
}
\`\`\`

**Frequent Archive Log Backup — rman_archivelog.rman (runs every 2 hours)**

\`\`\`text
RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK MAXPIECESIZE 16G;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK MAXPIECESIZE 16G;

  BACKUP AS COMPRESSED BACKUPSET
    ARCHIVELOG ALL
    NOT BACKED UP 1 TIMES
    FORMAT '/backup/RACDB/%d_arch_%T_%s_%t_%p.bkp'
    TAG 'ARCH_FREQ'
    DELETE INPUT;
}
\`\`\`

The \`NOT BACKED UP 1 TIMES\` clause prevents re-backing-up logs already covered by a previous job. The \`DELETE INPUT\` removes from ASM only the archive logs that were successfully included in this backup set — logs not yet backed up are untouched.

### Archive Log Backup Across All RAC Threads — Verification

After any archive log backup, confirm all threads were captured:

\`\`\`sql
-- Verify all threads have recent backups
SELECT b.thread#,
       b.sequence#,
       b.first_change#,
       b.next_change#,
       TO_CHAR(b.completion_time, 'YYYY-MM-DD HH24:MI:SS') AS backed_up_at,
       b.status
FROM   v\$backup_archivelog_details b
WHERE  b.completion_time >= SYSDATE - 1
ORDER  BY b.thread#, b.sequence#;
\`\`\`

\`\`\`sql
-- Identify archive logs present but NOT yet backed up
SELECT thread#,
       sequence#,
       name,
       TO_CHAR(completion_time, 'YYYY-MM-DD HH24:MI:SS') AS completed
FROM   v\$archived_log
WHERE  standby_dest = 'NO'
AND    status       = 'A'
AND    backed_up    = 0
ORDER  BY thread#, sequence#;
\`\`\`

If any thread shows unbacked-up logs that should have been captured by the most recent job, the archive log backup did not reach those sequences. This can indicate a channel that failed mid-job, a thread that was not active at backup time, or a log destination configuration issue.

---

## Multiplexed Control File Backup

The control file records the database structure, redo thread registrations, and RMAN backup metadata. In RAC, all instances share the same control file (mirrored copies). RMAN always backs up the control file as a consistent snapshot regardless of which node the channel runs on.

With \`CONFIGURE CONTROLFILE AUTOBACKUP ON\`, RMAN creates a control file backup automatically at the end of every backup job and after structural changes (\`CREATE TABLESPACE\`, \`ADD DATAFILE\`, etc.). The autobackup uses the format tag \`%F\` which encodes the DBID and timestamp and is self-contained — RMAN can locate it without a catalog using \`SET DBID\`.

\`\`\`text
-- Manual control file backup on demand
BACKUP CURRENT CONTROLFILE FORMAT '/backup/RACDB/cf_manual_%F';

-- Restore control file without catalog (disaster recovery scenario)
SET DBID 1234567890;
RESTORE CONTROLFILE FROM '/backup/RACDB/cf_manual_c-1234567890-20260715-00';
\`\`\`

---

## RMAN Recovery Catalog in a RAC Environment

A recovery catalog is a schema in a separate database (typically a standalone instance or a dedicated catalog database) that stores RMAN backup metadata for one or more target databases.

### Why the Catalog is More Important for RAC

- **Stored scripts**: backup scripts can be stored in the catalog and executed by name (\`EXECUTE SCRIPT weekly_backup\`), ensuring all nodes use identical backup logic
- **Cross-database reporting**: \`LIST BACKUP OF DATABASE\` from the catalog shows backups across all registered databases, useful when managing multiple RAC clusters
- **Control file independence**: if the target database control file is lost or corrupted, the catalog retains the complete backup history — critical when the control file autobackup path is also unreachable
- **Long-term retention**: the catalog can store backup records beyond the control file's record retention limit

### Catalog Registration and Maintenance

\`\`\`bash
# Register a RAC database with the catalog
rman target sys@RACDB catalog rman_owner@CATALOG

RMAN> REGISTER DATABASE;
RMAN> RESYNC CATALOG;
\`\`\`

\`RESYNC CATALOG\` synchronises the catalog with the target database control file — picks up new backups, datafiles, and incarnation records. Run it at the end of every backup job to keep the catalog current:

\`\`\`text
# Add to end of backup scripts
RESYNC CATALOG;
\`\`\`

---

## Backup Validation Without Restoring

RMAN can validate backup integrity without actually restoring files. This confirms backup pieces are readable and block checksums are valid — use it as a routine health check after each backup window.

\`\`\`text
-- Validate the most recent Level 0 backup (no restore, checks only)
RESTORE DATABASE VALIDATE;

-- Validate a specific backup piece
VALIDATE BACKUPSET 142;

-- Validate archive logs for a specific time range
RESTORE ARCHIVELOG FROM TIME 'SYSDATE-2' UNTIL TIME 'SYSDATE' VALIDATE;
\`\`\`

\`RESTORE ... VALIDATE\` reads every block from the backup set, verifies block checksums, and reports corrupt blocks — but does not write any files. The result appears in \`V\$RESTORE_POINT\` and is also logged to the RMAN log. Any corruption found here means the backup cannot be used to recover the affected blocks.

---

## Recovery Scenarios Specific to RAC

### Single Node Failure — All Other Nodes Running

If one RAC node fails, the cluster automatically evicts it (OPROCD, CSSD fence). The surviving instances perform crash recovery on the failed instance's redo threads automatically — no DBA action required. The database remains open and accessible through the surviving nodes.

Recovery from backup is not needed unless the node that failed had datafiles on a local filesystem path (atypical), or the failure caused ASM disk group dismount (rare, indicates storage path issue rather than node failure).

### All Nodes Down — Database Crash

If all nodes go down simultaneously (power failure, cluster network split resulting in all-node fence), the database requires crash recovery on startup. RMAN backup is not involved — Oracle applies the redo logs automatically when any instance mounts the database.

If the crash resulted in a corrupt control file or corrupted datafiles, RMAN recovery is needed:

\`\`\`text
-- Mount any single instance in the cluster for recovery
STARTUP MOUNT;

-- Restore and recover
RESTORE DATABASE;
RECOVER DATABASE;

ALTER DATABASE OPEN RESETLOGS;
\`\`\`

After \`RESETLOGS\`, register the new database incarnation with the catalog:

\`\`\`text
RESET DATABASE TO INCARNATION <new_incarnation_number>;
RESYNC CATALOG;
\`\`\`

### Point-in-Time Recovery (PITR)

PITR on RAC requires all archive log threads to be available up to the target SCN:

\`\`\`text
RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK;

  -- Set a consistent SCN or timestamp target
  SET UNTIL SCN 9876543210;

  RESTORE DATABASE;

  -- Recover applies all archive logs from all threads up to the target SCN
  RECOVER DATABASE;
}

ALTER DATABASE OPEN RESETLOGS;
\`\`\`

RMAN coordinates archive log application across all threads automatically during the \`RECOVER DATABASE\` step — it determines which sequences from which threads are needed to reach the target SCN and applies them in the correct order.

### Tablespace Point-in-Time Recovery (TSPITR)

TSPITR recovers one or more tablespaces to a point in the past while the rest of the database remains at the current SCN. This is useful for recovering from logical corruption (dropped tables, bad batch loads) that affected only a subset of tablespaces.

\`\`\`text
-- TSPITR requires the tablespace to be taken offline first
ALTER TABLESPACE sales_data OFFLINE IMMEDIATE;

RUN {
  ALLOCATE CHANNEL c1 DEVICE TYPE DISK;
  ALLOCATE CHANNEL c2 DEVICE TYPE DISK;

  SET UNTIL TIME "TO_DATE('2026-07-14 22:00:00','YYYY-MM-DD HH24:MI:SS')";

  RESTORE TABLESPACE sales_data;
  RECOVER TABLESPACE sales_data;
}

ALTER TABLESPACE sales_data ONLINE;
\`\`\`

On RAC, TSPITR must be run with all instances except one mounted or shut down, or the tablespace must be offline on all instances before the restore begins. Attempting TSPITR while the tablespace is online on any surviving RAC instance will fail.

---

## Monitoring Backup Jobs

### Real-Time Progress

\`\`\`sql
-- Running RMAN sessions and their current activity
SELECT s.sid,
       s.serial#,
       p.spid,
       s.username,
       s.program,
       s.status,
       s.sql_id,
       TO_CHAR(s.logon_time, 'HH24:MI:SS') AS logon_time
FROM   v\$session s
JOIN   v\$process p ON s.paddr = p.addr
WHERE  s.program LIKE '%rman%'
OR     s.module LIKE '%rman%'
ORDER  BY s.logon_time;
\`\`\`

\`\`\`sql
-- RMAN backup job progress from V\$RMAN_STATUS
SELECT row_type,
       operation,
       status,
       TO_CHAR(start_time, 'YYYY-MM-DD HH24:MI:SS') AS started,
       TO_CHAR(end_time,   'YYYY-MM-DD HH24:MI:SS') AS ended,
       mbytes_processed,
       output_device_type
FROM   v\$rman_status
WHERE  start_time >= SYSDATE - 1
ORDER  BY start_time DESC;
\`\`\`

### Backup History Summary

\`\`\`sql
-- Last 7 days of backup jobs: status and size
SELECT TO_CHAR(start_time, 'YYYY-MM-DD') AS backup_date,
       input_type,
       status,
       ROUND(input_bytes  / 1024 / 1024 / 1024, 1) AS input_gb,
       ROUND(output_bytes / 1024 / 1024 / 1024, 1) AS output_gb,
       ROUND(output_bytes / input_bytes * 100, 1)   AS compression_pct,
       ROUND((end_time - start_time) * 24 * 60, 0)  AS duration_min
FROM   v\$rman_backup_job_details
WHERE  start_time >= SYSDATE - 7
ORDER  BY start_time DESC;
\`\`\`

### Verify All Archive Log Threads are Covered

Run this after every archive log backup to confirm no threads were missed:

\`\`\`sql
-- Archive logs backed up in the last 4 hours, by thread
SELECT b.thread#,
       MIN(b.sequence#)  AS first_seq,
       MAX(b.sequence#)  AS last_seq,
       COUNT(*)          AS logs_backed_up,
       TO_CHAR(MAX(b.completion_time), 'YYYY-MM-DD HH24:MI:SS') AS most_recent
FROM   v\$backup_archivelog_details b
WHERE  b.completion_time >= SYSDATE - 4/24
GROUP  BY b.thread#
ORDER  BY b.thread#;
\`\`\`

If any RAC thread number is absent from this output, archive logs for that instance were not captured in the most recent backup job. Check whether the instance was running during the backup window, and whether the archive log destination was accessible.

---

## Summary

RMAN backup strategy for RAC databases shares the same fundamental mechanics as single-instance backup — Level 0 base, Level 1 incrementals, archive log management, control file autobackup — but introduces cluster-specific requirements that must be addressed explicitly:

Archive logs are generated per thread, and every thread must be present in every archive log backup. The \`BACKUP ARCHIVELOG ALL\` command backed from any RAC node captures all threads when archive logs reside in a shared ASM disk group, which is the recommended configuration.

Channel allocation on RAC can run from a single designated node (simpler, recommended for most environments) or explicitly across multiple nodes (maximum I/O parallelism, required if archive logs are on local filesystems). For ASM-based FRA configurations, single-node backup with multiple channels is the standard approach.

The recovery catalog is more valuable in a RAC environment than in single-instance deployments because it provides a backup history that survives control file loss, supports stored scripts for consistent cross-node execution, and enables cross-database visibility across multiple RAC clusters.

Configure \`ARCHIVELOG DELETION POLICY TO BACKED UP 2 TIMES TO DISK\` to prevent archive log deletion before they have been captured twice. Monitor FRA space usage continuously — a full FRA stalls archive log generation on all instances simultaneously.
`.trim();

async function main() {
  await db.insert(posts).values({
    title: 'RMAN Backup Strategy for Oracle RAC Databases',
    slug,
    excerpt: 'RMAN backup on an Oracle RAC database introduces requirements that do not exist in single-instance environments: archive logs are generated per instance thread and every thread must be present in every archive log backup, channel allocation determines which node performs backup I/O and which mount points are accessible, and a full Fast Recovery Area stalls archive log generation on all instances simultaneously. This post covers channel allocation strategies, archive log thread management, ASM considerations, complete backup scripts for Level 0 and Level 1 strategies, monitoring queries, and the recovery scenarios specific to a clustered environment.',
    content,
    category: 'rac-clusterware',
    isPremium: false,
    published: true,
    publishedAt: new Date(),
  });
  console.log('Inserted:', slug);
}

main().catch(console.error);
