import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'Oracle Shared Pool: Library Cache, Dictionary Cache, and Hard Parse Elimination',
  slug: 'oracle-shared-pool-library-cache-hard-parse',
  excerpt:
    'A deep dive into Oracle shared pool architecture — covering library cache internals, data dictionary cache, the hard parse vs. soft parse vs. parse-free execution hierarchy, bind variable discipline and CURSOR_SHARING, ORA-04031 root causes and fragmentation mechanics, and shared pool sizing methodology using V$SHARED_POOL_ADVICE and DBMS_SHARED_POOL.KEEP.',
  category: 'oracle-database' as const,
  published: true,
  isPremium: false,
  publishedAt: new Date('2026-06-05'),
  youtubeUrl: null,
  content: `## Introduction

The Oracle shared pool is the SGA component responsible for caching SQL and PL/SQL execution metadata, data dictionary information, and result sets. While the buffer cache holds data blocks, the shared pool holds the infrastructure needed to parse and execute SQL statements. Every SQL statement that Oracle executes must first be parsed — the process of checking syntax, resolving object names against the data dictionary, checking privileges, and generating an execution plan. The shared pool sits at the centre of this process: without it, every single SQL execution would require a fresh trip through syntax checking, dictionary lookups, privilege verification, and plan generation, making even the simplest OLTP system completely impractical.

Hard parsing is expensive: it acquires latches on the library cache, queries the data dictionary (which itself requires shared pool memory and row cache latch operations), generates and evaluates multiple candidate execution plans through the Cost-Based Optimizer, and allocates a new cursor in the shared pool. On a system running thousands of transactions per second, a hard parse for every execution would consume more CPU and memory than the actual SQL execution work itself. The cumulative effect of hard parses — latch contention, CPU burn, memory allocation pressure — is one of the most common and most correctable performance problems in production Oracle environments.

Soft parsing reuses an existing cursor — it still checks that the statement matches an existing cursor in the library cache (which requires latches) but skips the plan generation and dictionary lookup phases. The goal of shared pool tuning is to eliminate hard parses, maximise soft parses, and prevent ORA-04031 "unable to allocate shared memory" errors that occur when the shared pool is too fragmented or too small to accommodate a new allocation request. Between these two goals — eliminating hard parses and preventing ORA-04031 — lies the complete shared pool tuning agenda.

Shared pool problems manifest as specific, identifiable Oracle wait events and statistics: \`latch: library cache\`, \`latch: row cache objects\`, \`library cache lock\`, \`library cache pin\`, high \`parse count (hard)\` in \`V$SYSSTAT\`, low library cache hit ratios in \`V$LIBRARYCACHE\`, and ultimately ORA-04031 errors in the alert log. Each of these is a symptom pointing to one of a small number of root causes. Understanding the shared pool's internal structure — what the library cache stores, how cursors are found and reused, why fragmentation occurs and why it causes ORA-04031 even when total free memory appears adequate — is the prerequisite for diagnosing and correcting these problems efficiently.

---

## Shared Pool Components

The shared pool contains several distinct sub-areas, each serving a different part of the SQL execution lifecycle. Understanding what lives where — and why each sub-area exists as a separate region — clarifies both the tuning levers available and the failure modes that occur when the pool is improperly sized or under excessive load.

The library cache stores parsed SQL and PL/SQL: for each unique SQL statement, Oracle stores the parse tree, execution plan, bind variable metadata, execution statistics, and references to the dictionary objects the SQL touches. The library cache is organised as a hash table — the SQL text is hashed to produce a hash value, which maps to one of the library cache hash chains. Each chain is protected by a latch (or in modern Oracle, a mutex). Finding or inserting a cursor requires traversing the hash chain for the statement's hash bucket. The library cache is divided into namespaces: SQL AREA for SQL statements, TABLE/PROCEDURE/PACKAGE/etc. for PL/SQL compiled objects, BODY for package bodies, TRIGGER for triggers, and several others. Each namespace maintains its own hit ratio, reload count, and invalidation count, visible in \`V$LIBRARYCACHE\`.

The data dictionary cache (row cache) caches rows from the data dictionary — \`DBA_TABLES\`, \`DBA_INDEXES\`, \`DBA_COLUMNS\`, \`USER_$\` base tables — so that repeated parse operations do not require physical reads from the SYSTEM tablespace. Every hard parse queries the data dictionary to resolve object names, verify column existence, check privileges, and retrieve object statistics for the optimizer. The row cache stores these dictionary row values in memory, organised by dictionary table name and key. Row cache operations are protected by the \`row cache objects\` latch (or its mutex equivalent). A row cache miss means Oracle must read the dictionary row from the SYSTEM tablespace buffer cache — slower, but not catastrophic for single parses; under a parse storm, row cache pressure adds significant latency to every hard parse.

The result cache (introduced in Oracle 11g) stores the actual result sets of deterministic queries — queries whose results do not change between executions can be cached here, eliminating re-execution entirely. The \`RESULT_CACHE\` hint or the \`result_cache_mode = FORCE\` parameter directs Oracle to cache a query result. Subsequent executions with the same bind values return the cached result without executing the SQL. The PL/SQL function result cache is a subdivision of the result cache that caches the return values of deterministic PL/SQL functions, similarly eliminating repeated function calls with identical inputs.

The shared SQL area is a contiguous region within the library cache where a parent cursor and its child cursors live. A parent cursor represents a unique SQL text. A child cursor represents a specific execution context — the child stores the execution plan and bind variable type information for a particular combination of session NLS settings, optimizer parameters, and bind variable data types. One parent cursor can have multiple child cursors if, for example, the same SQL text is executed by sessions with different NLS date formats or if adaptive cursor sharing creates additional children for different bind variable value ranges.

The reserved pool is a sub-area of the shared pool reserved for large allocations (above the \`_SHARED_POOL_RESERVED_MIN_ALLOC\` hidden parameter threshold, default 4 KB) to prevent large requests from being blocked by small-object fragmentation. The reserved pool prevents the situation where the main free list contains only small chunks — the result of many small allocations and deallocations over time — and a large PL/SQL package load or a large SQL statement parse cannot find a contiguous block large enough to satisfy its request, even though total free memory is adequate.

---

## Hard Parse: What Actually Happens

Hard parsing is a multi-step, latch-intensive process. Understanding each step clarifies why hard parses are expensive and why they become a catastrophic bottleneck under high concurrency — a condition sometimes called a "parse storm."

Step 1: the server process computes a hash of the SQL text (the exact character-for-character text, including case and whitespace) and searches the library cache hash chains for a matching parent cursor. This requires a shared-mode latch on the \`library cache\` latch protecting the relevant hash bucket. At this stage, the server process is only looking — if many sessions are simultaneously searching for cursors, they compete for shared-mode latches, which can be held simultaneously by multiple readers.

Step 2: if no match is found (this is a hard parse situation), the server process must acquire an exclusive-mode latch to allocate memory for a new parent cursor and begin the parse process. Exclusive latches are held by one session at a time — all other sessions trying to parse any statement whose hash maps to the same latch must spin-wait. This is the primary mechanism by which a parse storm serialises all concurrent sessions: they are all waiting in latch spin loops while one session parses.

Step 3: syntax and semantic checking. Oracle parses the SQL text for syntactic correctness, then resolves all object and column names against the data dictionary (row cache operations with their own latch requirements), and checks the session's privilege to access those objects. Each dictionary lookup that misses the row cache adds further latency.

Step 4: the Cost-Based Optimizer (CBO) generates candidate execution plans. It considers available indexes, partition elimination opportunities, join methods (nested loop, hash join, sort-merge), and join order permutations. For each candidate plan it estimates the cost using object statistics (row counts, distinct value counts, histograms, system statistics for I/O and CPU speed). The plan with the lowest estimated cost is selected. For complex queries with many join permutations, the optimizer phase alone can take milliseconds — orders of magnitude longer than executing the SQL itself.

Step 5: the final parsed cursor — the parent cursor entry in the library cache containing the SQL text, plus the child cursor containing the execution plan, optimizer environment snapshot, and bind variable metadata — is written into the library cache. Memory is allocated from the shared pool to hold these structures permanently (until aged out). The total cost of a hard parse on a complex query can be 10–1000× the cost of executing the query. Under high concurrency, hard parsing creates severe \`library cache lock\`, \`library cache pin\`, and \`latch: library cache\` wait events as sessions compete to parse the same statement simultaneously — the parse storm pattern — because Oracle serialises library cache modifications through exclusive latches or mutexes.

---

## Soft Parse vs. Parse-Free Execution

A soft parse occurs when a session issues a SQL statement that already exists in the library cache. Oracle hashes the SQL text, finds the parent cursor on the appropriate hash chain, validates that the session's current environment matches an existing child cursor (comparing NLS settings, optimizer parameters, and bind variable data types), and reuses the existing execution plan stored in that child cursor. Soft parses still require library cache latches and are not free — just much cheaper than hard parses. They skip the CBO plan generation phase (which is the dominant cost of a hard parse) and the dictionary lookup phase, but they still compete for library cache latches to search the hash chains.

The ideal is parse-free execution: a cursor is parsed once per session connection and re-executed thousands of times using the \`EXECUTE\` call path, without re-parsing. When an application uses \`JDBC PreparedStatement\` or \`ODP.NET\` parameterized commands and the driver holds the cursor handle open across multiple executions, subsequent executions bypass parsing entirely — Oracle goes directly from the cursor handle to plan execution. This is the model used by connection pools and well-written application frameworks. The critical requirement is that the cursor handle must remain open between executions; a framework that prepares and then immediately closes a prepared statement, opening a new one for the next execution, gets soft parses instead of no parses — better than hard, but still suboptimal.

Session cursor caching controls how many recently used cursors Oracle caches in the session's private cursor cache (PGA). The \`SESSION_CACHED_CURSORS\` parameter (default 50 in recent releases) tells Oracle to keep the last N closed cursors' parse state in the session's memory. When the application closes and re-opens a cursor for the same SQL, Oracle checks the session cursor cache first — if found there, it can re-execute without acquiring library cache latches at all. This is the mechanism that makes even poorly-written applications (which close and re-open cursors between executions) perform adequately when the set of unique SQL statements is small. The \`V$SYSSTAT\` statistic \`session cursor cache hits\` measures how often the session cursor cache avoids a library cache lookup; a high ratio relative to \`parse count (total)\` indicates effective session cursor caching.

The parse call hierarchy from most expensive to least expensive is: hard parse (plan generation + dictionary lookup + library cache latch + memory allocation) > soft parse (library cache latch + hash chain search) > session cursor cache hit (no library cache interaction) > parse-free re-execution via held cursor handle (essentially zero parse overhead). The tuning goal is to push as many parse calls as far down this hierarchy as possible, with parse-free re-execution being the ideal for any SQL executed more than once.

---

## Cursor Sharing and Bind Variables

Literal SQL is the primary cause of library cache bloat and parse storms. Each unique literal value produces a unique SQL text hash — \`SELECT * FROM orders WHERE order_id = 1001\` and \`SELECT * FROM orders WHERE order_id = 1002\` are different statements requiring separate hard parses and separate library cache entries. Oracle has no knowledge that these two statements are logically identical; it sees two different character strings producing two different hash values. At scale, an application issuing 10,000 unique literal queries per second will generate 10,000 library cache entries per second, flooding the shared pool with single-use cursors that age out almost immediately. The resulting memory pressure — constant allocation and deallocation of cursor memory — fragments the shared pool's free list and increases ORA-04031 risk.

The fix is bind variables: \`SELECT * FROM orders WHERE order_id = :b1\` is one statement regardless of the bind value passed at execution time. Oracle parses it once, stores one cursor, and every execution reuses that cursor with a new bind value. The library cache entry count for this statement is one instead of N, where N is the number of distinct order ID values queried. For any frequently executed parameterized query, bind variables reduce library cache memory consumption from O(N) to O(1), eliminate the hard parse for every distinct value, and reduce latch contention proportionally.

The \`CURSOR_SHARING\` parameter provides a server-side mitigation: \`CURSOR_SHARING = FORCE\` replaces literals with system-generated bind variables (named \`:"SYS_B_0"\`, \`:"SYS_B_1"\`, etc.) before computing the hash, allowing literal SQL statements to share cursors. \`CURSOR_SHARING = SIMILAR\` was a more selective variant in older Oracle versions — it would only substitute literals if there was no histogram on the relevant column (to avoid plan instability from values that span histogram bucket boundaries) — but it was deprecated in Oracle 12c because its selectivity made its behaviour unpredictable. \`CURSOR_SHARING = FORCE\` is the blunt instrument: it substitutes all literals unconditionally.

\`FORCE\` can cause plan instability. When an optimizer histogram indicates that value X is rare (0.001% selectivity, index scan appropriate) and value Y is common (40% selectivity, full table scan appropriate), different literal values should produce different execution plans. With \`CURSOR_SHARING = FORCE\`, both values share one cursor with one plan — often the wrong plan for one of the values. For this reason, \`CURSOR_SHARING = FORCE\` is a workaround for legacy literal SQL in production emergencies, not a substitute for application-level bind variable use. The correct long-term fix is always to refactor the application to use bind variables.

\`V$SQL\` columns \`PARSE_CALLS\` and \`EXECUTIONS\` together reveal cursor reuse health. \`PARSE_CALLS / EXECUTIONS\` approaching 1 means every execution involves a parse call — the cursor is not being reused between calls. \`PARSE_CALLS\` equal to \`EXECUTIONS\` and \`EXECUTIONS\` equal to 1 means every execution is the first execution of a unique SQL text — the literal SQL flood pattern. A healthy cursor shows \`EXECUTIONS\` >> \`PARSE_CALLS\`: the cursor was parsed once (or a small number of times relative to execution count) and executed many times. The \`FORCE_MATCHING_SIGNATURE\` column in \`V$SQL\` is Oracle's computed hash of the SQL text after literal substitution — SQL statements that are logically the same but differ only in literal values share the same \`FORCE_MATCHING_SIGNATURE\`. Grouping \`V$SQL\` by \`FORCE_MATCHING_SIGNATURE\` and counting distinct cursor variants reveals which SQL statements are the worst literal SQL offenders.

---

## ORA-04031: Unable to Allocate Shared Memory

ORA-04031 occurs when Oracle cannot find a contiguous free chunk in the shared pool large enough to satisfy an allocation request. It is distinct from "shared pool is full" — a pool that is 90% utilised but well-organised can satisfy requests; a 50% utilised pool that is heavily fragmented (many small free chunks, no large contiguous free area anywhere on the free list) will raise ORA-04031 for any large allocation request. This distinction is critical because DBAs often respond to ORA-04031 by increasing \`SHARED_POOL_SIZE\`, which treats only the "pool genuinely too small" root cause and does nothing about fragmentation.

Three root causes account for the vast majority of ORA-04031 occurrences. First: the shared pool is genuinely too small for the workload's steady-state memory demand — the number of cached cursors, the size of large PL/SQL packages, and the row cache footprint together exceed the pool size. The fix is to increase \`SHARED_POOL_SIZE\` (or \`SGA_TARGET\` under ASMM). Second: literal SQL is causing thousands of single-use cursors to be created and destroyed constantly, fragmenting the free list into small chunks. Each cursor allocation carves a small piece from the free list; each cursor eviction (when the pool is full) returns a small piece — but the returned piece may not be adjacent to any other free piece, so it cannot be coalesced into a larger contiguous block. Over time, the pool contains many small free fragments but no large contiguous ones. The fix is bind variables or \`CURSOR_SHARING = FORCE\`. Third: large PL/SQL packages or SQL statements with complex plans require large contiguous allocations that cannot fit in the fragmented pool — the specific allocation request that triggers ORA-04031 may be large. The fix is \`DBMS_SHARED_POOL.KEEP\` to pin large packages before fragmentation occurs, or a flush followed by an increase in pool size.

Diagnosis: check \`V$SHARED_POOL_ADVICE\` to see if the estimated parse time savings curve indicates the pool is genuinely undersized. Check \`V$SGASTAT\` for current shared pool free memory — if free memory is above 10–15% but ORA-04031 is occurring, fragmentation is the cause, not pool size. Check \`V$SQL\` for high \`parse_calls\` with \`executions = 1\` — the literal SQL pattern. Check \`V$LIBRARYCACHE\` for reload rates — objects being evicted and reloaded indicate pool pressure and indirectly cause fragmentation through frequent allocation cycles. Check \`V$SHARED_POOL_RESERVED\` for \`REQUEST_FAILURES > 0\`, which specifically means large allocation requests to the reserved pool have failed.

The \`DBMS_SHARED_POOL.KEEP\` procedure pins large PL/SQL packages into the shared pool at instance startup, preventing their eviction and preventing the fragmentation that results from frequently loading and unloading large objects. A large package body that is 10 MB in size, if evicted and reloaded every few hours, creates 10 MB of fragmentation each cycle — the evicted space breaks into segments as other smaller allocations fill the gaps before the 10 MB region is needed again. Pinning the package eliminates this fragmentation source entirely. Pinning should be done as early as possible after instance startup, before other allocations have divided the pool; a post-startup script calling \`DBMS_SHARED_POOL.KEEP\` for all large packages is a standard production practice.

---

## Shared Pool Sizing and ASMM

With ASMM (\`SGA_TARGET\` set to a non-zero value), Oracle automatically sizes the shared pool based on demand, transferring granules between the buffer cache, shared pool, large pool, and streams pool as workload characteristics change. The \`SHARED_POOL_SIZE\` parameter acts as a minimum floor — Oracle will never shrink the shared pool below this value, regardless of what the buffer cache demands. Setting a floor equal to 80–90% of the observed steady-state shared pool demand prevents Oracle from shrinking the shared pool during parse-intensive activity, which would starve the library cache and trigger ORA-04031 or excessive reloads.

The \`V$SHARED_POOL_ADVICE\` view is the primary sizing tool. It shows estimated parse time savings at different shared pool sizes, analogous to \`V$DB_CACHE_ADVICE\` for the buffer cache. For each size point, it shows the estimated library cache size, the estimated number of objects that could be cached, and most importantly the estimated parse time saved relative to the current size. The \`ESTD_LC_TIME_SAVED_FACTOR\` column shows the ratio of estimated parse time saved at that size to the baseline — a factor > 1 means the larger size saves more parse time; a factor approaching 1 means additional size yields diminishing returns. The "knee" of the curve — the size at which the time-saved factor stops increasing meaningfully — is the appropriate sizing target. Add 20–25% headroom above the knee for growth.

The shared pool reserved area is controlled by \`SHARED_POOL_RESERVED_SIZE\` (default 5% of \`SHARED_POOL_SIZE\`). This sub-pool handles allocations above the \`_SHARED_POOL_RESERVED_MIN_ALLOC\` threshold (default 4 KB). The reserved pool has its own free list, separate from the main shared pool free list, which protects large allocations from small-object fragmentation in the main pool. Monitor \`V$SHARED_POOL_RESERVED\`: if \`REQUEST_FAILURES > 0\`, the reserved area is too small and has been unable to satisfy large allocation requests. Increase \`SHARED_POOL_RESERVED_SIZE\` — note that this parameter is not dynamic and requires an instance restart. A typical production value is 10–20% of \`SHARED_POOL_SIZE\` for workloads that make frequent large allocations (many PL/SQL packages, complex SQL plans).

The data dictionary cache hit ratio is derived from \`V$ROWCACHE\`: the ratio of \`(SUM(GETS) - SUM(MISSES)) / SUM(GETS)\` should be above 95% for a healthy shared pool. A ratio below 90% means the dictionary cache is being churned — row cache entries are being evicted before they can be reused. In steady state, the dictionary cache converges to a stable footprint representing the set of dictionary rows needed by the active SQL workload; if it cannot maintain that footprint, the shared pool is too small. Dictionary cache pressure almost always indicates that the shared pool needs to be larger, not that the workload needs to change.

---

## PL/SQL and the Shared Pool

PL/SQL packages, procedures, and functions are cached in the library cache as compiled code objects, specifically in the PACKAGE, PACKAGE BODY, PROCEDURE, FUNCTION, and TRIGGER namespaces. A large package body (hundreds of procedures and functions) can consume several megabytes of contiguous shared pool memory. Unlike SQL cursors which are relatively small (a few kilobytes for a typical plan), a large PL/SQL package body is a monolithic allocation — Oracle must find a single contiguous free region large enough to hold the entire compiled p-code object. This is why large PL/SQL packages are particularly dangerous sources of ORA-04031: they require not just adequate total free memory but adequate contiguous free memory, which fragmentation destroys.

When a package is first called after instance startup, Oracle loads the compiled p-code into the shared pool — this is a large, synchronous allocation that must be completed before the calling session can proceed. If many sessions simultaneously call a package that is not yet loaded (perhaps because the instance was just restarted, or because the package was invalidated and recompiled), they all block on \`library cache pin\` waits while one session loads the package. All others must wait for the load to complete before they can verify that the package is present. This serialisation storm — dozens of sessions blocked waiting for one package load — is a common post-restart pattern on systems with large, popular PL/SQL packages.

\`DBMS_SHARED_POOL.KEEP\` pins objects permanently: \`EXEC DBMS_SHARED_POOL.KEEP('SCHEMA.PACKAGE_NAME', 'P')\` where \`'P'\` indicates a package, \`'R'\` a trigger, \`'Q'\` a sequence, and \`'T'\` a type body. Pinning should be done in a post-startup script executed immediately after the instance opens, before application connections arrive. The effect is that the pinned object is loaded into the shared pool and marked as non-purgeable — Oracle's LRU-based eviction algorithm will never evict it, regardless of memory pressure. The pinned object occupies shared pool memory permanently; size the shared pool to accommodate pinned objects as a fixed overhead. The \`SIZES\` procedure in \`DBMS_SHARED_POOL\` lists objects above a size threshold that are candidates for pinning: \`EXEC DBMS_SHARED_POOL.SIZES(100)\` lists all objects above 100 KB currently in the shared pool.

Invalidation is a major source of library cache churn. DDL on any object that a package references — \`ALTER TABLE\`, \`CREATE INDEX\`, \`GRANT\`, \`REVOKE\`, even collecting statistics in some circumstances — invalidates the package. The next call to the invalidated package triggers a recompilation, which is equivalent to a hard parse for PL/SQL: Oracle must re-resolve all object references, re-verify privileges, and re-compile the p-code. In development environments with frequent DDL, this is expected. In production, unexpected invalidation chains (where one DDL invalidates package A, which invalidates packages B and C that reference A, which in turn invalidate packages D and E) can cause widespread library cache invalidation and a post-DDL parse storm. Reducing dependency chain depth and avoiding unnecessary DDL on production objects during peak hours minimises invalidation risk.

---

## Summary

The Oracle shared pool is a multi-component SGA region whose primary function is to serve as a parse cache: the library cache stores parsed SQL and PL/SQL execution plans so they can be reused without re-parsing; the data dictionary cache stores dictionary row data so that parse operations do not require physical reads from SYSTEM; the result cache stores query results to eliminate re-execution; and the reserved pool protects large allocation requests from small-object fragmentation in the main pool. These components work together to make SQL execution efficient at scale. Without the shared pool, even a simple OLTP workload running thousands of transactions per second would spend the majority of its CPU time re-parsing the same SQL statements over and over.

The hard vs. soft vs. parse-free execution hierarchy is the central organising principle of shared pool tuning. Hard parses are the most expensive: they acquire exclusive library cache latches, query the data dictionary, invoke the Cost-Based Optimizer, and allocate new cursor memory — all serialised operations that bottleneck under concurrency. Soft parses reuse existing cursors but still require library cache latch operations. Parse-free execution — a cursor held open between executions in a connection pool — adds essentially zero parse overhead. The tuning goal is always to push parse calls down this hierarchy: eliminate hard parses first (bind variables, cursor sharing), then reduce soft parse overhead (session cursor caching, \`SESSION_CACHED_CURSORS\`), then achieve parse-free execution (proper connection pooling with cursor reuse).

Bind variable discipline is the most effective shared pool optimisation available to application developers and DBAs alike. A workload that substitutes bind variables for literals reduces the library cache entry count from O(distinct values) to O(distinct statement templates), eliminates hard parses for every unique literal value, and prevents the fragmentation pattern that leads to ORA-04031. \`CURSOR_SHARING = FORCE\` is the server-side emergency valve when application refactoring is not immediately possible, but it carries plan stability risks and should be treated as a temporary measure. ORA-04031 has three root causes — pool genuinely too small, fragmentation from literal SQL churn, and large allocation failures — each requiring a different remedy, and misdiagnosing fragmentation as "pool too small" and simply increasing \`SHARED_POOL_SIZE\` is a common mistake that delays the real fix.

ASMM with a properly set \`SHARED_POOL_SIZE\` floor and the reserved pool sized at 10–20% of the shared pool handles most production environments without manual intervention, provided the workload uses bind variables. For PL/SQL-heavy workloads, \`DBMS_SHARED_POOL.KEEP\` for large packages is a mandatory post-startup step — it eliminates the load-on-demand storm pattern, ensures contiguous memory is available for large package loads, and prevents fragmentation from repeated large allocation cycles. The combination of bind variables in application SQL, proper shared pool sizing using \`V$SHARED_POOL_ADVICE\`, reserved pool sizing from \`V$SHARED_POOL_RESERVED\`, and pinned packages via \`DBMS_SHARED_POOL.KEEP\` constitutes a complete, robust shared pool management strategy for any Oracle database.`,
};

async function main() {
  console.log('Inserting shared pool concept post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: { ...post },
  });
  console.log('Inserted: "' + post.title + '"');
}

main().catch(console.error);
