import { config } from 'dotenv';
config({ path: '.env.local' });

import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { posts } from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql });

const post = {
  title: 'Oracle Index Types: B-Tree, Bitmap, Function-Based, Partitioned, and Beyond',
  slug: 'oracle-index-types-btree-bitmap-function-based',
  excerpt:
    'Oracle provides a rich set of index types — B-Tree, Bitmap, Function-Based, Composite, Reverse Key, Partitioned, IOT, and more — each optimised for a specific data distribution and query pattern. Choosing the wrong index type is one of the most common causes of poor query performance and excessive DML overhead. This guide explains how each index type works internally, when it helps, when it hurts, and the decision framework for building an efficient index strategy.',
  category: 'oracle-database' as const,
  published: true,
  isPremium: false,
  publishedAt: new Date('2026-06-05'),
  youtubeUrl: null,
  content: `## Introduction

Oracle's indexing subsystem is one of the most misunderstood areas in database performance tuning. Walk into any Oracle environment that has grown organically over a decade and you will find the same pattern: indexes on every foreign key, indexes on every column that ever appeared in a WHERE clause complaint, indexes that duplicate each other's leading columns, bitmap indexes on OLTP tables, and a complete absence of indexes on columns that actually need them. The database is carrying kilograms of extra weight on every INSERT, UPDATE, and DELETE — weight that is not helping any query. The developers who added those indexes were not negligent; they were following a reasonable heuristic ("add an index when a query is slow") without a mental model of what each index type actually does and when it stops helping.

The fundamental principle of indexing is this: an index is a read optimisation that costs write overhead and storage. Every time a row is inserted, every index on that table must receive a new entry. Every time an indexed column is updated, the old index entry must be deleted and a new one inserted. Every time a row is deleted, every index entry must be removed. The index maintenance is synchronous — it happens as part of the same transaction, under the same lock, generating the same redo and undo. An index that accelerates one query but is never used by any other query is paying this overhead for nothing. Multiplied across a high-concurrency OLTP table with ten indexes and ten thousand transactions per second, the aggregate overhead is enormous.

The right index type depends entirely on three things: the data distribution of the indexed column (is it high-cardinality with near-unique values, or low-cardinality with only a handful of distinct values?), the query pattern that needs to use it (equality lookup, range scan, expression predicate, or multi-column filter?), and the DML frequency of the table (is it read-heavy with rare writes, or a high-throughput OLTP table where write overhead matters?). These three dimensions map cleanly to the index types Oracle provides, and understanding that mapping is the difference between an index strategy and an index accident.

This post covers the complete range of Oracle index types in depth. We begin with the B-Tree, Oracle's universal default and the right choice for the majority of OLTP indexing needs. We then cover Bitmap indexes and why they are transformative for analytical workloads but catastrophic on OLTP tables. Function-Based indexes solve the expression predicate problem that stumps many developers who cannot understand why their index is being ignored. Composite indexes introduce the leading column rule that every query writer must understand. Reverse Key indexes address the right-hand insert hotspot that plagues sequence-generated primary keys under high concurrency. Partitioned indexes — local and global — integrate the index lifecycle with partition maintenance. We close with Invisible indexes, Index-Organised Tables, and the 12c Partial index feature. A companion runbook provides ready-to-run SQL for every operation covered here.

---

## B-Tree Indexes: The Universal Default

The B-Tree (Balanced Tree) is Oracle's default index type. When you issue \`CREATE INDEX\` without any additional keywords, you get a B-Tree. The structure is a rooted tree of index blocks where every path from root to leaf has exactly the same depth — that is what "balanced" means. The root block contains the highest-level branch entries, pointing to branch blocks, which in turn point to leaf blocks. Leaf blocks store the actual index entries: (key value, ROWID) pairs, sorted in ascending key order by default. Each leaf block is linked bidirectionally to its neighbours, enabling efficient range scans — Oracle can find the first qualifying entry via a root-to-leaf traversal, then walk laterally through the leaf block chain to collect all entries in the range without returning to the root.

Oracle maintains balance through block splits. When a leaf block fills up, Oracle splits it into two half-full blocks and promotes a new branch entry to the parent. If the parent also fills up, it splits and promotes to its parent, continuing up the tree until reaching the root. If the root splits, a new root is created and the tree gains one level of depth. This process guarantees that the tree remains balanced at all times regardless of insert order, key distribution, or delete patterns. The consequence is predictable access cost: the number of block reads to locate a single ROWID is always equal to the tree height (BLEVEL) plus one. For a table with a billion rows and a selective B-Tree index, BLEVEL is typically 4 or 5 — meaning Oracle reads five or six index blocks to get the ROWID, then one table block. That is seven I/Os, regardless of the table size. That is the fundamental value proposition of a B-Tree.

The clustering factor is the most important statistic describing how efficiently an index range scan will perform against the heap table. It is computed by walking the index leaf blocks in key order and counting the number of times consecutive index entries point to different table blocks. A clustering factor equal to the number of table blocks (the minimum possible value) means that rows are physically stored in the same order as the index key — every consecutive index entry points to the same block as the previous one, so the range scan touches at most one block per row in the worst case. A clustering factor equal to the number of rows (the maximum possible value) means every consecutive index entry points to a completely different table block — the range scan devolves into one random I/O per row, which for a large range scan is worse than a full table scan. The optimizer uses the clustering factor when calculating the cost of an index range scan access path: a poor clustering factor can cause the optimizer to correctly choose a full table scan even when you expect the index to be used.

B-Tree indexes are excellent for high-cardinality columns: primary keys, unique identifiers, email addresses, order numbers, timestamps with fine precision. They support equality predicates (\`=\`), range predicates (\`>\`, \`<\`, \`BETWEEN\`), \`LIKE 'prefix%'\` searches, \`IS NULL\` (Oracle B-Trees store NULL entries, unlike most other databases), and \`ORDER BY\` when the sort direction matches the index. They work poorly for low-cardinality columns: a column with only two distinct values (Y/N, M/F, OPEN/CLOSED) has an index where half the entries point to each value. A query for all open orders will retrieve half the table's rows. The optimizer knows this: at around 10–15% selectivity, a full table scan typically has lower cost than an index range scan plus row fetch, because a full table scan uses large multi-block reads while the index path requires a single-block read per table block (even worse: each single-block read may evict a useful buffer cache entry). The B-Tree on a low-cardinality column is not just useless — it actively adds overhead to every DML statement on the table.

---

## Bitmap Indexes: Analytical Workloads and Low Cardinality

A bitmap index stores, for each distinct value in the indexed column, a compressed bit string with one bit per row in the table. If the bit is 1, that row has this value; if 0, it does not. Oracle compresses these bit strings using a run-length encoding scheme (Byte-Aligned Bitmap Compression, or BBC) that makes the storage extremely compact for both high-density and low-density bitmaps. The index for a column with 10 distinct values across a 100-million-row table consists of 10 compressed bit strings. A lookup for a single value decompresses its bit string and converts the 1-bits to ROWIDs — the conversion is done in bulk using SIMD-style operations that process 64 bits (64 rows) simultaneously on modern hardware.

The transformative capability of bitmap indexes is multi-column AND/OR operations. If a query filters \`WHERE region = 'WEST' AND product_category = 'ELECTRONICS' AND order_status = 'SHIPPED'\`, Oracle can retrieve the three bitmap strings — one per index — and perform a bitwise AND in a single pass. The result is a bitmap where only rows matching all three predicates have a 1-bit. This is converted to a ROWID list in one operation. Compare this to three B-Tree indexes: Oracle would have to perform three range scans, collect three ROWID lists, and merge them with a SORT MERGE or BITMAP CONVERSION operation. The bitmap approach is dramatically faster, particularly when the intersecting bitmaps are sparse (the result set is small compared to the table size). No hash join, no sort, no temp segment — just bitwise arithmetic on compressed bit strings.

The fatal characteristic of bitmap indexes is their locking granularity. A B-Tree index stores one entry per row value — to lock that entry, Oracle uses a row-level lock. A bitmap index stores one bitmap per distinct value, where each bitmap covers all rows with that value — potentially millions of rows. To update a single row's bitmap column, Oracle must lock the entire bitmap segment for that value. This means two concurrent transactions that both update the \`status\` column — even if they are updating completely different rows — will serialize completely if they both set \`status = 'OPEN'\`. The first transaction takes an exclusive lock on the \`status = 'OPEN'\` bitmap; the second waits. Under OLTP concurrency (thousands of transactions per second touching the same columns), this serialization is application-ending. Bitmap indexes must never be created on any table that receives concurrent DML.

The appropriate use case for bitmap indexes is a data warehouse or reporting database with batch-loaded data and no concurrent DML during query hours. Dimension columns on a fact table — region (5–50 values), product category (50–200 values), status (3–10 values), channel (2–5 values) — are perfect bitmap candidates. The NDV-to-row-count ratio is the practical rule of thumb: bitmap indexes are beneficial when NDV is less than 1% of num_rows. A column with 100 distinct values in a 50-million-row table (0.0002% NDV) is ideal. A column with 100,000 distinct values in the same table (0.2% NDV) — borderline. A column with 1 million distinct values — use a B-Tree. Oracle itself provides this guidance in the \`DBMS_STATS\` documentation, and the optimizer's cost model reflects it: on tables with optimizer statistics, the optimizer will often choose a B-Tree over a bitmap for moderate-NDV columns even if you have both indexes.

---

## Function-Based Indexes: Indexing Expressions

A function-based index (FBI) solves a specific problem: Oracle cannot use a standard index on a column if the query predicate applies a function or expression to that column. The predicate \`UPPER(last_name) = 'SMITH'\` cannot use an index on \`last_name\` because Oracle must first apply UPPER to each \`last_name\` value before comparing — and the index stores the original (mixed-case) values, not the UPPER-transformed ones. The optimizer would have to apply the function to every index entry to find matches, which negates any advantage the index provides. The only way to use an index for this predicate is to pre-compute the expression and store it in the index.

A function-based index does exactly that. \`CREATE INDEX idx_upper_name ON employees(UPPER(last_name))\` creates a B-Tree index whose entries are the UPPER-transformed values rather than the original column values. Oracle registers this as a virtual column in \`DBA_IND_EXPRESSIONS\`. When the optimizer encounters \`WHERE UPPER(last_name) = 'SMITH'\`, it recognises that the expression matches the FBI definition and considers it a candidate access path, exactly as it would for a plain column index. The session must have \`QUERY_REWRITE_ENABLED = TRUE\` (the default since Oracle 10g) and the function must be deterministic — the same input must always produce the same output. Non-deterministic functions (SYSDATE, DBMS_RANDOM, USERENV) cannot be indexed because the stored value would immediately become stale.

Function-based indexes are not limited to single-function transformations. \`CREATE INDEX idx_year_hired ON employees(EXTRACT(YEAR FROM hire_date))\` supports year-only date range queries without forcing a full scan when the predicate is \`EXTRACT(YEAR FROM hire_date) = 2024\`. \`CREATE INDEX idx_full_name ON employees(last_name || ', ' || first_name)\` supports formatted-name lookups. A particularly useful pattern is the conditional (partial-like) index: \`CREATE INDEX idx_active_orders ON orders(CASE WHEN status = 'OPEN' THEN order_id END)\`. Oracle only stores entries where the expression is non-NULL — so this index contains entries only for open orders. If 95% of orders are closed, this index is 5% the size of a plain index on \`order_id\`, yet it serves all queries that filter on active orders by order_id.

Oracle 11g introduced virtual columns as a cleaner way to express the same concept. \`ALTER TABLE employees ADD (last_name_upper AS (UPPER(last_name)))\` adds a virtual column that is not physically stored in the table but is computed on access. You can then create a standard B-Tree index on the virtual column: \`CREATE INDEX idx_upper_name ON employees(last_name_upper)\`. The result is functionally identical to a direct FBI, but the virtual column is visible in \`DBA_TAB_COLUMNS\`, can have statistics collected on it independently, and is more explicit in the schema definition — a developer looking at the table structure sees \`last_name_upper\` and understands why the FBI exists, rather than having to inspect \`DBA_IND_EXPRESSIONS\`. Both approaches are valid; virtual columns are generally preferred for new development.

---

## Composite Indexes: Column Order is Everything

A composite index (also called a concatenated or multi-column index) stores multiple key columns in a single B-Tree structure. The leaf entries contain all indexed column values concatenated together as the key, followed by the ROWID. Oracle sorts the entries by the first column, then by the second column within identical first-column values, then by the third, and so on. This sorted order is the source of the leading column rule: Oracle can use a composite index efficiently only if the leading column (or a contiguous prefix of leading columns) appears in the WHERE clause predicate. If the leading column is absent, Oracle would have to scan the entire index to find matching entries — no better than a full table scan.

The leading column rule has one exception: the index skip scan. If the leading column has very low cardinality, Oracle can perform multiple range scans (one per distinct value of the leading column) and merge the results. For a composite index on (status, order_date) where status has 3 distinct values, an index skip scan for a predicate on order_date alone would perform 3 range scans — one for each status value. Whether this is cheaper than a full table scan depends on the cardinality. In practice, index skip scans are rarely the best solution; when you find the optimizer using one, it is often a signal that the column order in the composite index is wrong.

Column ordering strategy should follow the access pattern, not intuition about importance. For a query that filters on exact matches for multiple columns, put the most selective column first — this minimises the number of leaf entries that match the first-column predicate. For a query that filters on equality for one column and a range for another — the most common pattern — put the equality column first and the range column last. The equality predicate on the first column drastically reduces the range that must be scanned by the second-column predicate. Reversing the order forces Oracle to scan all rows matching the range predicate before applying the equality filter, which could be orders of magnitude more entries.

The covering index is the most powerful performance optimisation available in a composite index strategy. If all columns referenced by a query — both in the WHERE clause and in the SELECT list — are present in the index, Oracle can answer the query entirely from the index without ever touching the table segment. This eliminates the \`TABLE ACCESS BY INDEX ROWID\` step and all associated single-block I/O against the heap. In EXPLAIN PLAN, this appears as \`INDEX FAST FULL SCAN\` or a plain \`INDEX RANGE SCAN\` with no subsequent table access. For high-concurrency OLTP queries that run millions of times per day, eliminating the table fetch can more than double throughput. The cost is index size: each additional column in the composite index increases the size of every leaf entry, which increases the number of index blocks, which increases buffer cache pressure and I/O.

---

## Reverse Key Indexes: Solving Right-Hand Insert Contention

In any B-Tree index, inserts go to the leaf block that contains the range matching the new key value. When keys are generated by a sequence or a timestamp — the most common surrogate key pattern in OLTP systems — each new key is numerically greater than all existing keys. Every insert therefore goes to the rightmost leaf block of the B-Tree. Under single-user load, this is fine. Under high-concurrency OLTP, it is catastrophic: hundreds of sessions simultaneously try to latch and modify the same block, resulting in \`buffer busy waits\` and \`latch: cache buffers chains\` wait events. The wait event graph shows a dramatic spike on a single block address. Increasing the PCTFREE on the index helps marginally — it defers the split — but does not eliminate the hotspot.

A reverse key index stores a byte-reversed version of each key value. Key 1000001 is stored as 1000001 reversed byte-by-byte: the exact transformation depends on the internal numeric representation, but the effect is that numerically adjacent keys have completely different reversed values and land on completely different leaf blocks. Key 1000001 might land on leaf block 47; key 1000002 on leaf block 312; key 1000003 on leaf block 89. Inserts are distributed uniformly across the entire leaf block layer, and the right-hand hotspot disappears. This is a real and significant fix for the described contention problem.

The trade-off is that range scans and ORDER BY operations cannot use a reverse key index. The index stores keys in reversed-byte order, not in numeric order, so consecutive index entries correspond to non-consecutive key values. A query for \`order_id BETWEEN 1000000 AND 1001000\` would have to scan the entire index to find all matching entries — the same problem as applying a function to an indexed column. The reverse key index is appropriate only when the primary key column is used exclusively for equality lookups (\`WHERE order_id = ?\`) and never for range scans. This is true of many surrogate primary key patterns where the key has no business meaning and is never used in range predicates.

The modern architectural alternative to a reverse key index is hash partitioning the table with a local index. Hash partitioning distributes rows across N partitions based on a hash of the partition key, so inserts are spread evenly across partitions. A local index creates one index segment per partition; inserts to each partition modify only that partition's index segment. The contention is divided by N — for 16 partitions, the insert throughput is approximately 16x what it would be on a non-partitioned table with a reverse key index, and range scans work normally because the index is not key-reversed. Hash partitioning requires the Oracle Partitioning option license, but it is the architecturally superior solution when that license is available.

---

## Partitioned Indexes: Local and Global

When a table is partitioned, Oracle provides two index partitioning strategies. A local index has one index partition per table partition, and the partitioning key of the index is the same as the partitioning key of the table. Every row in table partition P1 has its index entry in index partition P1. This 1:1 mapping means the index is inherently maintenance-free: when a table partition is added, the corresponding index partition is created automatically; when a table partition is dropped or truncated, the corresponding index partition is dropped with it, with no index rebuilds required. This is the primary operational advantage of local indexes for time-series tables where old partitions are dropped on a regular schedule.

Local index partition pruning follows directly from table partition pruning. When the optimizer prunes table partitions based on a partition key predicate, it also prunes the index — a query that touches only the January 2026 table partition also touches only the January 2026 index partition. For a table with 60 monthly partitions, a query filtering on a single month reads 1/60th of the index. This is automatic and requires no special syntax. Local unique indexes have a constraint: they can only guarantee uniqueness within a single partition, not across the entire table. This means a local unique index is only valid if the partition key is a prefix of the unique key — ensuring that rows with the same unique key always land in the same partition. For cross-partition uniqueness, a global index is required.

A global index spans all table partitions. Its partitioning is independent of the table's partitioning — a global index may be unpartitioned (a single B-Tree covering all table rows) or globally partitioned (range or hash partitioned on the index's own key). Global indexes are required when the indexed column is different from the table partition key and uniqueness across partitions must be enforced. They are also required when the query workload frequently filters on a non-partition-key column and cannot benefit from table partition pruning — in this case, a global partitioned index on the query's filter column can provide index partition pruning independent of the table partition structure.

The critical operational difference between local and global indexes is what happens when a table partition is dropped or truncated. Oracle cannot automatically remove the corresponding index entries from a global index, because a global index entry's location depends on the index's own partition key, not the table's. Dropping a table partition makes all global index entries for that partition's rows invalid. Oracle marks the affected global index partitions (or the entire global index if unpartitioned) as \`UNUSABLE\`. Any subsequent query that would use the global index will fail with ORA-01502 until the index is rebuilt. To avoid this, partition maintenance DDL must include the \`UPDATE INDEXES\` or \`UPDATE GLOBAL INDEXES\` clause: \`ALTER TABLE orders DROP PARTITION p_old UPDATE GLOBAL INDEXES\`. This online index maintenance has a cost — Oracle must delete the stale entries from the global index as part of the DDL — but it avoids the hard failure. For tables where partition drops happen frequently (daily or hourly retention policies), local indexes are strongly preferred.

---

## Invisible Indexes, IOTs, and Partial Indexes

The invisible index, introduced in Oracle 11g, provides a zero-risk way to test an index before exposing it to production workloads. An invisible index is fully maintained: every INSERT, UPDATE, and DELETE on the table updates the invisible index exactly as it would a normal index. The index is structurally valid and contains current data. The only difference is that the optimizer ignores it — its access path is not considered when building execution plans. To test whether the index would help a specific query, you set \`ALTER SESSION SET optimizer_use_invisible_indexes = TRUE\` in a test session. The optimizer now sees the invisible index and may choose it. You can run EXPLAIN PLAN, compare costs, and verify the execution plan improvement before committing. When satisfied, \`ALTER INDEX name VISIBLE\` makes it available to all sessions instantly. The reverse is equally valuable: before dropping an index that you believe is unused, make it invisible. Monitor for a week. If no sessions set \`optimizer_use_invisible_indexes = TRUE\` and no plans degrade, you can drop it with confidence.

An Index-Organised Table (IOT) inverts the normal table structure. In a standard heap table, the table segment stores rows in an unordered heap and each B-Tree index maintains a separate sorted copy of the key plus ROWID pointers. In an IOT, there is no separate heap segment — the table's rows are stored inside the B-Tree leaf blocks, sorted by the primary key. Every access to an IOT row by primary key is an index lookup that returns the full row without a second I/O for the table block. Secondary indexes on an IOT store the primary key value as the ROWID substitute (since there is no fixed physical ROWID in an IOT — rows move when the B-Tree rebalances). IOTs are ideal for tables where the primary key is the dominant (or only) access path, the row is small enough to fit in a leaf block without overflowing to an overflow segment, and read throughput matters more than write throughput. Reference tables, lookup tables, and range-partition-key tables frequently fit this profile.

Oracle 12c introduced the Partial Index feature. On a partitioned table, you can designate specific partitions as \`INDEXING OFF\`, which prevents the index from maintaining entries for those partitions. \`ALTER TABLE orders MODIFY PARTITION p_archive INDEXING OFF\`. Subsequent index creation with the \`INDEXING PARTIAL\` clause will skip the \`INDEXING OFF\` partitions. This is valuable for tables with an active data set and a large historical archive: queries against current data use the partial index; queries against archive data fall back to full partition scans (which is often acceptable since archive queries are rare and the partitions are separate). The result is a dramatically smaller index covering only the data that actually benefits from it, with correspondingly lower DML overhead and buffer cache consumption.

Bitmap join indexes extend the bitmap index concept to a pre-joined structure. A bitmap join index on a fact table can include a column from a related dimension table, pre-computing the join relationship in the index. A query that filters on the dimension column can use the bitmap join index to avoid the join entirely. Bitmap join indexes are powerful in data warehouse star schema environments but come with significant maintenance complexity — any DML on either the fact table or the dimension table requires maintaining the bitmap join index. They are rarely used outside specialised analytical environments and should be considered only after exhausting standard indexing options.

---

## Summary

The decision framework for Oracle index type selection reduces to a small set of questions. First: what is the cardinality of the column? High cardinality (most values unique or near-unique) points to B-Tree; low cardinality (fewer than 1% NDV) in a read-heavy analytical environment points to Bitmap. Second: is the predicate against the raw column value or an expression? If an expression, use a Function-Based index or a virtual column B-Tree. Third: does the query filter on multiple columns? Build a composite index with the most selective equality column leading, followed by any range column. Check whether including the SELECT list columns in the composite index creates a covering index that eliminates the table fetch. Fourth: does the primary key use sequence-generated values and suffer from right-hand insert contention? Consider a Reverse Key index (equality access only) or hash partitioning with local indexes (if range scans are needed). Fifth: is the table partitioned? Prefer local indexes when the index key is the partition key or a prefix of it; use global indexes when uniqueness across partitions is required or the query access pattern is on a non-partition-key column.

There are two universal rules that apply regardless of index type. First, every index has a write cost. An index that is never used is not free — it costs an index maintenance operation on every INSERT, UPDATE (of the indexed column), and DELETE. In a high-throughput OLTP environment, redundant indexes measurably reduce write throughput. The question to ask before creating an index is not "could this index help?" but "does the read benefit for the expected query volume and frequency outweigh the write overhead for the expected DML rate on this table?" Second, indexes require optimizer statistics to be used correctly. Without current statistics, the optimizer cannot estimate the cost of an index access path accurately and may choose a full table scan when an index would be far cheaper, or choose an index when a full table scan is the correct choice. Run \`DBMS_STATS.GATHER_TABLE_STATS\` after creating an index and ensure the automated statistics job covers all production tables.

The most common indexing mistake in production systems is not the choice of wrong index type — it is the accumulation of unused and redundant indexes that nobody dares to drop. An index added during a performance emergency three years ago, now serving a query that was rewritten or retired, continues to tax every DML statement on the table. Invisible indexes provide the safe mechanism to test removals without risk. Index usage monitoring (\`ALTER INDEX name MONITORING USAGE\`, then \`SELECT * FROM V\$OBJECT_USAGE\`) can identify indexes that have not been used in a monitoring period. A regular index audit — at minimum annually, ideally quarterly — should be part of every DBA's operational cadence. Every index removed that was not being used is a permanent, compounding DML performance improvement.

The companion runbook to this post provides complete SQL scripts for every phase of index management: inventory and health check, creation of all index types, clustering factor analysis, index usage monitoring, fragmentation detection, rebuild and maintenance procedures, and identification of missing and harmful indexes. It also includes a shell script for automated nightly index health alerting.`,
};

async function main() {
  console.log('Inserting Oracle Index Types concept post...');
  await db.insert(posts).values(post).onConflictDoUpdate({
    target: posts.slug,
    set: { ...post },
  });
  console.log('Inserted: "' + post.title + '"');
}

main().catch(console.error);
