import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';

const slug = 'ebs-patching-fndload-ldt-worker-failure-troubleshooting';

const content = `
Patch day in Oracle E-Business Suite is rarely uneventful. You apply a patch that looks straightforward, assign workers, and watch the adpatch manager begin stepping through tasks — until one worker locks up with the message every EBS DBA dreads:

> **ATTENTION: All workers either have failed or are waiting.**

This post dissects one of the most common causes of that message: a worker failure during LDT loader processing. We will look at exactly what the error means, walk through a systematic investigation using SQL and shell scripts, and close with a clean procedure to resume the patch without restarting from zero.

---

## The Scenario

You are applying patch **28458567** on an EBS 12.1.3 environment running against Oracle Database 11.2.0.4. The adpatch session starts normally, distributes tasks to workers, and then worker 2 fails while processing a loader data file belonging to the Advanced Pricing (QP) module.

Your \`adwork002.log\` shows a tight failure loop:

\`\`\`
ASSIGNED: file qpprg.ldt on worker 2 for product qp username APPS.
FAILED:   file qpprg.ldt on worker 2 for product qp username APPS.
DEFERRED: file qpprg.ldt on worker 2 for product qp username APPS. (Deferment number 2 for this job)

An entity data line was expected

ATTENTION: All workers either have failed or are waiting:
FAILED: file qpprg.ldt on worker 2.
ATTENTION: Please fix the above failed worker(s) so the manager can continue.
\`\`\`

---

## What the Error Actually Means

### The culprit: FNDLOAD

The Oracle Loader (FNDLOAD) is the utility EBS uses to load seed data from \`.ldt\` files into the database. \`.ldt\` files carry structured data — program definitions, lookups, menus, messages, concurrent program definitions — and follow a strict hierarchical format with entity headers, begin/end markers, and field-value pairs.

When FNDLOAD reports **"An entity data line was expected"**, it means the parser hit content that does not match the expected structure at that position in the file. The two most common causes:

| Cause | Signature |
|---|---|
| **File corruption / truncation** | File ends mid-block, or has zero-byte lines. Common after bad download, NFS interruption, or an OS-level disk event during extraction. |
| **FNDLOAD version mismatch** | The \`.ldt\` was generated by a newer version of the Oracle Application Object Library (FND) that uses a slightly different entity header format. Your installed FND utilities do not understand the new format. |

A third, less common cause is a character encoding problem — the \`.ldt\` file was extracted to a filesystem with a different NLS_LANG and multi-byte characters corrupted the parser's line boundaries.

---

## Initial Investigation

Before touching anything, collect the evidence. Run these queries against the APPS schema while the patch session is still active (workers in FAILED state, adpatch manager stopped).

### 1. Confirm worker status in the AD tables

\`\`\`sql
-- Active patch session
SELECT patch_run_id, name, start_date, end_date, phase_name
FROM   applsys.ad_patch_runs
WHERE  end_date IS NULL
ORDER  BY start_date DESC
FETCH  FIRST 3 ROWS ONLY;

-- Worker job status for the failing worker
SELECT w.worker_id,
       w.status,
       j.filename,
       j.product_short_name,
       j.execution_status,
       j.start_date,
       j.end_date,
       j.log_filename
FROM   applsys.ad_workers   w
JOIN   applsys.ad_deferred_jobs j ON j.worker_id = w.worker_id
ORDER  BY j.start_date DESC
FETCH  FIRST 20 ROWS ONLY;
\`\`\`

### 2. Find exactly which LDT file is failing

\`\`\`sql
SELECT j.job_type,
       j.filename,
       j.product_short_name,
       j.execution_status,
       j.failure_count,
       j.log_filename
FROM   applsys.ad_deferred_jobs j
WHERE  j.execution_status IN ('F', 'D')   -- Failed or Deferred
  AND  j.filename LIKE '%.ldt'
ORDER  BY j.failure_count DESC, j.start_date DESC;
\`\`\`

### 3. Check the installed FND / ATG version

A version mismatch between the patch's \`.ldt\` format and the installed FND utilities is the second most common cause.

\`\`\`sql
SELECT application_short_name,
       product_version,
       patch_level,
       status
FROM   applsys.fnd_product_installations
WHERE  application_short_name IN ('FND', 'QP')
ORDER  BY application_short_name;
\`\`\`

### 4. Check for prerequisite patch gaps

\`\`\`sql
-- Patches applied in the last 7 days — look for the patch and its prerequisites
SELECT ab.bug_number,
       ab.creation_date,
       ab.last_update_date,
       ab.platform_code,
       ab.language_code
FROM   applsys.ad_bugs ab
WHERE  ab.creation_date >= SYSDATE - 7
ORDER  BY ab.creation_date DESC;
\`\`\`

### 5. Check the actual LDT file on disk

\`\`\`bash
# Locate the failing LDT file
find $QP_TOP/patch/115/import -name "qpprg.ldt" 2>/dev/null
# Also check the patch staging area
find $APPL_TOP/../patch -name "qpprg.ldt" 2>/dev/null

# Check file size and last-modified timestamp
ls -lh \$(find $QP_TOP -name "qpprg.ldt" 2>/dev/null)

# Inspect the tail of the file — truncated files end abruptly
tail -20 \$(find $QP_TOP -name "qpprg.ldt" 2>/dev/null)

# Count BEGIN/END markers — a healthy LDT has balanced pairs
grep -c '^BEGIN ' \$(find $QP_TOP -name "qpprg.ldt" 2>/dev/null)
grep -c '^END '   \$(find $QP_TOP -name "qpprg.ldt" 2>/dev/null)
# If BEGIN count != END count the file is truncated
\`\`\`

### 6. Validate file integrity against the patch zip

\`\`\`bash
# If the patch zip is still present in the staging area
PATCH_ZIP="/u01/patches/p28458567_121300_Linux-x86-64.zip"
unzip -p "\$PATCH_ZIP" "28458567/qp/patch/115/import/qpprg.ldt" | \
  md5sum > /tmp/zip_md5.txt

md5sum \$(find $QP_TOP -name "qpprg.ldt" 2>/dev/null) > /tmp/disk_md5.txt

diff /tmp/zip_md5.txt /tmp/disk_md5.txt
# Any output means the disk file differs from the zip — re-extract
\`\`\`

---

## Root Cause Decision Tree

\`\`\`
Worker 2 failed on qpprg.ldt — "An entity data line was expected"
│
├── BEGIN count != END count in file?
│     └── YES → FILE TRUNCATED
│               → Re-extract from patch zip or re-download
│
├── BEGIN == END but file has zero-byte lines or garbled characters?
│     └── YES → FILE CORRUPTED (encoding or disk I/O)
│               → Re-extract fresh copy
│
├── File looks complete but FND version < expected?
│     └── YES → PREREQUISITE MISSING
│               → Apply required ATG / FND patch first
│
└── File clean, FND version correct, NLS_LANG mismatch?
      └── YES → CHARACTER SET ISSUE
                → Re-extract with correct NLS_LANG set on OS session
\`\`\`

---

## The Fix

### Option A — Re-extract the LDT file from the patch zip

This resolves truncation and most corruption cases.

\`\`\`bash
# Back up the corrupted file
cp $QP_TOP/patch/115/import/qpprg.ldt \
   $QP_TOP/patch/115/import/qpprg.ldt.bak_$(date +%Y%m%d)

# Re-extract from the original patch zip
PATCH_STAGE="/u01/patches/28458567"

# If zip still present
unzip -o /u01/patches/p28458567_121300_Linux-x86-64.zip \
  "28458567/qp/patch/115/import/qpprg.ldt" \
  -d /tmp/patch_extract/

cp /tmp/patch_extract/28458567/qp/patch/115/import/qpprg.ldt \
   $QP_TOP/patch/115/import/qpprg.ldt

# Verify the freshly extracted file
tail -5 $QP_TOP/patch/115/import/qpprg.ldt
\`\`\`

### Option B — Apply missing prerequisite ATG patch first

If root cause is a version mismatch:

\`\`\`bash
# Stop the current patch session (do NOT use adpatch abort — use adctrl)
# Then apply the prerequisite FND/ATG patch in a new session
cd /u01/patches/<prereq_patch_number>
adpatch

# After prereq completes, resume the original session
\`\`\`

---

## Resuming the Patch with adctrl

Once the root cause is fixed, **do not re-run adpatch from scratch**. Use adctrl to restart only the failed worker.

\`\`\`
$ adctrl

AD Controller Menu
==================
1. Show worker status
2. Tell worker to restart a failed job
3. Tell worker to quit
4. Tell manager to recalibrate workers
5. Tell manager to quit after current task
6. Quit

Enter your choice: 1

Worker 2: FAILED — qpprg.ldt

Enter your choice: 2

Enter the worker number: 2

Worker 2 status changed to: FIXED/RESTART
\`\`\`

The adpatch manager detects the FIXED/RESTART status within its next polling interval (typically 30–60 seconds) and resubmits the job to worker 2. Watch the worker log:

\`\`\`bash
tail -f $APPL_TOP/admin/$TWO_TASK/log/adwork002.log
# Expected: "COMPLETED: file qpprg.ldt on worker 2 for product qp"
\`\`\`

---

## Performance and Stability Checks After Patch Completion

\`\`\`sql
-- Verify no remaining failed jobs
SELECT COUNT(*) failed_jobs
FROM   applsys.ad_deferred_jobs
WHERE  execution_status = 'F';

-- Check patch completion status
SELECT patch_run_id,
       name,
       start_date,
       end_date,
       ROUND((end_date - start_date)*24,2) hours_elapsed
FROM   applsys.ad_patch_runs
ORDER  BY start_date DESC
FETCH  FIRST 5 ROWS ONLY;

-- Confirm the bug is marked applied
SELECT bug_number, creation_date, platform_code
FROM   applsys.ad_bugs
WHERE  bug_number = '28458567';
\`\`\`

---

## Prevention Checklist

Before applying any EBS patch:

1. **Verify the download MD5** against the checksum listed on MOS before extraction.
2. **Check the Readme** for prerequisite patches — apply them in the documented order.
3. **Confirm ATG / FND patch level** meets the minimum requirement stated in the Readme.
4. **Use a staging filesystem with sufficient inodes** — NFS mounts with aggressive caching can produce partial files under load.
5. **Set NLS_LANG consistently** across the OS session that runs adpatch and the session that extracted the patch files.
6. **Run adpatch in no-interactive mode** (\`adpatch defaultsfile=\$APPL_TOP/admin/adalldefaults.txt\`) and log session output to a timestamped file for audit.

---

## Summary

An EBS worker failure reporting **"An entity data line was expected"** during LDT processing almost always has one of two root causes: the \`.ldt\` file is truncated or corrupted from the extraction process, or there is a prerequisite FND/ATG version that the patch assumes but has not been applied. The investigation path is short — check the file integrity first (BEGIN/END balance, file size, MD5 against zip), then check the FND product version. The recovery is clean: re-extract the file, fix the worker via adctrl, and let the manager resume without restarting the patch session. No data is at risk; the patch simply continues from where it stopped.
`.trim();

async function main() {
  await db.insert(posts).values({
    title: 'EBS Patching: Diagnosing and Fixing FNDLOAD LDT Worker Failures',
    slug,
    excerpt: 'A worker reports "An entity data line was expected" during EBS patching — the FNDLOAD loader fails on an .ldt file and all workers halt. Covers root cause analysis (truncation vs prerequisite gap vs character set mismatch), SQL investigation scripts, file integrity checks, and how to resume a failed patch session cleanly using adctrl.',
    content,
    category: 'ebs-suite',
    isPremium: false,
    published: true,
    publishedAt: new Date(),
  });
  console.log('Inserted:', slug);
}

main().catch(console.error);
