import { config } from 'dotenv';
config({ path: '.env.local' });

import { db } from './index';
import { posts } from './schema';
import { eq } from 'drizzle-orm';

const slug = 'ebs-tns-ifile-context-file-internal-concurrent-manager';

const content = `
Oracle EBS generates most of its configuration files automatically through AutoConfig — tnsnames.ora included. That convenience comes with a constraint: every time AutoConfig runs, it overwrites the generated tnsnames.ora with a fresh copy derived from the context file. Any manual additions made directly to the generated file are silently lost.

The TNS ifile mechanism exists to solve this. A single IFILE directive in the AutoConfig-generated tnsnames.ora points to a second file that AutoConfig does not touch. DBAs maintain that second file independently, and Oracle Net reads both files together on every connection attempt.

In a multi-tier EBS deployment — where two or more application server nodes each run their own set of concurrent managers — the ifile is not a single shared artifact. Each node has its own TNS admin directory, its own generated tnsnames.ora, and its own ifile. Each node's ifile must independently contain any TNS entries that processes on that node need, including the CP_TWO_TASK service that every concurrent manager process uses to connect to the database.

This post covers how the TNS ifile works, where its path is stored in the \`\$CONTEXT_FILE\`, how the Internal Concurrent Manager depends on it at startup, how a multi-tier deployment multiplies the ifile maintenance surface, and how the TNS admin directory structure differs across EBS 11i, R12.1.3, and R12.2.x.

---

## The EBS Code Tree and TNS Admin Directories

The location of TNS configuration files — tnsnames.ora, sqlnet.ora, and the ifile — is directly tied to the EBS code tree structure, which changed significantly between releases. In a multi-tier setup, the key fact is that each application server node has its own instance-level directory tree and therefore its own TNS admin directory.

### EBS 11i — Multi-Tier Layout

In 11i, the application middle tier uses the iAS Oracle Home for its web server and Forms runtime. In a multi-node 11i installation, \`\$APPL_TOP\` is typically mounted from shared NFS so all nodes share the product code, but each node has its own iAS Oracle Home installed locally.

The context file name incorporates the hostname, so each node has a separate context file even though APPL_TOP is shared:

\`\`\`
$APPL_TOP/admin/
  EBSPRD_appnode01.xml     ← context file for node 1 (s_ifile → node1 path)
  EBSPRD_appnode02.xml     ← context file for node 2 (s_ifile → node2 path)
\`\`\`

Each node's TNS admin is under its own local iAS Oracle Home:

\`\`\`
Node 1: /u01/applocal/appnode01/iAS/
  network/
    admin/
      tnsnames.ora          ← generated by AutoConfig for node 1
      sqlnet.ora
      ifile.ora             ← DBA-maintained for node 1

Node 2: /u01/applocal/appnode02/iAS/
  network/
    admin/
      tnsnames.ora          ← generated by AutoConfig for node 2
      sqlnet.ora
      ifile.ora             ← DBA-maintained for node 2
\`\`\`

\`TNS_ADMIN\` in each node's environment script points to that node's local iAS home \`network/admin\` directory. Running AutoConfig on node 1 regenerates node 1's tnsnames.ora only; node 2 is unaffected until AutoConfig runs there separately.

### EBS R12.1.3 — Multi-Tier Layout

R12.1 introduced the \`\$INST_TOP\` concept: each application server node has its own instance directory that holds all generated, environment-specific, and node-specific files. \`\$APPL_TOP\` remains on shared NFS, but \`\$INST_TOP\` is node-local (or stored in a node-specific subdirectory on shared storage).

\`\`\`
Shared (NFS):
  /u01/applmgr/EBSPRD/apps/apps_st/appl/    ← $APPL_TOP (shared)
  /u01/applmgr/EBSPRD/apps/apps_st/comn/    ← $COMMON_TOP (shared)

Node-specific:
  /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/   ← $INST_TOP for node 1
    appl/admin/
      EBSPRD_appnode01.xml                   ← context file for node 1
    ora/
      10.1.2/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 1)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained (node 1)
      10.1.3/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 1)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained (node 1)

  /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode02/   ← $INST_TOP for node 2
    appl/admin/
      EBSPRD_appnode02.xml                   ← context file for node 2
    ora/
      10.1.2/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 2)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained (node 2)
      10.1.3/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 2)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained (node 2)
\`\`\`

Forms and Reports processes use the 10.1.2 TNS admin. OC4J (OA Framework / self-service) uses the 10.1.3 TNS admin. Each has its own ifile. A change made to the ifile under 10.1.2 on node 1 does not propagate to node 2, or to the 10.1.3 ifile on the same node, without manual action.

### EBS R12.2.x — Multi-Tier Layout

R12.2 replaces \`\$APPL_TOP\` with dual editioned file systems (\`fs1\` and \`fs2\`) plus a shared non-editioned file system (\`fs_ne\`). The \`inst\` directory is non-editioned and node-specific. As in R12.1, each node has its own subdirectory under \`inst/apps/\`:

\`\`\`
Shared (editioned — alternates between run and patch):
  /u01/applmgr/EBSPRD/fs1/EBSapps/appl/    ← APPL_TOP (fs1)
  /u01/applmgr/EBSPRD/fs2/EBSapps/appl/    ← APPL_TOP (fs2)

Shared (non-editioned):
  /u01/applmgr/EBSPRD/fs_ne/EBSapps/appl/  ← $APPL_TOP_NE

Node-specific (non-editioned):
  /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/   ← inst for node 1
    appl/admin/
      EBSPRD_appnode01.xml                   ← context file for node 1
    ora/
      10.1.2/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 1)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained; survives adop cycles

  /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode02/   ← inst for node 2
    appl/admin/
      EBSPRD_appnode02.xml                   ← context file for node 2
    ora/
      10.1.2/
        network/admin/
          tnsnames.ora                       ← generated by AutoConfig (node 2)
          sqlnet.ora
          ifile.ora                          ← DBA-maintained; survives adop cycles
\`\`\`

Because the \`inst\` directory is not part of the editioned file system, the ifile survives \`adop\` patching cycles without being overwritten. However, the ifile on node 1 and the ifile on node 2 remain separate files and must be maintained independently.

---

## What Is the TNS ifile?

The \`IFILE\` directive is a standard Oracle Net parameter supported in \`tnsnames.ora\`, \`sqlnet.ora\`, and \`listener.ora\`. When Oracle Net reads a configuration file and encounters an IFILE directive, it reads the referenced file as if its contents were embedded inline at that point.

In a generated \`tnsnames.ora\`, the IFILE entry looks like:

\`\`\`
IFILE = /u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/ifile.ora
\`\`\`

Oracle Net then reads \`ifile.ora\` and merges its entries with those in \`tnsnames.ora\`. From the perspective of any process resolving a service name — sqlplus, JDBC thin, FNDLIBR — entries in \`ifile.ora\` are indistinguishable from entries declared directly in \`tnsnames.ora\`.

Oracle Net also supports **nested ifiles**: an ifile.ora can itself contain an IFILE directive pointing to a second file. This is useful in multi-tier deployments where each node has a local ifile that in turn references a shared master ifile on NFS — the local file carries node-specific entries and the master carries entries common to all nodes.

### What goes in the ifile

The ifile holds TNS service name entries that need to survive AutoConfig. Common entries:

- **CP_TWO_TASK service** — a dedicated service for concurrent processing database connections, particularly when it differs from the general TWO_TASK (RAC node affinity, dedicated server mode, ADG offload)
- **Read-only standby service** — a service registered on an Active Data Guard standby for offloading reporting queries
- **RAC-specific load balancing services** — services targeting specific RAC nodes or using specific connection policies
- **Third-party application service aliases** — connections to external databases for ERP integrations or ETL pipelines
- **Monitoring tool service names** — entries used by OEM agents or third-party monitoring that must survive AutoConfig runs

### What the ifile is not

The ifile is not:
- A replacement for tnsnames.ora — it supplements it
- A place to override entries in tnsnames.ora — if the same alias exists in both files, behavior is implementation-defined and should be avoided
- Automatically validated by AutoConfig — errors in the ifile are silent until a connection attempt fails
- Automatically propagated across nodes — in a multi-tier setup, each node's ifile is independent

---

## The s_ifile Parameter in \$CONTEXT_FILE

AutoConfig writes the IFILE directive into the generated tnsnames.ora based on the \`s_ifile\` parameter in the context file. The entry in \`\$CONTEXT_FILE\` looks like:

\`\`\`xml
<s_ifile oa_var="s_ifile">/u01/applmgr/EBSPRD/inst/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/ifile.ora</s_ifile>
\`\`\`

To view the current value:

\`\`\`bash
grep -i "s_ifile" \$CONTEXT_FILE
\`\`\`

When AutoConfig runs, it writes this path into the generated tnsnames.ora as:

\`\`\`
IFILE = <value of s_ifile>
\`\`\`

### s_ifile is node-specific

Because the context file name incorporates the hostname (e.g., \`EBSPRD_appnode01.xml\`), and \`s_ifile\` typically references a path that also incorporates the hostname (via INST_TOP), each node's \`s_ifile\` value is different. Node 1's context file points to node 1's ifile; node 2's context file points to node 2's ifile.

This means:
- Adding a TNS entry to node 1's ifile does not affect node 2
- Running AutoConfig on node 1 does not affect node 2's tnsnames.ora or ifile
- In a three-node deployment, there are three separate \`s_ifile\` values (one per context file) and three separate ifile.ora files to maintain

### Shared ifile pattern (single NFS path for all nodes)

If all nodes are configured with the same \`s_ifile\` value pointing to a shared NFS location, AutoConfig on each node writes the same IFILE directive into each node's tnsnames.ora:

\`\`\`xml
<!-- Same value in all three context files -->
<s_ifile oa_var="s_ifile">/shared/nfs/ebsprd/tns/ifile.ora</s_ifile>
\`\`\`

This eliminates the per-node ifile maintenance burden — one edit to the shared ifile propagates to all nodes immediately. The trade-off is that the ifile becomes dependent on NFS availability: if the NFS mount is unavailable when Oracle Net initializes, processes that need entries from the ifile fail.

### What happens when s_ifile is blank or wrong

If \`s_ifile\` is empty in the context file, AutoConfig generates a tnsnames.ora with no IFILE directive. Any custom TNS entries that existed in the ifile are no longer reachable.

If \`s_ifile\` points to a path that does not exist at runtime, Oracle Net silently ignores the IFILE directive. No error is raised — the failure surfaces only when a process attempts to resolve a service name that was defined only in the missing ifile.

---

## Multiple Mid-Tier Nodes: ifile Maintenance and ICM Node Considerations

### Every node needs the CP_TWO_TASK service

The CP_TWO_TASK service is used by every concurrent manager process — the ICM and all worker managers (Standard Manager, Output Post Processor, Conflict Resolution Manager, and any custom managers). In a three-node EBS R12.1.3 deployment where concurrent managers are distributed across all three nodes, each node's ifile must contain the CP_TWO_TASK service definition. A broken ifile on node 3 will not affect the ICM (which runs on node 1), but it will cause all worker CMs on node 3 to fail to start or to crash when they attempt their database connection.

### The ICM node

The Internal Concurrent Manager runs on a single designated node — typically the primary application tier node. Its node assignment is determined by the host configured in \`\$FND_TOP/secure/\` and the concurrent processing startup scripts. To identify the current ICM node:

\`\`\`sql
SELECT node_name,
       manager_type,
       concurrent_queue_name
FROM   fnd_concurrent_queues
WHERE  manager_type = 'I';
\`\`\`

The ICM node's ifile is the highest-priority ifile to fix when the ICM fails with ORA-12154 — but fixing only the ICM node's ifile while leaving other nodes broken will cause worker CM failures that appear after the ICM restarts and attempts to bring up managers on those nodes.

### ifile synchronization strategies

**Manual copy** — The simplest approach. After updating the ifile on one node, copy it to all other nodes:

\`\`\`bash
# From node 1, push to node 2 and node 3
scp \${IFILE_PATH} applmgr@appnode02:\${INST_TOP_N2}/ora/10.1.2/network/admin/ifile.ora
scp \${IFILE_PATH} applmgr@appnode03:\${INST_TOP_N3}/ora/10.1.2/network/admin/ifile.ora
\`\`\`

Risk: requires remembering to copy after every change. Appropriate for environments with infrequent ifile changes.

**Shared NFS ifile** — Set \`s_ifile\` in all context files to a single shared NFS path. All nodes read the same physical file. One edit propagates immediately to all nodes.

\`\`\`bash
# Verify all context files agree on the shared path
for CTX in /u01/applmgr/EBSPRD/inst/apps/*/appl/admin/*.xml; do
  echo "\$(basename \${CTX}): \$(grep -i 's_ifile' \${CTX} | sed 's/.*>\\(.*\\)<.*/\\1/' | tr -d '[:space:]')"
done
\`\`\`

**Nested ifile** — Each node's local ifile.ora contains a single IFILE directive pointing to a shared master on NFS. The local file can hold node-specific entries (if any); the master holds the common entries:

\`\`\`
# /local/inst/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/ifile.ora
IFILE = /shared/nfs/ebsprd/tns/master_ifile.ora
# (node-specific entries below, if needed)
\`\`\`

This combines the per-node flexibility of local ifiles with the maintenance simplicity of a single shared master.

**Configuration management** — Puppet, Ansible, or Chef distributes the ifile content to all nodes from a central source. The playbook or manifest defines the ifile entries; a deploy run pushes to all nodes simultaneously.

### AutoConfig in a multi-tier environment

AutoConfig must be run separately on each node. Running AutoConfig on node 1 regenerates node 1's tnsnames.ora and leaves all other nodes unchanged. The standard order for running AutoConfig in a multi-tier setup is:

1. DB tier node(s)
2. Primary application tier node (ICM node)
3. Secondary application tier node(s)

After AutoConfig on each node, verify that the IFILE directive is still present in the newly generated tnsnames.ora on that node, and that the ifile still exists at the path referenced.

### Per-version ifile locations in a two-node deployment

| Version | Node | TNS admin path | ifile path |
|---------|------|----------------|-----------|
| 11i | appnode01 | \`\$IAS_OH_N1/network/admin/\` | Same dir, \`ifile.ora\` |
| 11i | appnode02 | \`\$IAS_OH_N2/network/admin/\` | Same dir, \`ifile.ora\` |
| R12.1.3 | appnode01 | \`\$INST_TOP_N1/ora/10.1.2/network/admin/\` | Same dir, \`ifile.ora\` |
| R12.1.3 | appnode02 | \`\$INST_TOP_N2/ora/10.1.2/network/admin/\` | Same dir, \`ifile.ora\` |
| R12.1.3 | appnode01 | \`\$INST_TOP_N1/ora/10.1.3/network/admin/\` | Same dir, \`ifile.ora\` (OC4J/OAF) |
| R12.1.3 | appnode02 | \`\$INST_TOP_N2/ora/10.1.3/network/admin/\` | Same dir, \`ifile.ora\` (OC4J/OAF) |
| R12.2.x | appnode01 | \`\$INST_TOP/apps/EBSPRD_appnode01/ora/10.1.2/network/admin/\` | Same dir, \`ifile.ora\` |
| R12.2.x | appnode02 | \`\$INST_TOP/apps/EBSPRD_appnode02/ora/10.1.2/network/admin/\` | Same dir, \`ifile.ora\` |

---

## The Internal Concurrent Manager and TNS ifile

The Internal Concurrent Manager (ICM) is the master process that starts, monitors, and shuts down all other concurrent managers. It connects to the database at startup using the service name in the \`CP_TWO_TASK\` environment variable.

### The ICM startup TNS dependency chain

\`\`\`
ICM startup (on ICM node only)
     │
     ▼
Reads CP_TWO_TASK environment variable (set by AutoConfig from s_cp_twotask)
     │
     ▼
Calls Oracle Net to resolve CP_TWO_TASK service name
     │
     ▼
Oracle Net reads \$TNS_ADMIN/tnsnames.ora (node-specific)
     │
     ├── Service found in tnsnames.ora → connect succeeds
     │
     └── Service NOT found in tnsnames.ora
              │
              ▼
         Oracle Net reads IFILE entry from tnsnames.ora (node-specific)
              │
              ├── ifile.ora exists and contains the service → connect succeeds
              │
              └── ifile missing, empty, or service not defined → ORA-12154
\`\`\`

Worker CMs on all other nodes follow the same dependency chain using their own node-local tnsnames.ora and ifile.

### When CP_TWO_TASK is defined in the ifile

This is the most common source of ICM startup failures after an AutoConfig run or a code tree migration. If a DBA placed the Concurrent Processing service definition in ifile.ora rather than in tnsnames.ora — which is a valid configuration — and then AutoConfig changes the \`s_ifile\` path or the path becomes inaccessible, the ICM fails to start with:

\`\`\`
ORA-12154: TNS:could not resolve the connect identifier specified
\`\`\`

The error message does not indicate whether the failure was in tnsnames.ora or in the ifile. The resolution is:

\`\`\`bash
# Check whether the IFILE directive is present in the generated tnsnames.ora
grep -i "ifile" \$TNS_ADMIN/tnsnames.ora

# Check whether the ifile exists and is readable
cat \$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')

# Verify the CP_TWO_TASK service is in either file
tnsping \$CP_TWO_TASK
\`\`\`

### ICM and the ifile across EBS versions — single vs. multi-tier

| Version | ICM node TNS_ADMIN | ICM node ifile | Worker CM nodes |
|---------|-------------------|----------------|-----------------|
| 11i | \`\$IAS_OH_N1/network/admin\` | \`ifile.ora\` in same dir | Each node has own iAS OH and own ifile |
| R12.1.3 | \`\$INST_TOP_N1/ora/10.1.2/network/admin\` | \`ifile.ora\` in same dir | Each node has own INST_TOP and own ifiles (10.1.2 and 10.1.3) |
| R12.2.x | \`\$INST_TOP/apps/EBSPRD_appnode01/ora/10.1.2/network/admin\` | \`ifile.ora\` in same dir; non-editioned | Each node has own inst/ subdir and own ifile; all survive adop |

---

## Using the TNS ifile on the Application Tier

### Locate the active ifile path

\`\`\`bash
# From context file
grep -i "s_ifile" \$CONTEXT_FILE

# From the generated tnsnames.ora (confirms AutoConfig wrote the directive)
grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora

# Confirm the file exists and is readable
IFILE_PATH=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
ls -lh "\${IFILE_PATH}"
\`\`\`

### Add a custom TNS entry to the ifile

\`\`\`bash
# Never edit tnsnames.ora directly — edit the ifile
vi "\${IFILE_PATH}"

# Add the entry using standard TNS syntax:
# EBSPRD_CP =
#   (DESCRIPTION =
#     (ADDRESS = (PROTOCOL = TCP)(HOST = dbhost.example.com)(PORT = 1521))
#     (CONNECT_DATA =
#       (SERVER = DEDICATED)
#       (SERVICE_NAME = EBSPRD_CP)
#     )
#   )
\`\`\`

### Propagate to all other nodes (multi-tier)

After editing on the current node, push to all other application tier nodes:

\`\`\`bash
# Identify all application tier nodes from the inst directory
ls /u01/applmgr/EBSPRD/inst/apps/

# Push ifile to each other node (R12.1.3/R12.2.x example)
for NODE in appnode02 appnode03; do
  REMOTE_IFILE="/u01/applmgr/EBSPRD/inst/apps/EBSPRD_\${NODE}/ora/10.1.2/network/admin/ifile.ora"
  scp "\${IFILE_PATH}" applmgr@\${NODE}:"\${REMOTE_IFILE}"
  echo "Pushed to \${NODE}: \${REMOTE_IFILE}"
done

# Verify on each remote node
for NODE in appnode02 appnode03; do
  ssh applmgr@\${NODE} "source /u01/applmgr/EBSPRD/EBSapps.env run && tnsping \${CP_TWO_TASK}"
done
\`\`\`

### Verify after an AutoConfig run

AutoConfig regenerates tnsnames.ora but does not touch ifile.ora. After any AutoConfig run, confirm on each node that ran AutoConfig:

\`\`\`bash
# 1. IFILE directive is still in the generated tnsnames.ora
grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora

# 2. The ifile path in tnsnames.ora matches s_ifile in the context file
TNSNAMES_IFILE=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
CTX_IFILE=\$(grep -i "s_ifile" \$CONTEXT_FILE | sed 's/.*>\\(.*\\)<.*/\\1/' | tr -d '[:space:]')
echo "tnsnames.ora IFILE : \${TNSNAMES_IFILE}"
echo "Context file s_ifile: \${CTX_IFILE}"

# 3. Custom entries still resolve
tnsping \$CP_TWO_TASK
\`\`\`

### R12.2 — ifile after an adop cycle

In R12.2, the \`inst\` directory is not editioned, so the ifile is not affected by \`adop phase=cutover\`. Verify this after each online patching cycle on each node:

\`\`\`bash
source /u01/applmgr/EBSPRD/EBSapps.env run
grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora
tnsping \$CP_TWO_TASK
\`\`\`

If the IFILE directive disappears from tnsnames.ora after a cutover, the adop cycle regenerated tnsnames.ora using a context file where \`s_ifile\` was blank. Correct the context file and re-run AutoConfig on the affected node.

---

## Using the TNS ifile on the Database Tier

The database tier has its own \`tnsnames.ora\` — separate from the application tier's. This file is also regenerated by the DB-tier AutoConfig run and also supports an IFILE directive. In a RAC environment, each database node has its own local tnsnames.ora (though the DB-tier AutoConfig typically generates identical content for each node).

### Locate the DB-tier TNS admin

\`\`\`bash
# Standard location
echo \$ORACLE_HOME/network/admin

# Verify which tnsnames.ora is in use
echo \$TNS_ADMIN
ls -lh \$TNS_ADMIN/tnsnames.ora
\`\`\`

### DB-tier ifile use cases

The most common entries added to the DB-tier ifile:

- **Cross-database dblinks** — remote database connection strings for database links that the EBS database creates
- **Standby connection aliases** — connection strings for the physical standby database, used in switchover or DR testing
- **Monitoring tool service names** — entries used by OEM agents or third-party monitoring that must survive AutoConfig runs on the DB tier

### Add an entry to the DB-tier ifile

\`\`\`bash
# Locate the DB-tier ifile
DB_IFILE=\$(grep -i "^IFILE" \$ORACLE_HOME/network/admin/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')

# If no IFILE directive exists yet, create one
if [ -z "\${DB_IFILE}" ]; then
  DB_IFILE=\$ORACLE_HOME/network/admin/ifile.ora
  echo "IFILE = \${DB_IFILE}" >> \$ORACLE_HOME/network/admin/tnsnames.ora
fi

# Edit the ifile
vi "\${DB_IFILE}"
\`\`\`

### DB-tier AutoConfig considerations

The DB-tier AutoConfig reads its own context file (stored in the \`appsutil\` path on the database node). If \`s_ifile\` is set in the DB-tier context file, AutoConfig generates a DB-tier tnsnames.ora with the IFILE directive. In a RAC environment with multiple DB nodes, each DB node has its own DB-tier context file and its own DB-tier tnsnames.ora.

\`\`\`bash
# On the database node
source /u01/oracle/EBSPRD/appsutil/env/EBSPRD_\$(hostname -s).env
grep -i "s_ifile" \$CONTEXT_FILE
\`\`\`

---

## Troubleshooting: ICM Fails to Start After AutoConfig

**Symptom:** ICM fails with ORA-12154 immediately after an AutoConfig run. Forms sessions and self-service sessions work normally (because their TWO_TASK service is in tnsnames.ora), but the ICM cannot connect.

The selective failure pattern — ICM and concurrent managers fail, Forms succeeds — is the diagnostic signature that the CP_TWO_TASK service is defined in the ifile and the ifile chain is broken.

**Diagnosis on the ICM node:**

\`\`\`bash
# 1. What service is the ICM trying to connect to?
echo "CP_TWO_TASK: \$CP_TWO_TASK"

# 2. Does that service resolve?
tnsping \$CP_TWO_TASK
# If this returns ORA-12154, the service is not in tnsnames.ora or ifile

# 3. Is IFILE in the generated tnsnames.ora?
grep -i "IFILE" \$TNS_ADMIN/tnsnames.ora

# 4. Does the ifile exist?
IFILE_PATH=\$(grep -i "^IFILE" \$TNS_ADMIN/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
[ -f "\${IFILE_PATH}" ] && echo "ifile exists" || echo "ifile MISSING"

# 5. Is the CP_TWO_TASK service in the ifile?
grep -i "\$CP_TWO_TASK" "\${IFILE_PATH}"
\`\`\`

**Also check other nodes:**

If the ICM node is healthy after remediation but worker CMs on other nodes still fail, those nodes have their own ifile issues:

\`\`\`bash
for NODE in appnode02 appnode03; do
  echo "=== \${NODE} ==="
  ssh applmgr@\${NODE} "
    source /u01/applmgr/EBSPRD/EBSapps.env run 2>/dev/null || source /u01/applmgr/EBSPRD/EBSPRD_\${NODE}.env
    IFILE=\$(grep -i '^IFILE' \${TNS_ADMIN}/tnsnames.ora | awk -F'=' '{print \$2}' | tr -d ' ')
    echo 'tnsnames IFILE: '\${IFILE}
    [ -f \"\${IFILE}\" ] && echo 'ifile EXISTS' || echo 'ifile MISSING'
    tnsping \${CP_TWO_TASK} 2>&1 | tail -2
  "
done
\`\`\`

**Resolution options:**

Option A — Restore the ifile at the path referenced in tnsnames.ora and propagate to all nodes.

Option B — Correct \`s_ifile\` in each node's context file and re-run AutoConfig on each node.

Option C — Configure all context files to use a shared NFS ifile path so subsequent AutoConfig runs maintain consistency automatically.

---

## Summary

The TNS ifile is the mechanism that allows custom Oracle Net service name entries to survive AutoConfig regeneration of tnsnames.ora. Its path is stored in the \`s_ifile\` parameter in the Applications Context File (\`\$CONTEXT_FILE\`), and AutoConfig writes an \`IFILE =\` directive into the generated tnsnames.ora that points to it.

In a multi-tier EBS deployment, each application server node has its own context file, its own TNS admin directory, and its own ifile. Changes to one node's ifile do not propagate to other nodes automatically. Every node that runs concurrent managers — including worker CM nodes, not just the ICM node — needs the CP_TWO_TASK service to be resolvable, either through its local tnsnames.ora or its local ifile. A broken ifile on a worker CM node will not prevent the ICM from starting, but it will prevent all concurrent managers on that node from connecting to the database.

The three ifile synchronization strategies (manual copy, shared NFS ifile, nested ifile with shared master) each make a different trade-off between simplicity and NFS dependency. In environments where ifile changes are infrequent, manual copy is sufficient. In environments with many nodes or frequent changes, a shared NFS ifile controlled via \`s_ifile\` in all context files eliminates the per-node maintenance burden at the cost of adding an NFS dependency to the Oracle Net resolution path.

The selective ICM failure signature — ICM fails, Forms sessions succeed — points reliably to the CP_TWO_TASK service being inaccessible through the ifile chain. Verifying tnsnames.ora IFILE directive → ifile existence → ifile content → tnsping on each node identifies which link is broken and on which node.
`.trim();

async function main() {
  await db.update(posts).set({
    title: 'EBS TNS ifile and the Internal Concurrent Manager: Context File Parameter, Code Tree Paths, Multi-Tier ifile Maintenance, and ICM Startup Dependency Across 11i, R12.1.3, and R12.2.x',
    excerpt: 'The TNS ifile lets custom Oracle Net entries survive AutoConfig regeneration of tnsnames.ora. In a multi-tier EBS deployment, each application server node has its own TNS admin directory and its own ifile — changes on one node do not propagate to others. Every concurrent manager node, not just the ICM node, needs the CP_TWO_TASK service resolvable through its local tnsnames.ora or ifile. This post covers the ifile mechanism, s_ifile context parameter, multi-tier directory layouts for 11i/R12.1.3/R12.2.x, ifile synchronization strategies, and the ICM startup dependency chain.',
    content,
    publishedAt: new Date(),
  }).where(eq(posts.slug, slug));
  console.log('Updated:', slug);
}

main().catch(console.error);
